id: cafc6f55-b05a-4349-8c21-dd05fb7db2b4
version: 55
name: ServiceNow Test
description: This playbook tests the SEPM integration commands.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b9912ecc-bae9-40c5-8a5f-7cf8db6329f0
    type: start
    task:
      id: b9912ecc-bae9-40c5-8a5f-7cf8db6329f0
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 6f1a76a9-7773-4c5d-84de-a675a57f0bb9
    type: regular
    task:
      id: 6f1a76a9-7773-4c5d-84de-a675a57f0bb9
      version: -1
      name: DeleteContext (all)
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all: "yes"
      key: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 0203e572-261e-471f-83ca-66d137ab8be4
    type: regular
    task:
      id: 0203e572-261e-471f-83ca-66d137ab8be4
      version: -1
      name: 'servicenow-incident-create (Assignee: Johnny Doe)'
      description: Create new ServiceNow ticket
      script: ServiceNow|||servicenow-incident-create
      type: regular
      iscommand: true
      brand: ServiceNow
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      active: ""
      activity_due: ""
      additional_assignee_list: ""
      approval: ""
      approval_history: ""
      approval_set: ""
      assigned_to: Johnny Doe
      assignment_group: ""
      business_duration: ""
      business_service: ""
      business_stc: ""
      calendar_duration: ""
      caller_id: ""
      category: Telephony
      caused_by: ""
      close_code: ""
      close_notes: ""
      closed_at: ""
      closed_by: ""
      cmdb_ci: ""
      comments: ""
      comments_and_work_notes: ""
      company: ""
      contact_type: ""
      correlation_display: ""
      correlation_id: ""
      delivery_plan: ""
      description: ""
      display: ""
      due_date: ""
      escalation: ""
      expected_start: ""
      follow_up: ""
      group_list: ""
      impact: ""
      incident_state: ""
      knowledge: ""
      location: ""
      made_sla: ""
      notify: ""
      number: ""
      order: ""
      parent: ""
      parent_incident: ""
      priority: ""
      problem_id: ""
      reassignment_count: ""
      reopen_count: ""
      resolved_at: ""
      resolved_by: ""
      rfc: ""
      severity: ""
      short_description: Ticket 1 description
      sla_due: ""
      subcategory: ""
      sys_updated_by: ""
      sys_updated_on: ""
      urgency: ""
      user_input: ""
      watch_list: ""
      work_end: ""
      work_notes: ""
      work_notes_list: ""
      work_start: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 515
        }
      }
  "6":
    id: "6"
    taskid: 00786b1c-4a8a-4d98-8291-0a4fd2850a28
    type: regular
    task:
      id: 00786b1c-4a8a-4d98-8291-0a4fd2850a28
      version: -1
      name: VerifyContextFields
      scriptName: VerifyContextFields
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      field1: Ticket.Summary
      field2: Ticket.Assignee
      field3: ""
      field4: ""
      field5: ""
      value1: Ticket 1 description
      value2: Johnny Doe
      value3: ""
      value4: ""
      value5: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 689
        }
      }
  "7":
    id: "7"
    taskid: 260124a3-4659-47af-8c42-0448f5cc5d9f
    type: regular
    task:
      id: 260124a3-4659-47af-8c42-0448f5cc5d9f
      version: -1
      name: 'servicenow-incident-create (Assignee: Lucy Liu)'
      description: Create new ServiceNow ticket
      script: ServiceNow|||servicenow-incident-create
      type: regular
      iscommand: true
      brand: ServiceNow
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      active: ""
      activity_due: ""
      additional_assignee_list: ""
      approval: ""
      approval_history: ""
      approval_set: ""
      assigned_to: Lucy Liu
      assignment_group: ""
      business_duration: ""
      business_service: ""
      business_stc: ""
      calendar_duration: ""
      caller_id: ""
      category: Telephony
      caused_by: ""
      close_code: ""
      close_notes: ""
      closed_at: ""
      closed_by: ""
      cmdb_ci: ""
      comments: ""
      comments_and_work_notes: ""
      company: ""
      contact_type: ""
      correlation_display: ""
      correlation_id: ""
      delivery_plan: ""
      description: ""
      display: ""
      due_date: ""
      escalation: ""
      expected_start: ""
      follow_up: ""
      group_list: ""
      impact: ""
      incident_state: ""
      knowledge: ""
      location: ""
      made_sla: ""
      notify: ""
      number: ""
      order: ""
      parent: ""
      parent_incident: ""
      priority: ""
      problem_id: ""
      reassignment_count: ""
      reopen_count: ""
      resolved_at: ""
      resolved_by: ""
      rfc: ""
      severity: ""
      short_description: Ticket 2 description
      sla_due: ""
      subcategory: ""
      sys_updated_by: ""
      sys_updated_on: ""
      urgency: ""
      user_input: ""
      watch_list: ""
      work_end: ""
      work_notes: ""
      work_notes_list: ""
      work_start: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 865
        }
      }
  "8":
    id: "8"
    taskid: 6429c973-9d13-415c-8502-be85f0d8c8e2
    type: regular
    task:
      id: 6429c973-9d13-415c-8502-be85f0d8c8e2
      version: -1
      name: VerifyContextFields
      scriptName: VerifyContextFields
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      field1: Ticket.[1].Summary
      field2: Ticket.[1].Assignee
      field3: ""
      field4: ""
      field5: ""
      value1: Ticket 2 description
      value2: Lucy Liu
      value3: ""
      value4: ""
      value5: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1040
        }
      }
  "10":
    id: "10"
    taskid: cf883242-923b-4dd1-8ff8-54fb1a364728
    type: regular
    task:
      id: cf883242-923b-4dd1-8ff8-54fb1a364728
      version: -1
      name: servicenow-incident-create (Dani, Monitoring)
      description: Create new ServiceNow ticket
      script: ServiceNow|||servicenow-incident-create
      type: regular
      iscommand: true
      brand: ServiceNow
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      active: ""
      activity_due: ""
      additional_assignee_list: ""
      approval: ""
      approval_history: ""
      approval_set: ""
      assigned_to: Moshe
      assignment_group: ""
      business_duration: ""
      business_service: ""
      business_stc: ""
      calendar_duration: ""
      caller_id: ""
      category: Monitoring
      caused_by: ""
      close_code: ""
      close_notes: ""
      closed_at: ""
      closed_by: ""
      cmdb_ci: ""
      comments: ""
      comments_and_work_notes: ""
      company: ""
      contact_type: ""
      correlation_display: ""
      correlation_id: ""
      delivery_plan: ""
      description: ""
      display: ""
      due_date: ""
      escalation: ""
      expected_start: ""
      follow_up: ""
      group_list: ""
      impact: ""
      incident_state: ""
      knowledge: ""
      location: ""
      made_sla: ""
      notify: ""
      number: ""
      order: ""
      parent: ""
      parent_incident: ""
      priority: ""
      problem_id: ""
      reassignment_count: ""
      reopen_count: ""
      resolved_at: ""
      resolved_by: ""
      rfc: ""
      severity: ""
      short_description: Ticket test description
      sla_due: ""
      subcategory: ""
      sys_updated_by: ""
      sys_updated_on: ""
      urgency: ""
      user_input: ""
      watch_list: ""
      work_end: ""
      work_notes: ""
      work_notes_list: ""
      work_start: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1360
        }
      }
  "12":
    id: "12"
    taskid: 4c97ecd8-5b56-421f-8f94-ffcdfb48f3b4
    type: regular
    task:
      id: 4c97ecd8-5b56-421f-8f94-ffcdfb48f3b4
      version: -1
      name: servicenow-incident-create (Moshe, IT)
      description: Create new ServiceNow ticket
      script: ServiceNow|||servicenow-incident-create
      type: regular
      iscommand: true
      brand: ServiceNow
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      active: ""
      activity_due: ""
      additional_assignee_list: ""
      approval: ""
      approval_history: ""
      approval_set: ""
      assigned_to: Moshe
      assignment_group: ""
      business_duration: ""
      business_service: ""
      business_stc: ""
      calendar_duration: ""
      caller_id: ""
      category: Monitoring
      caused_by: ""
      close_code: ""
      close_notes: ""
      closed_at: ""
      closed_by: ""
      cmdb_ci: ""
      comments: ""
      comments_and_work_notes: ""
      company: ""
      contact_type: ""
      correlation_display: ""
      correlation_id: ""
      delivery_plan: ""
      description: ""
      display: ""
      due_date: ""
      escalation: ""
      expected_start: ""
      follow_up: ""
      group_list: ""
      impact: ""
      incident_state: ""
      knowledge: ""
      location: ""
      made_sla: ""
      notify: ""
      number: ""
      order: ""
      parent: ""
      parent_incident: ""
      priority: ""
      problem_id: ""
      reassignment_count: ""
      reopen_count: ""
      resolved_at: ""
      resolved_by: ""
      rfc: ""
      severity: ""
      short_description: Ticket test description
      sla_due: ""
      subcategory: ""
      sys_updated_by: ""
      sys_updated_on: ""
      urgency: ""
      user_input: ""
      watch_list: ""
      work_end: ""
      work_notes: ""
      work_notes_list: ""
      work_start: ""
    view: |-
      {
        "position": {
          "x": 912,
          "y": 1360
        }
      }
  "13":
    id: "13"
    taskid: 206bcc31-ab6a-42ef-87e3-56a78ee2108d
    type: regular
    task:
      id: 206bcc31-ab6a-42ef-87e3-56a78ee2108d
      version: -1
      name: servicenow-incident-create (Moshe, IT)
      description: Create new ServiceNow ticket
      script: ServiceNow|||servicenow-incident-create
      type: regular
      iscommand: true
      brand: ServiceNow
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      active: ""
      activity_due: ""
      additional_assignee_list: ""
      approval: ""
      approval_history: ""
      approval_set: ""
      assigned_to: Dani
      assignment_group: ""
      business_duration: ""
      business_service: ""
      business_stc: ""
      calendar_duration: ""
      caller_id: ""
      category: IT
      caused_by: ""
      close_code: ""
      close_notes: ""
      closed_at: ""
      closed_by: ""
      cmdb_ci: ""
      comments: ""
      comments_and_work_notes: ""
      company: ""
      contact_type: ""
      correlation_display: ""
      correlation_id: ""
      delivery_plan: ""
      description: ""
      display: ""
      due_date: ""
      escalation: ""
      expected_start: ""
      follow_up: ""
      group_list: ""
      impact: ""
      incident_state: ""
      knowledge: ""
      location: ""
      made_sla: ""
      notify: ""
      number: ""
      order: ""
      parent: ""
      parent_incident: ""
      priority: ""
      problem_id: ""
      reassignment_count: ""
      reopen_count: ""
      resolved_at: ""
      resolved_by: ""
      rfc: ""
      severity: ""
      short_description: Ticket test description
      sla_due: ""
      subcategory: ""
      sys_updated_by: ""
      sys_updated_on: ""
      urgency: ""
      user_input: ""
      watch_list: ""
      work_end: ""
      work_notes: ""
      work_notes_list: ""
      work_start: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1360
        }
      }
  "14":
    id: "14"
    taskid: 453eb4d8-456b-401b-8d60-210b4de3570f
    type: regular
    task:
      id: 453eb4d8-456b-401b-8d60-210b4de3570f
      version: -1
      name: servicenow-incident-create (Dani, Monitoring)
      description: Create new ServiceNow ticket
      script: ServiceNow|||servicenow-incident-create
      type: regular
      iscommand: true
      brand: ServiceNow
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      active: ""
      activity_due: ""
      additional_assignee_list: ""
      approval: ""
      approval_history: ""
      approval_set: ""
      assigned_to: Dani
      assignment_group: ""
      business_duration: ""
      business_service: ""
      business_stc: ""
      calendar_duration: ""
      caller_id: ""
      category: IT
      caused_by: ""
      close_code: ""
      close_notes: ""
      closed_at: ""
      closed_by: ""
      cmdb_ci: ""
      comments: ""
      comments_and_work_notes: ""
      company: ""
      contact_type: ""
      correlation_display: ""
      correlation_id: ""
      delivery_plan: ""
      description: ""
      display: ""
      due_date: ""
      escalation: ""
      expected_start: ""
      follow_up: ""
      group_list: ""
      impact: ""
      incident_state: ""
      knowledge: ""
      location: ""
      made_sla: ""
      notify: ""
      number: ""
      order: ""
      parent: ""
      parent_incident: ""
      priority: ""
      problem_id: ""
      reassignment_count: ""
      reopen_count: ""
      resolved_at: ""
      resolved_by: ""
      rfc: ""
      severity: ""
      short_description: Ticket test description
      sla_due: ""
      subcategory: ""
      sys_updated_by: ""
      sys_updated_on: ""
      urgency: ""
      user_input: ""
      watch_list: ""
      work_end: ""
      work_notes: ""
      work_notes_list: ""
      work_start: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1360
        }
      }
  "15":
    id: "15"
    taskid: 2036fb9a-8ff9-4283-85f9-e63963550f0e
    type: title
    task:
      id: 2036fb9a-8ff9-4283-85f9-e63963550f0e
      version: -1
      name: Create two tickets
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
  "16":
    id: "16"
    taskid: d856a968-ec39-434c-8ae3-abd9ee12b11c
    type: title
    task:
      id: d856a968-ec39-434c-8ae3-abd9ee12b11c
      version: -1
      name: Create 4 tickets with two different categories and assignees
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
      - "12"
      - "14"
      - "13"
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1215
        }
      }
  "17":
    id: "17"
    taskid: b19934a1-2b03-40bb-8642-67df50e6afbe
    type: regular
    task:
      id: b19934a1-2b03-40bb-8642-67df50e6afbe
      version: -1
      name: VerifyContextFields (Total of 6 tickets)
      scriptName: VerifyContextFields
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      field1: Ticket.[5].Summary
      field2: Ticket.[5].Assignee
      field3: ""
      field4: ""
      field5: ""
      value1: ""
      value2: ""
      value3: ""
      value4: ""
      value5: ""
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1588
        }
      }
  "18":
    id: "18"
    taskid: 775ed07f-64c0-4001-8290-2235526ae8b2
    type: title
    task:
      id: 775ed07f-64c0-4001-8290-2235526ae8b2
      version: -1
      name: Different queries
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1766
        }
      }
  "19":
    id: "19"
    taskid: 6cd9d8b5-d60f-458e-8642-b8610514bfa5
    type: regular
    task:
      id: 6cd9d8b5-d60f-458e-8642-b8610514bfa5
      version: -1
      name: servicenow-incidents-query
      description: Retrieve info with query
      script: ServiceNow|||servicenow-incidents-query
      type: regular
      iscommand: true
      brand: ServiceNow
    scriptarguments:
      limit: "3"
      sysparm_query: short_description=Ticket test description
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1921
        }
      }
  "20":
    id: "20"
    taskid: d7402ff4-c90c-4f97-89dc-04c83c660514
    type: regular
    task:
      id: d7402ff4-c90c-4f97-89dc-04c83c660514
      version: -1
      name: servicenow-incidents-query
      description: Retrieve info with query
      script: ServiceNow|||servicenow-incidents-query
      type: regular
      iscommand: true
      brand: ServiceNow
    scriptarguments:
      limit: "3"
      sysparm_query: '"short_description=Ticket test description"'
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2104
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2149,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
