id: TestWordFileToIOC
version: -1
name: TestWordFileToIOC
description: Creates a test docx word file, parses it and runs various IOC extraction
  tasks.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 28e96809-a1cc-47f1-87e3-4d94fc38edb7
    type: start
    task:
      id: 28e96809-a1cc-47f1-87e3-4d94fc38edb7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "4":
    id: "4"
    taskid: ae9a5f7d-be1b-43ea-8342-b7c53bd9b5fa
    type: regular
    task:
      id: ae9a5f7d-be1b-43ea-8342-b7c53bd9b5fa
      version: -1
      name: CreateWordTestFile
      description: Downloads a test file to parse
      scriptName: TestCreateWordFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      extend-context: {}
      name:
        simple: test.docx
      text:
        simple: 'These are some IP''s: 127.0.0.1, 127.0.0.8, Awesome!'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "6":
    id: "6"
    taskid: 3bd899e1-5cc8-4fe9-8aa6-4b3a1630dc43
    type: regular
    task:
      id: 3bd899e1-5cc8-4fe9-8aa6-4b3a1630dc43
      version: -1
      name: RunParseWordDoc
      description: Parses word files to text file
      scriptName: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "7":
    id: "7"
    taskid: e80f7ff9-7f64-4587-8dcd-caab127096b4
    type: regular
    task:
      id: e80f7ff9-7f64-4587-8dcd-caab127096b4
      version: -1
      name: ExtractIPsFromFile
      scriptName: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      extend-context: {}
      report: {}
      text:
        simple: ${FileData}
      url: {}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "8":
    id: "8"
    taskid: 820ba247-9ba3-4700-8bc4-feb21ad6f1bc
    type: regular
    task:
      id: 820ba247-9ba3-4700-8bc4-feb21ad6f1bc
      version: -1
      name: ReadFileContentsToContext
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      action: {}
      contextKey: {}
      data: {}
      destpath: {}
      enforce_timeout: {}
      entry: {}
      entryID:
        simple: ${File.[1].EntryID}
      entryId: {}
      entryid: {}
      file: {}
      fileNames: {}
      filename: {}
      hostname: {}
      ip: {}
      issueId: {}
      machine: {}
      max_file_size: {}
      maxFileSize: {}
      memory: {}
      options: {}
      package: {}
      path: {}
      paths: {}
      pathtype: {}
      platform: {}
      profiles: {}
      system: {}
      tags: {}
      timeout: {}
      upload: {}
      verbose: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "9":
    id: "9"
    taskid: c025933f-7b6d-4601-864c-820764bb0356
    type: regular
    task:
      id: c025933f-7b6d-4601-864c-820764bb0356
      version: -1
      name: CheckExtractedIPsExistInContext
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue:
        simple: '["127.0.0.1", "127.0.0.8"]'
      extend-context: {}
      field1: {}
      field2: {}
      field3: {}
      field4: {}
      fields: {}
      path:
        simple: IP.Address
      value:
        simple: ${IP.Address}
      value1: {}
      value2: {}
      value3: {}
      value4: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "10":
    id: "10"
    taskid: 16745cb5-d6f6-4f52-8013-0a7a56166895
    type: regular
    task:
      id: 16745cb5-d6f6-4f52-8013-0a7a56166895
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
