id: IOC Hunt - TIE - Test
version: -1
name: IOC Hunt - TIE - Test
description: A test playbook for "IOC Hunt - TIE"
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 066f0346-5546-4ce7-840d-52444dec212e
    type: start
    task:
      id: 066f0346-5546-4ce7-840d-52444dec212e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 3b86fa59-f5bd-483d-8648-d73cb79c668b
    type: regular
    task:
      id: 3b86fa59-f5bd-483d-8648-d73cb79c668b
      version: -1
      name: DeleteContext
      description: Delete all context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: f0a75cf5-dd71-4864-84aa-9adf93ee2324
    type: regular
    task:
      id: f0a75cf5-dd71-4864-84aa-9adf93ee2324
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      data:
        simple: ' '
      entryId: {}
      filename:
        simple: testFile1.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 8e770017-6125-46a0-8852-9d0e865f85d2
    type: regular
    task:
      id: 8e770017-6125-46a0-8852-9d0e865f85d2
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      data:
        simple: a
      entryId: {}
      filename:
        simple: testFile2.tzt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: 8bfb3388-fd14-4a4a-88fa-f89d917a0a06
    type: playbook
    task:
      id: 8bfb3388-fd14-4a4a-88fa-f89d917a0a06
      version: -1
      name: TIE - IOC Hunt
      playbookId: TIE - IOC Hunt
      description: |-
        Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

        Input:
        * Hash (default, takes all deferent hashes from context)

        Output:
        * All agents that files with "Hash" has been executed on (TIE)
        * Enrich Agents info from ePO
      playbookName: TIE - IOC Hunt
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      Hash:
        simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
          b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 718
        }
      }
  "5":
    id: "5"
    taskid: 9469b3df-6167-4d9b-8eb1-986f993e8fc8
    type: regular
    task:
      id: 9469b3df-6167-4d9b-8eb1-986f993e8fc8
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: File
          filters:
          - - operator: general.isExists
              left:
                value:
                  simple: File.References.AgentGuid
                iscontext: true
          accessor: References
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"