id: RedCanaryTest
version: 6
name: RedCanaryTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 84663d49-6b0a-4045-86ac-b2e95609f379
    type: start
    task:
      id: 84663d49-6b0a-4045-86ac-b2e95609f379
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: e2cdcf98-7063-4f06-83ae-944ec284022e
    type: regular
    task:
      id: e2cdcf98-7063-4f06-83ae-944ec284022e
      version: -1
      name: Start Fresh
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: ac835a47-bbdb-4768-82d2-43f7a36bb37b
    type: regular
    task:
      id: ac835a47-bbdb-4768-82d2-43f7a36bb37b
      version: -1
      name: List Detections
      script: Red Canary|||redcanary-list-detections
      type: regular
      iscommand: true
      brand: Red Canary
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      page:
        simple: "2"
      per-page:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 7b4458cc-e287-457e-8e92-a38f8f29cf6f
    type: condition
    task:
      id: 7b4458cc-e287-457e-8e92-a38f8f29cf6f
      version: -1
      name: Verify Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThanOrEqual
          left:
            value:
              complex:
                root: RedCanary
                accessor: Detection.ID
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 13598001-e00f-47a7-8ee7-d02cd994e12a
    type: regular
    task:
      id: 13598001-e00f-47a7-8ee7-d02cd994e12a
      version: -1
      name: List EndPoints
      script: Red Canary|||redcanary-list-endpoints
      type: regular
      iscommand: true
      brand: Red Canary
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      page: {}
      per-page: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 03692221-f098-4b9e-81b9-9e863663c369
    type: condition
    task:
      id: 03692221-f098-4b9e-81b9-9e863663c369
      version: -1
      name: Verify Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: EndPoint
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
  "6":
    id: "6"
    taskid: c70867f2-73f1-4457-845e-dd371fad09fb
    type: regular
    task:
      id: c70867f2-73f1-4457-845e-dd371fad09fb
      version: -1
      name: Acknowledge detection
      script: Red Canary|||redcanary-acknowledge-detection
      type: regular
      iscommand: true
      brand: Red Canary
    nexttasks:
      '#none#':
      - "7"
      - "9"
    scriptarguments:
      id:
        complex:
          root: RedCanary
          filters:
          - - operator: isNotExists
              left:
                value:
                  simple: RedCanary.Detection.RemediationStatus
                iscontext: true
          accessor: Detection
          transformers:
          - operator: GetFirstObject
          - operator: getField
            args:
              field:
                value:
                  simple: ID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 9eb7f786-2071-403c-8bf0-be4045051405
    type: regular
    task:
      id: 9eb7f786-2071-403c-8bf0-be4045051405
      version: -1
      name: Execute test playbook on detection using ID
      script: Red Canary|||redcanary-execute-playbook
      type: regular
      iscommand: true
      brand: Red Canary
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      detection-id:
        complex:
          root: RedCanary
          accessor: Detection.ID
          transformers:
          - operator: GetFirstObject
      playbook-id:
        simple: "3001"
      playbook-name: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 7ed6c285-f053-4992-8358-6cb042ce70e1
    type: regular
    task:
      id: 7ed6c285-f053-4992-8358-6cb042ce70e1
      version: -1
      name: Remediate detection
      script: Red Canary|||redcanary-remediate-detection
      type: regular
      iscommand: true
      brand: Red Canary
    scriptarguments:
      comment:
        simple: 'demisto testing '
      id:
        complex:
          root: RedCanary
          filters:
          - - operator: isNotExists
              left:
                value:
                  simple: RedCanary.Detection.RemediationStatus
                iscontext: true
          accessor: Detection
          transformers:
          - operator: GetFirstObject
          - operator: getField
            args:
              field:
                value:
                  simple: ID
      remediation-state:
        simple: not_remediated_false_positive
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 478c12ab-7b57-421e-859b-9c3eb2e0b950
    type: regular
    task:
      id: 478c12ab-7b57-421e-859b-9c3eb2e0b950
      version: -1
      name: Execute test playbook on detection using name
      script: Red Canary|||redcanary-execute-playbook
      type: regular
      iscommand: true
      brand: Red Canary
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      detection-id:
        complex:
          root: RedCanary
          accessor: Detection.ID
          transformers:
          - operator: GetFirstObject
      playbook-id: {}
      playbook-name:
        simple: TestPlaybook
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1465,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
