id: endpoint_enrichment_-_generic_test
version: -1
name: Endpoint Enrichment - Generic Test
description: ""
fromversion: "3.5.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 06f33f0f-43b8-4260-862c-c700fe7278dd
    type: start
    task:
      id: 06f33f0f-43b8-4260-862c-c700fe7278dd
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "4":
    id: "4"
    taskid: b0904425-5a15-4511-8cf6-762d02e244c1
    type: playbook
    task:
      id: b0904425-5a15-4511-8cf6-762d02e244c1
      version: -1
      name: Endpoint Enrichment - Generic
      description: Enrich an Endpoint Hostname using one or more integrations
      playbookName: Endpoint Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      Hostname:
        simple: ${Endpoint.Hostname}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    id: "5"
    taskid: fc2ab457-693b-4673-887d-9eb89583eb94
    type: regular
    task:
      id: fc2ab457-693b-4673-887d-9eb89583eb94
      version: -1
      name: Verify context endpoint key
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
      description: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Hostname,Mac,IP,OS
      path:
        simple: ${Endpoint}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    id: "6"
    taskid: 6d21f234-ad71-4c57-822a-8278ebabe962
    type: regular
    task:
      id: 6d21f234-ad71-4c57-822a-8278ebabe962
      version: -1
      name: Delete context (all)
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "7":
    id: "7"
    taskid: 70e0c51c-f979-47c9-8d1b-638c4cf6717e
    type: regular
    task:
      id: 70e0c51c-f979-47c9-8d1b-638c4cf6717e
      version: -1
      name: 'add hostname #1'
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint.Hostname
      value:
        simple: AMAZON-39D8D1E7
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "8":
    id: "8"
    taskid: 63f6ec04-9335-4c37-88a9-eec0010a724c
    type: regular
    task:
      id: 63f6ec04-9335-4c37-88a9-eec0010a724c
      version: -1
      name: 'add hostname #2'
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint.Hostname
      value:
        simple: acAir2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
