id: Hunt for bad IOCs - Test
version: -1
name: Hunt for bad IOCs - Test
fromversion: 3.5.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dee39df6-13a5-478c-896a-10346bd28cb3
    type: start
    task:
      id: dee39df6-13a5-478c-896a-10346bd28cb3
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: dd50fb3b-b6fe-4f9a-8d7a-0f2bdb8351fb
    type: regular
    task:
      id: dd50fb3b-b6fe-4f9a-8d7a-0f2bdb8351fb
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 83395f0b-e00d-4163-8363-f74627b9e64f
    type: playbook
    task:
      id: 83395f0b-e00d-4163-8363-f74627b9e64f
      version: -1
      name: Hunt for bad IOCs
      description: Assume that malicious IOCs are in the right place in the context
        and start hunting using available tools
      playbookName: Hunt for bad IOCs
      playbookId: Hunt for bad IOCs
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      MD5Hash:
        complex:
          root: MD5Hashes
      SHA1Hash:
        complex:
          root: SHA1Hashes
      SHA256Hash:
        complex:
          root: SHA256Hashes
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "3":
    id: "3"
    taskid: 414dc5dc-bcdd-4b0b-8605-8e09028122ed
    type: title
    task:
      id: 414dc5dc-bcdd-4b0b-8605-8e09028122ed
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
  "4":
    id: "4"
    taskid: e1af6de9-3698-4e3b-8ceb-8d901a1f42b0
    type: regular
    task:
      id: e1af6de9-3698-4e3b-8ceb-8d901a1f42b0
      version: -1
      name: VerifyContext - Falcon Host Devices
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: FalconHostDevices
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "5":
    id: "5"
    taskid: 3e2c67c9-6838-4e2b-8f80-89a3c0987941
    type: regular
    task:
      id: 3e2c67c9-6838-4e2b-8f80-89a3c0987941
      version: -1
      name: VerifyContext - Found File Locations
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: found_file_locations
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "6":
    id: "6"
    taskid: 4e087e30-035d-4f81-8074-302e2f865596
    type: regular
    task:
      id: 4e087e30-035d-4f81-8074-302e2f865596
      version: -1
      name: VerifyContext - Found Hashes
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: found_hashes
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "7":
    id: "7"
    taskid: 794eac9a-79f5-423b-8984-e27bc38e3ed0
    type: regular
    task:
      id: 794eac9a-79f5-423b-8984-e27bc38e3ed0
      version: -1
      name: VerifyContext - Agent Guids
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: File.References.AgentGuid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "8":
    id: "8"
    taskid: 13f70d86-c111-4f71-82e6-f9af5e83e1d7
    type: regular
    task:
      id: 13f70d86-c111-4f71-82e6-f9af5e83e1d7
      version: -1
      name: Set test MD5 Hashes
      description: Set test MD5 Hashes
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      append: {}
      key:
        simple: MD5Hashes
      value:
        simple: '["0cc175b9c0f1b6a831c399e269772661", "36bd4be7042f6de7e332c05cef287d05",
          "df9d0ca7409a2967bb338014b043a062", "05ED91DAA77FF31F7F4E61314C2A3122"]'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    id: "9"
    taskid: 6a8b052d-d681-44c4-8a4d-0bd710eead49
    type: regular
    task:
      id: 6a8b052d-d681-44c4-8a4d-0bd710eead49
      version: -1
      name: Set test SHA1 Hashes
      description: Set test SHA1 Hashes
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      append: {}
      key:
        simple: SHA1Hashes
      value:
        simple: '["2fb8b65be05606697e019391d99e28c79c946725"]'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "10":
    id: "10"
    taskid: bf02c0ae-1980-4750-8d53-7b5b3ce27a24
    type: regular
    task:
      id: bf02c0ae-1980-4750-8d53-7b5b3ce27a24
      version: -1
      name: Set test SHA256 Hashes
      description: Set test SHA256 Hashes
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append: {}
      key:
        simple: SHA256Hashes
      value:
        simple: '["56cdfe418592b3fd68cea60da9689fb51a9bd90409b747d02fa08ed90db81e37"]'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"