id: account_enrichment_-_generic_test
version: -1
name: Account Enrichment - Generic Test
description: ""
fromversion: "3.5.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bd1b0003-1e61-4474-86cf-5144c2382d78
    type: start
    task:
      id: bd1b0003-1e61-4474-86cf-5144c2382d78
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 4886f584-4a72-4f75-8ea0-879715f325d3
    type: playbook
    task:
      id: 4886f584-4a72-4f75-8ea0-879715f325d3
      version: -1
      name: Account Enrichment - Generic
      description: Enrich Accounts using one or more integrations
      playbookName: Account Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Username:
        simple: ${ExampleAccount.Username}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 723
        }
      }
  "3":
    id: "3"
    taskid: 5fcabfc8-e07f-4d0d-8df3-162085f4bad8
    type: regular
    task:
      id: 5fcabfc8-e07f-4d0d-8df3-162085f4bad8
      version: -1
      name: Verify account fields
      description: '-'
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: DisplayName, Username, Type, Manager, Groups
      path:
        simple: ${Account}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "4":
    id: "4"
    taskid: a06cf79a-9ceb-4845-833e-a3a5f4d14488
    type: regular
    task:
      id: a06cf79a-9ceb-4845-833e-a3a5f4d14488
      version: -1
      name: Delete context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    id: "5"
    taskid: 8f908d05-411f-4ecb-8265-ddbe39a32fca
    type: regular
    task:
      id: 8f908d05-411f-4ecb-8265-ddbe39a32fca
      version: -1
      name: 'add username #1'
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: ExampleAccount.Username
      value:
        simple: admin
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "6":
    id: "6"
    taskid: 03bca718-5632-4188-8573-8ddf251db5d3
    type: regular
    task:
      id: 03bca718-5632-4188-8573-8ddf251db5d3
      version: -1
      name: 'add username #2'
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: ExampleAccount.Username
      value:
        simple: administrator
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
