id: Test Playbook TrendMicroDDA
version: -1
name: Test Playbook TrendMicroDDA
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cac5e409-9f5f-4ee1-8f36-70819f33b627
    type: start
    task:
      id: cac5e409-9f5f-4ee1-8f36-70819f33b627
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": -50
        }
      }
  "1":
    id: "1"
    taskid: b8460130-c568-48d2-87fd-0d2673317b45
    type: regular
    task:
      id: b8460130-c568-48d2-87fd-0d2673317b45
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
      keysToKeep: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 240
        }
      }
  "2":
    id: "2"
    taskid: 12f16010-adf2-42f7-8990-f92c01ce2e71
    type: regular
    task:
      id: 12f16010-adf2-42f7-8990-f92c01ce2e71
      version: -1
      name: upload-url
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-upload-url
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      url:
        simple: https://www.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 478,
          "y": 455
        }
      }
  "3":
    id: "3"
    taskid: b7dd2ef4-9623-43f7-86f0-681a28fb56f4
    type: condition
    task:
      id: b7dd2ef4-9623-43f7-86f0-681a28fb56f4
      version: -1
      name: upload-sample-url AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    scriptarguments:
      left:
        simple: ${TrendMicroDDA.Submissions.SHA1}
      right:
        simple: BCF5132CDC4F74112868C2AEFF9740B5034873D2
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 680
        }
      }
  "6":
    id: "6"
    taskid: 2808fbbd-fc41-4749-8a70-f48dfc7b1f0f
    type: regular
    task:
      id: 2808fbbd-fc41-4749-8a70-f48dfc7b1f0f
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 968
        }
      }
  "7":
    id: "7"
    taskid: 8b36c63d-a8cb-4ca8-890f-5066923c015b
    type: regular
    task:
      id: 8b36c63d-a8cb-4ca8-890f-5066923c015b
      version: -1
      name: check-status after sleep
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-check-status
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      sha1:
        simple: ${TrendMicroDDA.Submissions.SHA1}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 1198
        }
      }
  "8":
    id: "8"
    taskid: 420c902f-012a-4b49-8681-72f1ee35802c
    type: condition
    task:
      id: 420c902f-012a-4b49-8681-72f1ee35802c
      version: -1
      name: check-status after sleep AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    scriptarguments:
      left:
        simple: ${TrendMicroDDA.Submissions.status}
      right:
        simple: Completed
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 1454
        }
      }
  "9":
    id: "9"
    taskid: 2dd842be-42ad-4cb4-8d5f-ddf2abc2b916
    type: regular
    task:
      id: 2dd842be-42ad-4cb4-8d5f-ddf2abc2b916
      version: -1
      name: get-report
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-report
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      sha1:
        simple: ${TrendMicroDDA.Submissions.SHA1}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 1735
        }
      }
  "10":
    id: "10"
    taskid: 88f590a6-f781-4c03-816b-1fa0e232e14c
    type: condition
    task:
      id: 88f590a6-f781-4c03-816b-1fa0e232e14c
      version: -1
      name: get-report AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    scriptarguments:
      left:
        simple: ${TrendMicroDDA.Submissions.RiskLevel}
      right:
        simple: "0"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 1915
        }
      }
  "11":
    id: "11"
    taskid: b536bfcb-65c4-41ea-80ae-f0266b3ec006
    type: regular
    task:
      id: b536bfcb-65c4-41ea-80ae-f0266b3ec006
      version: -1
      name: get-sample-list
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-sample-list
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      interval_end:
        simple: 2008-11-22 19:53:59
      interval_start:
        simple: 2008-11-22 19:53:42
      interval_type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 2095
        }
      }
  "12":
    id: "12"
    taskid: f83a1490-70bb-4ec9-8bf2-93096b23cd3b
    type: regular
    task:
      id: f83a1490-70bb-4ec9-8bf2-93096b23cd3b
      version: -1
      name: FileCreateAndUpload
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      data:
        simple: qwerty6
      entryId: {}
      filename:
        simple: test_file.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 2275
        }
      }
  "13":
    id: "13"
    taskid: 095f832b-71bf-498e-82bd-ac606fcc27d3
    type: regular
    task:
      id: 095f832b-71bf-498e-82bd-ac606fcc27d3
      version: -1
      name: upload-file
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-upload-file
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      EntryID:
        simple: ${File.EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 2455
        }
      }
  "14":
    id: "14"
    taskid: b6d62f62-dfb7-44b2-8e09-90095e392338
    type: condition
    task:
      id: b6d62f62-dfb7-44b2-8e09-90095e392338
      version: -1
      name: get-report2 AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    scriptarguments:
      left:
        complex:
          root: TrendMicroDDA
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: TrendMicroDDA.Submissions.SHA1
                iscontext: true
              right:
                value:
                  simple: 571AD0F7D5056F68D0F2B795EAF4618C082A89D9
          accessor: Submissions.RiskLevel
      right:
        simple: "0"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 2850
        }
      }
  "15":
    id: "15"
    taskid: 24fb8a00-13d8-49b0-8a47-03ab84a862b7
    type: regular
    task:
      id: 24fb8a00-13d8-49b0-8a47-03ab84a862b7
      version: -1
      name: get-sample
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-sample
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      encrypted: {}
      filename: {}
      sample_sha1:
        simple: 571AD0F7D5056F68D0F2B795EAF4618C082A89D9
      type: {}
      type_origin: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 478,
          "y": 3076
        }
      }
  "16":
    id: "16"
    taskid: c5382a0a-70ba-46ba-8ea1-cee235e5ff55
    type: regular
    task:
      id: c5382a0a-70ba-46ba-8ea1-cee235e5ff55
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
      keysToKeep: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 3275
        }
      }
  "17":
    id: "17"
    taskid: 0f31cae0-ecc0-4009-8938-a65d9caf1192
    type: title
    task:
      id: 0f31cae0-ecc0-4009-8938-a65d9caf1192
      version: -1
      name: Test Playbook TrendMicroADD
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 80
        }
      }
  "18":
    id: "18"
    taskid: 6b323d98-d937-45c3-8eb3-975db9f29e01
    type: title
    task:
      id: 6b323d98-d937-45c3-8eb3-975db9f29e01
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 3452
        }
      }
  "19":
    id: "19"
    taskid: daaedb7b-e604-4b15-86d0-553c5570e9a5
    type: regular
    task:
      id: daaedb7b-e604-4b15-86d0-553c5570e9a5
      version: -1
      name: get-report2
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-report
      type: regular
      iscommand: true
      brand: Trend Micro Deep Discovery Analyzer
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      sha1:
        simple: 571ad0f7d5056f68d0f2b795eaf4618c082a89d9
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 476,
          "y": 2658
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3567,
        "width": 382,
        "x": 476,
        "y": -50
      }
    }
  }
inputs: []
outputs: []
