id: IOC Hunt - TIE - Test
version: -1
name: IOC Hunt - TIE - Test
description: A test playbook for "IOC Hunt - TIE"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5445cceb-f26f-4cf3-8eb1-3fbb234f3acd
    type: start
    task:
      id: 5445cceb-f26f-4cf3-8eb1-3fbb234f3acd
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: d0b09e9e-88e3-4dad-8237-91e9324e00cf
    type: regular
    task:
      id: d0b09e9e-88e3-4dad-8237-91e9324e00cf
      version: -1
      name: Clear context
      description: Clear the context before starting
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 9a16ec30-2598-4507-81a4-f5336f4aa382
    type: regular
    task:
      id: 9a16ec30-2598-4507-81a4-f5336f4aa382
      version: -1
      name: Create testFile1
      description: Create a file with a known hash
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      data:
        simple: ' '
      entryId: {}
      filename:
        simple: testFile1.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -160,
          "y": 371
        }
      }
  "4":
    id: "4"
    taskid: 31360047-8ddf-4063-83b3-ebd9a692a28b
    type: regular
    task:
      id: 31360047-8ddf-4063-83b3-ebd9a692a28b
      version: -1
      name: Create testFile2
      description: Create another file with a known hash
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      data:
        simple: a
      entryId: {}
      filename:
        simple: testFile2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 259,
          "y": 371
        }
      }
  "7":
    id: "7"
    taskid: 06f79862-24f5-46e0-88d2-fb180ed2172d
    type: regular
    task:
      id: 06f79862-24f5-46e0-88d2-fb180ed2172d
      version: -1
      name: Verify AgentGuid
      description: Verify AgentGuid exists
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: File
          filters:
          - - operator: general.isExists
              left:
                value:
                  simple: References
                iscontext: true
          - - operator: general.isNotEmpty
              left:
                value:
                  simple: References.AgentGuid
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 729
        }
      }
  "8":
    id: "8"
    taskid: 0205d5e7-bc56-489b-8dfb-f25982a7a395
    type: condition
    task:
      id: 0205d5e7-bc56-489b-8dfb-f25982a7a395
      version: -1
      name: Is hostname found?
      description: Did epo returned a hostname?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "11"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: Endpoint
          accessor: Hostname
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 908
        }
      }
  "9":
    id: "9"
    taskid: 8be08976-e2fc-45a3-8ce4-8675887c7d9c
    type: playbook
    task:
      id: 8be08976-e2fc-45a3-8ce4-8675887c7d9c
      version: -1
      name: IOC Hunt - TIE
      description: |-
        Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

        Input:
        * Hash (default, takes all deferent hashes from context)

        Output:
        * All agents that files with "Hash" has been executed on (TIE)
        * Enrich Agents info from ePO
      playbookName: IOC Hunt - TIE
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      Hash:
        simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
          b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 561
        }
      }
  "10":
    id: "10"
    taskid: 978786d7-2c20-417d-8290-654e1d26e2e0
    type: title
    task:
      id: 978786d7-2c20-417d-8290-654e1d26e2e0
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1708
        }
      }
  "11":
    id: "11"
    taskid: eafa44ec-f9d1-4cd6-8920-8cc3295a0ec8
    type: regular
    task:
      id: eafa44ec-f9d1-4cd6-8920-8cc3295a0ec8
      version: -1
      name: Verify Hostname
      description: Verify hostnames are hot empty
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: Endpoint
          filters:
          - - operator: general.isExists
              left:
                value:
                  simple: Hostname
                iscontext: true
          - - operator: general.isNotEmpty
              left:
                value:
                  simple: Hostname
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1525
        }
      }
  "12":
    id: "12"
    taskid: 98efd474-f5a5-4b1a-83d2-96602a1a60ae
    type: regular
    task:
      id: 98efd474-f5a5-4b1a-83d2-96602a1a60ae
      version: -1
      name: Add a fake hostname
      description: Create a fake hostname for the test
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      append: {}
      key:
        simple: Endpoint
      value:
        simple: '{ "Hostname": "someHostname1" }'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -225,
          "y": 1118
        }
      }
  "13":
    id: "13"
    taskid: d43c695c-d4a2-43c6-818b-ad5d2974435d
    type: regular
    task:
      id: d43c695c-d4a2-43c6-818b-ad5d2974435d
      version: -1
      name: Add another fake hostname
      description: Create another fake hostname for the test
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint
      value:
        simple: '{ "Hostname": "someHostname2" }'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -225,
          "y": 1286
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1723,
        "width": 864,
        "x": -225,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
