id: Splunk-Test
version: -1
name: Splunk-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e8d1a9d6-027c-4043-8d29-2781fa9a25d5
    type: start
    task:
      id: e8d1a9d6-027c-4043-8d29-2781fa9a25d5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 6d673a2c-c2c3-4ff8-803b-d2419a83f916
    type: regular
    task:
      id: 6d673a2c-c2c3-4ff8-803b-d2419a83f916
      version: -1
      name: splunk-search
      description: Search Splunk for events
      script: SplunkPy|||splunk-search
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      earliest_time:
        simple: -1000d
      event_limit: {}
      latest_time: {}
      query:
        simple: '* | head 3'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 4d00e0d9-c3de-41c9-8964-5ada56ebe449
    type: regular
    task:
      id: 4d00e0d9-c3de-41c9-8964-5ada56ebe449
      version: -1
      name: Verify Context result of Splunk Search
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: ${Splunk.Result}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 57ff69a7-377a-4307-8fd2-99c523c28deb
    type: regular
    task:
      id: 57ff69a7-377a-4307-8fd2-99c523c28deb
      version: -1
      name: Get indexes names
      script: SplunkPy|||splunk-get-indexes
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      extend-context:
        simple: indexes=
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: 8620f3ed-26ee-41d5-8e31-972e998537cc
    type: condition
    task:
      id: 8620f3ed-26ee-41d5-8e31-972e998537cc
      version: -1
      name: Has main index
      scriptName: StringContains
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "5"
    scriptarguments:
      left: {}
      right: {}
      string:
        simple: ${JsonStr}
      substring:
        simple: main
      substringSeperator: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "5":
    id: "5"
    taskid: e77650cb-56ce-4529-8260-4c57a8ce3b94
    type: regular
    task:
      id: e77650cb-56ce-4529-8260-4c57a8ce3b94
      version: -1
      name: Create new Splunk event
      script: SplunkPy|||splunk-submit-event
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      data:
        simple: test
      host:
        simple: localhost
      index:
        simple: main
      sourcetype:
        simple: demisto-ci
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "6":
    id: "6"
    taskid: 97c66fb9-18ac-4e68-8a06-b48579f1e3e9
    type: regular
    task:
      id: 97c66fb9-18ac-4e68-8a06-b48579f1e3e9
      version: -1
      name: DumpJSON
      description: Dumps a json from context key input, and returns a json object
        string result
      scriptName: DumpJSON
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      extend-context: {}
      key:
        simple: indexes
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "7":
    id: "7"
    taskid: 6d7873fd-79d7-4d63-880f-059466574d29
    type: regular
    task:
      id: 6d7873fd-79d7-4d63-880f-059466574d29
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "8":
    id: "8"
    taskid: f49679c7-4f5e-4582-8324-94c4ea1e18fb
    type: regular
    task:
      id: f49679c7-4f5e-4582-8324-94c4ea1e18fb
      version: -1
      name: Test eventcount query
      script: SplunkPy|||splunk-search
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      earliest_time: {}
      event_limit: {}
      extend-context:
        simple: eventcount=
      latest_time: {}
      query:
        simple: '| eventcount'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "9":
    id: "9"
    taskid: 0daa1ba8-5d92-4f42-8897-96a4ab8e1602
    type: condition
    task:
      id: 0daa1ba8-5d92-4f42-8897-96a4ab8e1602
      version: -1
      name: Verify eventcount
      scriptName: IsGreaterThan
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "11"
      "yes":
      - "12"
    scriptarguments:
      first:
        simple: ${eventcount.[0].count}
      second:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "10":
    id: "10"
    taskid: aa5182a1-d082-4f40-8fdf-89701ee9d857
    type: regular
    task:
      id: aa5182a1-d082-4f40-8fdf-89701ee9d857
      version: -1
      name: Hurry!
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Hurry!
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 21,
          "y": 2228
        }
      }
  "11":
    id: "11"
    taskid: 45be7519-b926-4e6e-8a6a-a0fcfbc67feb
    type: regular
    task:
      id: 45be7519-b926-4e6e-8a6a-a0fcfbc67feb
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
  "12":
    id: "12"
    taskid: 48213731-f2f6-4977-80f6-3a6ade499613
    type: title
    task:
      id: 48213731-f2f6-4977-80f6-3a6ade499613
      version: -1
      name: Test _raw parsing
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 21,
          "y": 1655
        }
      }
  "13":
    id: "13"
    taskid: 1447c7b2-1cd0-4292-83c6-2aeca4bcee7d
    type: regular
    task:
      id: 1447c7b2-1cd0-4292-83c6-2aeca4bcee7d
      version: -1
      name: Parse Raw
      script: SplunkPy|||splunk-parse-raw
      type: regular
      iscommand: true
      brand: SplunkPy_copy_raw
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      raw: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 24,
          "y": 1819
        }
      }
  "14":
    id: "14"
    taskid: 25d906c9-d47d-41f2-842f-9771fda890e4
    type: regular
    task:
      id: 25d906c9-d47d-41f2-842f-9771fda890e4
      version: -1
      name: Verify parse get's to context
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Splunk.Raw.Parsed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 21,
          "y": 2020
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2273,
        "width": 1054,
        "x": 21,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
