id: IOC Hunt - TIE - Test
version: -1
name: IOC Hunt - TIE - Test
description: A test playbook for "IOC Hunt - TIE"
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 066f0346-5546-4ce7-840d-52444dec212e
    type: start
    task:
      id: 066f0346-5546-4ce7-840d-52444dec212e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 3b86fa59-f5bd-483d-8648-d73cb79c668b
    type: regular
    task:
      id: 3b86fa59-f5bd-483d-8648-d73cb79c668b
      version: -1
      name: DeleteContext
      description: Delete all context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    id: "5"
    taskid: e4aa1f5f-32be-4359-803c-3eaf099ace04
    type: regular
    task:
      id: e4aa1f5f-32be-4359-803c-3eaf099ace04
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: File.References.AgentGuid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    id: "6"
    taskid: 3b19c594-3647-4f9d-8f85-a157dd54ed4d
    type: regular
    task:
      id: 3b19c594-3647-4f9d-8f85-a157dd54ed4d
      version: -1
      name: Create hashes for test
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append: {}
      key:
        simple: Hashes
      value:
        simple: '["0cc175b9c0f1b6a831c399e269772661", "7215ee9c7d9dc229d2921a40e899ec5f"]'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "7":
    id: "7"
    taskid: 296d1092-4e4d-4af5-8680-f123f22abab1
    type: playbook
    task:
      id: 296d1092-4e4d-4af5-8680-f123f22abab1
      version: -1
      name: TIE - IOC Hunt
      playbookId: TIE - IOC Hunt
      description: |-
        Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

        Input:
        * Hash (default, takes all deferent hashes from context)

        Output:
        * All agents that files with "Hash" has been executed on (TIE)
        * Enrich Agents info from ePO
      playbookName: TIE - IOC Hunt
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      Hash:
        complex:
          root: Hashes
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"