id: Get File Endpoint History - Generic - Test
version: -1
name: Get File Endpoint History - Generic - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dee39df6-13a5-478c-896a-10346bd28cb3
    type: start
    task:
      id: dee39df6-13a5-478c-896a-10346bd28cb3
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: dd50fb3b-b6fe-4f9a-8d7a-0f2bdb8351fb
    type: regular
    task:
      id: dd50fb3b-b6fe-4f9a-8d7a-0f2bdb8351fb
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: eaf80db4-bab9-499c-8ac8-80f47b43693f
    type: playbook
    task:
      id: eaf80db4-bab9-499c-8ac8-80f47b43693f
      version: -1
      name: Hunt for bad IOCs_copy
      description: Assume that malicious IOCs are in the right place in the context
        and start hunting using available tools
      playbookName: Get File Endpoint History - Generic
      playbookId: Hunt for bad IOCs
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      MD5Hash:
        simple: '[\"0cc175b9c0f1b6a831c399e269772661\", \"36bd4be7042f6de7e332c05cef287d05\",
          \"df9d0ca7409a2967bb338014b043a062\", \"05ED91DAA77FF31F7F4E61314C2A3122\"]'
      SHA1Hash:
        simple: '[\"2fb8b65be05606697e019391d99e28c79c946725\"]'
      SHA256Hash:
        simple: '[\"56cdfe418592b3fd68cea60da9689fb51a9bd90409b747d02fa08ed90db81e37\"]'
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 414dc5dc-bcdd-4b0b-8605-8e09028122ed
    type: title
    task:
      id: 414dc5dc-bcdd-4b0b-8605-8e09028122ed
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "4":
    id: "4"
    taskid: ef7538c3-efde-443f-8b3d-53903eba202e
    type: regular
    task:
      id: ef7538c3-efde-443f-8b3d-53903eba202e
      version: -1
      name: VerifyContext - Falcon Host Devices
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: FalconHostDevices
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    id: "5"
    taskid: eeb842b5-5d39-4383-8485-f4009e048b7f
    type: regular
    task:
      id: eeb842b5-5d39-4383-8485-f4009e048b7f
      version: -1
      name: VerifyContext - Found File Locations
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: found_file_locations
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    id: "6"
    taskid: 4e984156-7368-4aac-8490-79134e96db60
    type: regular
    task:
      id: 4e984156-7368-4aac-8490-79134e96db60
      version: -1
      name: VerifyContext - Found Hashes
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: found_hashes
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    id: "7"
    taskid: 87ec56e1-fe54-480c-8b01-c02b5bf7a258
    type: regular
    task:
      id: 87ec56e1-fe54-480c-8b01-c02b5bf7a258
      version: -1
      name: VerifyContext - Agent Guids
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: File
          accessor: References.AgentGuid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"