id: domain_enrichment_generic_test
version: -1
fromversion: "3.5.0"
name: Domain Enrichment Generic - Test
description: Domain Enrichment Generic test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4cda480e-8fe1-4795-8b8f-e78ee8e84375
    type: start
    task:
      id: 4cda480e-8fe1-4795-8b8f-e78ee8e84375
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
      id: "1"
      taskid: 391e1cac-f7b0-4511-808d-2b3169996721
      type: playbook
      task:
        id: 391e1cac-f7b0-4511-808d-2b3169996721
        version: -1
        name: Domain Enrichment - Generic
        description: Enrich Domain using one or more integrations
        playbookName: Domain Enrichment - Generic
        type: playbook
        iscommand: false
        brand: ""
      nexttasks:
        '#none#':
        - "2"
      scriptarguments:
        Domain:
          simple: ${Test.Domain}
      separatecontext: false
      loop:
        iscommand: false
        exitCondition: ""
        wait: 1
      view: |-
        {
          "position": {
            "x": 447,
            "y": 613
          }
        }
    "2":
      id: "2"
      taskid: e3732a7a-3ea1-4bda-8044-1f0322a46797
      type: regular
      task:
        id: e3732a7a-3ea1-4bda-8044-1f0322a46797
        version: -1
        name: Verify Domain
        description: verify that the context contains the domain name
        scriptName: VerifyContext
        type: regular
        iscommand: false
        brand: ""
      nexttasks:
        '#none#':
        - "3"
      scriptarguments:
        expectedValue: {}
        fields:
          simple: Name
        path:
          simple: ${Domain}
      separatecontext: false
      view: |-
        {
          "position": {
            "x": 450,
            "y": 799
          }
        }
    "3":
      id: "3"
      taskid: 38790b1c-aa86-4fc3-87e6-35b9b79e415d
      type: regular
      task:
        id: 38790b1c-aa86-4fc3-87e6-35b9b79e415d
        version: -1
        name: Verify DBotScore
        description: verify that the context contains the DBotScore
        scriptName: VerifyContext
        type: regular
        iscommand: false
        brand: ""
      nexttasks:
        '#none#':
        - "6"
      scriptarguments:
        expectedValue: {}
        fields:
          simple: Indicator, Vendor, Type, Score
        path:
          simple: ${DBotScore}
      separatecontext: false
      view: |-
        {
          "position": {
            "x": 450,
            "y": 1014
          }
        }
    "4":
      id: "4"
      taskid: a576bf16-3652-448b-80b9-790bb3045658
      type: regular
      task:
        id: a576bf16-3652-448b-80b9-790bb3045658
        version: -1
        name: Clear Context
        description: Clear the context
        scriptName: DeleteContext
        type: regular
        iscommand: false
        brand: ""
      nexttasks:
        '#none#':
        - "5"
      scriptarguments:
        all:
          simple: "yes"
        key: {}
      separatecontext: false
      view: |-
        {
          "position": {
            "x": 450,
            "y": 227
          }
        }
    "5":
      id: "5"
      taskid: 23212201-4dce-46cb-8f57-21ce44c0efb2
      type: regular
      task:
        id: 23212201-4dce-46cb-8f57-21ce44c0efb2
        version: -1
        name: Set domains
        description: Sets a value into the context with the given context key
        scriptName: Set
        type: regular
        iscommand: false
        brand: ""
      nexttasks:
        '#none#':
        - "1"
      scriptarguments:
        append: {}
        key:
          simple: Test.Domain
        value:
          simple: '["demisto.com", "github.com"]'
      separatecontext: false
      view: |-
        {
          "position": {
            "x": 450,
            "y": 423
          }
        }
    "6":
      id: "6"
      taskid: 384ca74e-9588-42c2-8bd6-57d7f2598b1b
      type: regular
      task:
        id: 384ca74e-9588-42c2-8bd6-57d7f2598b1b
        version: -1
        name: Verify DBotScore content
        description: Verify that the DBotScore contains both domains
        scriptName: VerifyContext
        type: regular
        iscommand: false
        brand: ""
      scriptarguments:
        expectedValue: {}
        fields:
          simple: '"demisto.com,github.com"'
        path:
          simple: ${DBotScore.Indicator}
      separatecontext: false
      view: |-
        {
          "position": {
            "x": 450,
            "y": 1212
          }
        }
  view: |-
    {
      "linkLabelsPosition": {},
      "paper": {
        "dimensions": {
          "height": 1257,
          "width": 383,
          "x": 447,
          "y": 50
        }
      }
    }
  inputs: []
  outputs: []
