id: PostgreSQL Test
version: -1
name: PostgreSQL Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0f69103c-5b7e-4bdc-83d2-ba197765e604
    type: start
    task:
      id: 0f69103c-5b7e-4bdc-83d2-ba197765e604
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 5da971b1-3b83-4e5a-8943-015606810d4e
    type: regular
    task:
      id: 5da971b1-3b83-4e5a-8943-015606810d4e
      version: -1
      name: Run a PostgreSQL Query
      script: PostgreSQL|||pgsql-query
      type: regular
      iscommand: true
      brand: PostgreSQL
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context: pgSqlStatus=val
      query: select 'ALLGOOD' as val
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    taskid: 2b4241ed-168c-4380-8f1f-0686b9cb7064
    type: condition
    task:
      id: 2b4241ed-168c-4380-8f1f-0686b9cb7064
      version: -1
      name: Check if query returned ALLGOOD
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "4"
      "yes":
      - "3"
    scriptarguments:
      value: ${pgSqlStatus(val='ALLGOOD')}
    view: |-
      {
        "position": {
          "x": 450,
          "y": 411
        }
      }
  "3":
    id: "3"
    taskid: 547453ee-169c-4df6-8d33-dd283953ae61
    type: regular
    task:
      id: 547453ee-169c-4df6-8d33-dd283953ae61
      version: -1
      name: All good. Closing investigation
      scriptName: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: ""
      reason: ""
    view: |-
      {
        "position": {
          "x": 682,
          "y": 583
        }
      }
  "4":
    id: "4"
    taskid: 6f197467-630e-4c1a-8e5c-1424f257019f
    type: regular
    task:
      id: 6f197467-630e-4c1a-8e5c-1424f257019f
      version: -1
      name: Did not get expected value. Pending analysis
      type: regular
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 249,
          "y": 583
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 628,
        "width": 813,
        "x": 249,
        "y": 50
      }
    }
  }
inputs: []
