id: Lastline - testplaybook
version: -1
name: Lastline - testplaybook
description: Test PB for Lastline integration
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bc3e91c1-6ec9-41bd-80d5-35ee8a8dfd14
    type: start
    task:
      id: bc3e91c1-6ec9-41bd-80d5-35ee8a8dfd14
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: cac54e8e-f080-47e3-8420-77b30780666e
    type: playbook
    task:
      id: cac54e8e-f080-47e3-8420-77b30780666e
      version: -1
      name: Detonate File - Lastline
      playbookName: Detonate File - Lastline
      type: playbook
      iscommand: false
      brand: ""
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
  "2":
    id: "2"
    taskid: cbe8eaba-7a1b-475f-8655-89a4f27d7036
    type: playbook
    task:
      id: cbe8eaba-7a1b-475f-8655-89a4f27d7036
      version: -1
      name: Detonate URL - Lastline
      playbookName: Detonate URL - Lastline
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      Interval:
        simple: "1"
      Timeout:
        simple: "15"
      URL:
        complex:
          root: URL
          accessor: Data
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 97ca3269-4743-425c-8bd6-23a3759974d3
    type: regular
    task:
      id: 97ca3269-4743-425c-8bd6-23a3759974d3
      version: -1
      name: Set
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append: {}
      key:
        simple: URL.Data
      value:
        simple: https://www.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 85326279-047b-405a-8c05-ebf06bf93e78
    type: regular
    task:
      id: 85326279-047b-405a-8c05-ebf06bf93e78
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      data:
        simple: How I need a drink, alcoholic in nature, after the heavy coding, involving  design
          patterns.
      entryId: {}
      filename:
        simple: test_file_lastline
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []