id: CarbonBlackLiveResponseTest
version: -1
name: Carbon Black Live Response Test
description: Tests carbon black enterprise response selected use cases and commands
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c2ed899a-e668-4614-806b-269335660c46
    type: start
    task:
      id: c2ed899a-e668-4614-806b-269335660c46
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "39"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "29":
    id: "29"
    taskid: 2b1e0b46-2dd3-4fb4-866e-c45aaf8eb4a2
    type: regular
    task:
      id: 2b1e0b46-2dd3-4fb4-866e-c45aaf8eb4a2
      version: -1
      name: List sessions
      script: carbonblackliveresponse|||cb-list-sessions
      type: regular
      iscommand: true
      brand: carbonblackliveresponse
    nexttasks:
      '#none#':
      - "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
  "30":
    id: "30"
    taskid: 2e53e133-5dce-47f1-8e17-e3c34392a855
    type: regular
    task:
      id: 2e53e133-5dce-47f1-8e17-e3c34392a855
      version: -1
      name: Close session
      script: carbonblackliveresponse|||cb-session-close
      type: regular
      iscommand: true
      brand: carbonblackliveresponse
    scriptarguments:
      session:
        simple: ${CbResponse.Sessions.[0].CbSessionID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
  "36":
    id: "36"
    taskid: dcacf12c-56d8-45c9-8664-aa81f72ac92b
    type: regular
    task:
      id: dcacf12c-56d8-45c9-8664-aa81f72ac92b
      version: -1
      name: Create a process-list command
      script: carbonblackliveresponse|||cb-command-create-and-wait
      type: regular
      iscommand: true
      brand: carbonblackliveresponse
    nexttasks:
      '#none#':
      - "37"
    scriptarguments:
      compress: {}
      get-count: {}
      name:
        simple: process-list
      object: {}
      offset: {}
      output-file: {}
      overwrite: {}
      session:
        simple: ${CbResponse.Sessions.CbSessionID}
      timeout: {}
      value-data: {}
      value-type: {}
      wait-timeout:
        simple: "30"
      working-dir: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "37":
    id: "37"
    taskid: 6922728a-83ca-46bd-8d7c-383d4a360067
    type: regular
    task:
      id: 6922728a-83ca-46bd-8d7c-383d4a360067
      version: -1
      name: Send a keepalive to refresh session timeout
      script: carbonblackliveresponse|||cb-keepalive
      type: regular
      iscommand: true
      brand: carbonblackliveresponse
    nexttasks:
      '#none#':
      - "29"
    scriptarguments:
      session:
        simple: ${CbResponse.Sessions.CbSessionID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
  "39":
    id: "39"
    taskid: 5e79f131-4712-40b5-8f6c-d7f5301ed119
    type: regular
    task:
      id: 5e79f131-4712-40b5-8f6c-d7f5301ed119
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "40"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "40":
    id: "40"
    taskid: 37bcc6dd-bfc9-46ce-894f-677861121377
    type: regular
    task:
      id: 37bcc6dd-bfc9-46ce-894f-677861121377
      version: -1
      name: List sensors
      script: carbonblack-v2|||cb-list-sensors
      type: regular
      iscommand: true
      brand: carbonblack-v2
    nexttasks:
      '#none#':
      - "47"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "41":
    id: "41"
    taskid: 1900f0fa-d300-47d5-8248-d7ff4cc37a19
    type: regular
    task:
      id: 1900f0fa-d300-47d5-8248-d7ff4cc37a19
      version: -1
      name: Create a session for the first sensor in the list
      script: carbonblackliveresponse|||cb-session-create-and-wait
      type: regular
      iscommand: true
      brand: carbonblackliveresponse
    nexttasks:
      '#none#':
      - "36"
    scriptarguments:
      command-timeout: {}
      keepalive-timeout: {}
      sensor:
        simple: ${CbResponse.Sensors.[0].CbSensorID}
      wait-timeout:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "47":
    id: "47"
    taskid: 6b36931b-2fca-407e-8aec-2789fd46b21e
    type: regular
    task:
      id: 6b36931b-2fca-407e-8aec-2789fd46b21e
      version: -1
      name: List open sessions for sensor
      script: carbonblackliveresponse|||cb-list-sessions
      type: regular
      iscommand: true
      brand: carbonblackliveresponse
    nexttasks:
      '#none#':
      - "56"
    scriptarguments:
      sensor:
        simple: ${CbResponse.Sensors.[0].CbSensorID}
      status:
        simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
  "56":
    id: "56"
    taskid: 926cfe33-1536-4691-869d-38f94be6d701
    type: condition
    task:
      id: 926cfe33-1536-4691-869d-38f94be6d701
      version: -1
      name: Check if there's an active session
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "41"
      "yes":
      - "36"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isNotEmpty
          left:
            value:
              simple: CbResponse.Sessions
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
