id: IOC Hunt - TIE - Test
version: -1
name: IOC Hunt - TIE - Test
description: A test playbook for "IOC Hunt - TIE"
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 2cfe76f3-9e13-4507-80f2-71574f8e5b71
    type: start
    task:
      id: 2cfe76f3-9e13-4507-80f2-71574f8e5b71
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: cd75bb5c-f152-44b0-8285-c032e65ca522
    type: regular
    task:
      id: cd75bb5c-f152-44b0-8285-c032e65ca522
      version: -1
      name: Clear context
      description: Clear the context before starting
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 52dfe8df-500d-4c54-894d-bbb4bf6a08f9
    type: regular
    task:
      id: 52dfe8df-500d-4c54-894d-bbb4bf6a08f9
      version: -1
      name: Create testFile1
      description: Create a file with a known hash
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      data:
        simple: ' '
      entryId: {}
      filename:
        simple: testFile1.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    id: "4"
    taskid: 09d89477-4416-47ca-86ea-4ee46d9c10eb
    type: regular
    task:
      id: 09d89477-4416-47ca-86ea-4ee46d9c10eb
      version: -1
      name: Create testFile2
      description: Create another file with a known hash
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      data:
        simple: a
      entryId: {}
      filename:
        simple: testFile2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "7":
    id: "7"
    taskid: b37f5046-3c58-46bb-8061-5b5b7535915f
    type: regular
    task:
      id: b37f5046-3c58-46bb-8061-5b5b7535915f
      version: -1
      name: Verify AgentGuid
      description: Verify AgentGuid exists
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        complex:
          root: File
          filters:
          - - operator: general.isExists
              left:
                value:
                  simple: References
                iscontext: true
          - - operator: general.isNotEmpty
              left:
                value:
                  simple: References.AgentGuid
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "9":
    id: "9"
    taskid: 62d51b99-1ded-46f7-8595-283138319603
    type: playbook
    task:
      id: 62d51b99-1ded-46f7-8595-283138319603
      version: -1
      name: IOC Hunt - TIE
      description: |-
        Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

        Input:
        * Hash (default, takes all deferent hashes from context)

        Output:
        * All agents that files with "Hash" has been executed on (TIE)
        * Enrich Agents info from ePO
      playbookName: IOC Hunt - TIE
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      Hash:
        simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
          b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "10":
    id: "10"
    taskid: 7f19a477-c115-40ab-8f03-ce7187966ca4
    type: title
    task:
      id: 7f19a477-c115-40ab-8f03-ce7187966ca4
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
