id: IOC Hunt - TIE - Test
version: -1
name: IOC Hunt - TIE - Test
description: A test playbook for IOC Hunt - TIE
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 066f0346-5546-4ce7-840d-52444dec212e
    type: start
    task:
      id: 066f0346-5546-4ce7-840d-52444dec212e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: b1cd7dc5-47f3-43c7-8cf8-71306f41a6a6
    type: regular
    task:
      id: b1cd7dc5-47f3-43c7-8cf8-71306f41a6a6
      version: -1
      name: Clear Context
      description: Clear all context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
      extend-context: {}
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    id: "5"
    taskid: f8208b45-3fc1-4e65-80dd-8ad86c8c0060
    type: regular
    task:
      id: f8208b45-3fc1-4e65-80dd-8ad86c8c0060
      version: -1
      name: Verify Context - AgentGuid
      description: Verify Context - AgentGuid
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: File.References.AgentGuid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    id: "6"
    taskid: 73db95ad-1bb5-4204-841f-9e4ed6f12f60
    type: regular
    task:
      id: 73db95ad-1bb5-4204-841f-9e4ed6f12f60
      version: -1
      name: Create hashes for test
      description: Create dummy hashes for test purposes
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append: {}
      key:
        simple: Hashes
      value:
        simple: '["0cc175b9c0f1b6a831c399e269772661", "7215ee9c7d9dc229d2921a40e899ec5f"]'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "7":
    id: "7"
    taskid: 296d1092-4e4d-4af5-8680-f123f22abab1
    type: playbook
    task:
      id: 296d1092-4e4d-4af5-8680-f123f22abab1
      version: -1
      name: TIE - IOC Hunt
      playbookId: TIE - IOC Hunt
      description: ""
      playbookName: TIE - IOC Hunt
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      Hash:
        complex:
          root: Hashes
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"