id: ExtractDomainTest
version: -1
name: ExtractDomainTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 709f1b79-ee47-45f0-882f-60e7146a9a2d
    type: start
    task:
      id: 709f1b79-ee47-45f0-882f-60e7146a9a2d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 73eede55-e81f-4fcb-8119-706d1ed6d7da
    type: regular
    task:
      id: 73eede55-e81f-4fcb-8119-706d1ed6d7da
      version: -1
      name: Extract Domain from www.google.com
      scriptName: ExtractDomain
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      calcReputation: {}
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: www.google.com
      tldList: {}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 285
        }
      }
  "2":
    id: "2"
    taskid: 614aa9af-9f80-4815-8b59-b7c8e403689e
    type: regular
    task:
      id: 614aa9af-9f80-4815-8b59-b7c8e403689e
      version: -1
      name: verify it's google.com
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue:
        simple: google.com
      fields: {}
      path:
        simple: Domain.Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 538
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 583,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
