id: iDefenseTest
version: 30
name: iDefenseTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a0d42c7f-c385-405a-8a38-e02540fc6aa6
    type: start
    task:
      id: a0d42c7f-c385-405a-8a38-e02540fc6aa6
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 5cc140db-7297-464e-8a4d-367e2ca600df
    type: regular
    task:
      id: 5cc140db-7297-464e-8a4d-367e2ca600df
      version: -1
      name: Start Clean
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: e410438f-805c-4aad-8fde-9295ee383196
    type: regular
    task:
      id: e410438f-805c-4aad-8fde-9295ee383196
      version: -1
      name: 'check non existing IP: 8.8.8.8'
      script: iDefense|||ip
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      ip:
        simple: 8.8.8.8
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 63f44aed-0f13-4cd3-8032-eefccbef3c42
    type: regular
    task:
      id: 63f44aed-0f13-4cd3-8032-eefccbef3c42
      version: -1
      name: 'check suspicious IP: 106.184.5.30'
      script: iDefense|||ip
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      ip:
        simple: 106.184.5.30
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: dcfe23f5-62b2-4526-8b68-79ee092d4d59
    type: regular
    task:
      id: dcfe23f5-62b2-4526-8b68-79ee092d4d59
      version: -1
      name: Validate IPs (1)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      expectedValue:
        simple: ip
      fields: {}
      path:
        simple: DBotScore.[0].Type
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "5":
    id: "5"
    taskid: 77512a90-40fe-4515-80b6-13a065bf71b4
    type: regular
    task:
      id: 77512a90-40fe-4515-80b6-13a065bf71b4
      version: -1
      name: 'check good domain: pgeeucpt.uk'
      script: iDefense|||domain
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      domain:
        simple: pgeeucpt.uk
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "6":
    id: "6"
    taskid: 1b3c34c4-e292-406e-8d92-79a0e1a57fee
    type: regular
    task:
      id: 1b3c34c4-e292-406e-8d92-79a0e1a57fee
      version: -1
      name: 'check suspisious domain: txffn.org'
      script: iDefense|||domain
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      domain:
        simple: txffn.org
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "8":
    id: "8"
    taskid: 81b3dd60-c1c2-4a7b-875f-4a5738466b87
    type: regular
    task:
      id: 81b3dd60-c1c2-4a7b-875f-4a5738466b87
      version: -1
      name: Clean context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "9":
    id: "9"
    taskid: 4778337a-e8b0-4f90-8e63-72afdb8f0549
    type: regular
    task:
      id: 4778337a-e8b0-4f90-8e63-72afdb8f0549
      version: -1
      name: Clean context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
  "10":
    id: "10"
    taskid: f84c3868-eb63-4936-8e08-14023c56696b
    type: regular
    task:
      id: f84c3868-eb63-4936-8e08-14023c56696b
      version: -1
      name: 'check suspicious URL: upper-int.ru'
      script: iDefense|||url
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      url:
        simple: upper-int.ru
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1770
        }
      }
  "11":
    id: "11"
    taskid: efc65438-f314-46fa-8848-52720b2c305c
    type: regular
    task:
      id: efc65438-f314-46fa-8848-52720b2c305c
      version: -1
      name: 'Check non existing URL: www.walla.com'
      script: iDefense|||url
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      url:
        simple: www.walla.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
  "12":
    id: "12"
    taskid: c2b7ea12-27ad-476c-848c-efa56722e747
    type: condition
    task:
      id: c2b7ea12-27ad-476c-848c-efa56722e747
      version: -1
      name: Validate URL (2)
      scriptName: StringContains
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "15"
      "yes":
      - "13"
    scriptarguments:
      field1: {}
      field2:
        simple: DBotScore.Type
      field3:
        simple: DBotScore.Score
      field4: {}
      string:
        simple: ${DBotScore.Type}
      substring:
        simple: url
      substringSeperator: {}
      value1: {}
      value2:
        simple: url
      value3:
        simple: "2"
      value4: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 2295
        }
      }
  "13":
    id: "13"
    taskid: 7b4c25aa-6bba-4c97-86fc-4664647fb4fa
    type: regular
    task:
      id: 7b4c25aa-6bba-4c97-86fc-4664647fb4fa
      version: -1
      name: 'Get all known threat '
      script: iDefense|||idefense-general
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      max_result:
        simple: "50"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
  "14":
    id: "14"
    taskid: fb20b5d9-44fc-404e-8aca-d6836f1e2878
    type: condition
    task:
      id: fb20b5d9-44fc-404e-8aca-d6836f1e2878
      version: -1
      name: Validate URL (1)
      scriptName: StringContains
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "15"
      "yes":
      - "12"
    scriptarguments:
      string:
        simple: ${DBotScore.Indicator}
      substring:
        simple: upper-int.ru
      substringSeperator: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2120
        }
      }
  "15":
    id: "15"
    taskid: 36ece665-d4ce-4771-848d-6183be0699ef
    type: regular
    task:
      id: 36ece665-d4ce-4771-848d-6183be0699ef
      version: -1
      name: Error - failing the Test Playbook
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue:
        simple: blablabla
      fields: {}
      path:
        simple: FailTheTest
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2470
        }
      }
  "17":
    id: "17"
    taskid: 9b87d517-ae4a-4d61-8c59-b1cac3314520
    type: regular
    task:
      id: 9b87d517-ae4a-4d61-8c59-b1cac3314520
      version: -1
      name: Search threat by UUID
      script: iDefense|||uuid
      type: regular
      iscommand: true
      brand: iDefense
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      uuid:
        simple: 44a7d355-d160-4bc6-b7f4-4908dc3a4a67
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
  "18":
    id: "18"
    taskid: 26cb48c7-d3c2-488a-8cb3-e3477b88ae6b
    type: regular
    task:
      id: 26cb48c7-d3c2-488a-8cb3-e3477b88ae6b
      version: -1
      name: Clean context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
  "20":
    id: "20"
    taskid: 8e53a413-a3fc-4eac-8787-3477c0c454af
    type: regular
    task:
      id: 8e53a413-a3fc-4eac-8787-3477c0c454af
      version: -1
      name: Validate IPs (2)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      expectedValue:
        simple: "2"
      fields: {}
      path:
        simple: DBotScore.[0].Score
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 692,
          "y": 815
        }
      }
  "21":
    id: "21"
    taskid: 7a3ddc8a-edbb-4b38-8ddd-ad643a98871d
    type: regular
    task:
      id: 7a3ddc8a-edbb-4b38-8ddd-ad643a98871d
      version: -1
      name: Validate IPs (3)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      expectedValue:
        simple: 106.184.5.30
      fields: {}
      path:
        simple: DBotScore.[0].Indicator
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 692,
          "y": 995
        }
      }
  "22":
    id: "22"
    taskid: 8d020ee8-6af9-483f-829a-170a00530fc3
    type: regular
    task:
      id: 8d020ee8-6af9-483f-829a-170a00530fc3
      version: -1
      name: Validate Domains (1)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      expectedValue:
        simple: '["domain","domain"]'
      fields: {}
      path:
        simple: DBotScore.Type
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 692,
          "y": 1420
        }
      }
  "23":
    id: "23"
    taskid: 8b5c79ab-3aef-4604-8ac0-e297118e6847
    type: regular
    task:
      id: 8b5c79ab-3aef-4604-8ac0-e297118e6847
      version: -1
      name: Validate Domains (2)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      expectedValue:
        simple: '["pgeeucpt.uk","txffn.org"]'
      fields: {}
      path:
        simple: DBotScore.Indicator
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 692,
          "y": 1600
        }
      }
  "24":
    id: "24"
    taskid: 2529d6d6-c174-4b70-86eb-69c292a7bffe
    type: regular
    task:
      id: 2529d6d6-c174-4b70-86eb-69c292a7bffe
      version: -1
      name: Validate Domains (3)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      expectedValue:
        simple: '[1,2]'
      fields: {}
      path:
        simple: DBotScore.Score
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 692,
          "y": 1780
        }
      }
  "25":
    id: "25"
    taskid: 8c9f77e6-a2b9-42ef-8ed1-e6314458e654
    type: regular
    task:
      id: 8c9f77e6-a2b9-42ef-8ed1-e6314458e654
      version: -1
      name: Validate UUID (1)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    scriptarguments:
      expectedValue:
        simple: domain
      fields: {}
      path:
        simple: DBotScore.[0].Type
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 576,
          "y": 2752
        }
      }
  "26":
    id: "26"
    taskid: 98156052-f878-4d25-8931-b168b057a26f
    type: regular
    task:
      id: 98156052-f878-4d25-8931-b168b057a26f
      version: -1
      name: Validate UUID (2)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      expectedValue:
        simple: yahoolive.us
      fields: {}
      path:
        simple: Domain.Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 576,
          "y": 2932
        }
      }
  "27":
    id: "27"
    taskid: 1dfe5490-0811-43ab-8b94-23fbf1334630
    type: regular
    task:
      id: 1dfe5490-0811-43ab-8b94-23fbf1334630
      version: -1
      name: Validate UUID (3)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    scriptarguments:
      expectedValue:
        simple: yahoolive.us
      fields: {}
      path:
        simple: DBotScore.[0].Indicator
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 576,
          "y": 3090
        }
      }
  "28":
    id: "28"
    taskid: e751bfa1-74e6-458a-850c-2dbabf0bc22e
    type: regular
    task:
      id: e751bfa1-74e6-458a-850c-2dbabf0bc22e
      version: -1
      name: Validate UUID (4)
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue:
        simple: "2"
      fields: {}
      path:
        simple: DBotScore.[0].Score
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 576,
          "y": 3270
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "12_15_no": 0.5,
      "14_15_no": 0.74
    },
    "paper": {
      "dimensions": {
        "height": 3315,
        "width": 1022,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []