id: langDetect-Test
version: -1
name: langDetect-Test
description: Testing langDetect script
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bfdc77ce-bb32-4c87-8af0-0ef088940c53
    type: start
    task:
      id: bfdc77ce-bb32-4c87-8af0-0ef088940c53
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 238a2ccc-2d44-48e7-8d20-183a9cdecfc0
    type: regular
    task:
      id: 238a2ccc-2d44-48e7-8d20-183a9cdecfc0
      version: -1
      name: Detect english
      scriptName: langDetect
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      text: Hello World
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: d471e1c2-e804-405a-8050-ae5bd079285b
    type: condition
    task:
      id: d471e1c2-e804-405a-8050-ae5bd079285b
      version: -1
      name: Check if we found English
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    scriptarguments:
      value: ${langDetect(val.lang=='en')}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 0c183f63-ecf5-4c89-8912-f6c108d09081
    type: regular
    task:
      id: 0c183f63-ecf5-4c89-8912-f6c108d09081
      version: -1
      name: Close
      scriptName: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: ""
      reason: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
