id: McAfee-TIE Test
version: -1
name: McAfee-TIE Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e77800cc-02ad-46ca-83b6-ee794627b9c3
    type: start
    task:
      id: e77800cc-02ad-46ca-83b6-ee794627b9c3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 10b6fb19-2aeb-4a21-884f-003b10727430
    type: regular
    task:
      id: 10b6fb19-2aeb-4a21-884f-003b10727430
      version: -1
      name: Verify Context File Reputation
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: ""
      fields: TrustLevel,Vendor,SHA1
      path: File
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 29e9c569-921d-431a-8769-fc1dd246b276
    type: regular
    task:
      id: 29e9c569-921d-431a-8769-fc1dd246b276
      version: -1
      name: Verify Context DBot Score
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: ""
      fields: Vendor,Indicator,Score,Type
      path: DBotScore
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    id: "5"
    taskid: 5193413b-8fee-4858-8445-96d6f7bb5a46
    type: regular
    task:
      id: 5193413b-8fee-4858-8445-96d6f7bb5a46
      version: -1
      name: TIE file reputation
      description: Retrieves the reputations for the specified hash ( Supports MD5
        SHA1 & SHA256)
      script: McAfee Threat Intelligence Exchange|||file
      type: regular
      iscommand: true
      brand: McAfee Threat Intelligence Exchange
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      file: 6EAE26DB8C13182A7947982991B4321732CC3DE2
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
