id: Monochrome
version: 1
name: Monochrome
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a45fec39-f849-4914-89f1-a171103f8884
    type: start
    task:
      id: a45fec39-f849-4914-89f1-a171103f8884
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 4decd66c-1ce0-41ab-8d10-e9d805b75e80
    type: regular
    task:
      id: 4decd66c-1ce0-41ab-8d10-e9d805b75e80
      version: -1
      name: PrintContext
      description: Pretty-print the contents of the playbook context
      scriptName: PrintContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      outputformat: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
