id: Splunk-Test
version: -1
name: Splunk-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e8d1a9d6-027c-4043-8d29-2781fa9a25d5
    type: start
    task:
      id: e8d1a9d6-027c-4043-8d29-2781fa9a25d5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 6d673a2c-c2c3-4ff8-803b-d2419a83f916
    type: regular
    task:
      id: 6d673a2c-c2c3-4ff8-803b-d2419a83f916
      version: -1
      name: splunk-search
      description: Search Splunk for events
      script: SplunkPy|||splunk-search
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      earliest_time:
        simple: -1000d
      event_limit: {}
      latest_time: {}
      query:
        simple: '* | head 3'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: 4d00e0d9-c3de-41c9-8964-5ada56ebe449
    type: regular
    task:
      id: 4d00e0d9-c3de-41c9-8964-5ada56ebe449
      version: -1
      name: Verify Context result of Splunk Search
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: ${Splunk.Result}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 57ff69a7-377a-4307-8fd2-99c523c28deb
    type: regular
    task:
      id: 57ff69a7-377a-4307-8fd2-99c523c28deb
      version: -1
      name: Get indexes names
      script: SplunkPy|||splunk-get-indexes
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      extend-context:
        simple: indexes=
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: 8620f3ed-26ee-41d5-8e31-972e998537cc
    type: condition
    task:
      id: 8620f3ed-26ee-41d5-8e31-972e998537cc
      version: -1
      name: Has main index
      scriptName: StringContains
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "5"
    scriptarguments:
      left: {}
      right: {}
      string:
        simple: ${JsonStr}
      substring:
        simple: main
      substringSeperator: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "5":
    id: "5"
    taskid: e77650cb-56ce-4529-8260-4c57a8ce3b94
    type: regular
    task:
      id: e77650cb-56ce-4529-8260-4c57a8ce3b94
      version: -1
      name: Create new Splunk event
      script: SplunkPy|||splunk-submit-event
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      data:
        simple: test
      host:
        simple: localhost
      index:
        simple: main
      sourcetype:
        simple: demisto-ci
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "6":
    id: "6"
    taskid: 97c66fb9-18ac-4e68-8a06-b48579f1e3e9
    type: regular
    task:
      id: 97c66fb9-18ac-4e68-8a06-b48579f1e3e9
      version: -1
      name: DumpJSON
      description: Dumps a json from context key input, and returns a json object
        string result
      scriptName: DumpJSON
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      extend-context: {}
      key:
        simple: indexes
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "7":
    id: "7"
    taskid: 6d7873fd-79d7-4d63-880f-059466574d29
    type: regular
    task:
      id: 6d7873fd-79d7-4d63-880f-059466574d29
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
  "8":
    id: "8"
    taskid: f49679c7-4f5e-4582-8324-94c4ea1e18fb
    type: regular
    task:
      id: f49679c7-4f5e-4582-8324-94c4ea1e18fb
      version: -1
      name: Test eventcount query
      script: SplunkPy|||splunk-search
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      earliest_time: {}
      event_limit: {}
      extend-context:
        simple: eventcount=
      latest_time: {}
      query:
        simple: '| eventcount'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "9":
    id: "9"
    taskid: 0daa1ba8-5d92-4f42-8897-96a4ab8e1602
    type: condition
    task:
      id: 0daa1ba8-5d92-4f42-8897-96a4ab8e1602
      version: -1
      name: Verify eventcount
      scriptName: IsGreaterThan
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "11"
      "yes":
      - "12"
    scriptarguments:
      first:
        simple: ${eventcount.[0].count}
      second:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
  "10":
    id: "10"
    taskid: aa5182a1-d082-4f40-8fdf-89701ee9d857
    type: regular
    task:
      id: aa5182a1-d082-4f40-8fdf-89701ee9d857
      version: -1
      name: Hurry!
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Hurry!
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2645
        }
      }
  "11":
    id: "11"
    taskid: 45be7519-b926-4e6e-8a6a-a0fcfbc67feb
    type: regular
    task:
      id: 45be7519-b926-4e6e-8a6a-a0fcfbc67feb
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "12":
    id: "12"
    taskid: 48213731-f2f6-4977-80f6-3a6ade499613
    type: title
    task:
      id: 48213731-f2f6-4977-80f6-3a6ade499613
      version: -1
      name: Test _raw parsing
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1610
        }
      }
  "13":
    id: "13"
    taskid: 1447c7b2-1cd0-4292-83c6-2aeca4bcee7d
    type: regular
    task:
      id: 1447c7b2-1cd0-4292-83c6-2aeca4bcee7d
      version: -1
      name: Parse Raw
      script: SplunkPy|||splunk-parse-raw
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      raw: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
  "14":
    id: "14"
    taskid: 25d906c9-d47d-41f2-842f-9771fda890e4
    type: regular
    task:
      id: 25d906c9-d47d-41f2-842f-9771fda890e4
      version: -1
      name: Verify parse get's to context
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Splunk.Raw.Parsed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
  "15":
    id: "15"
    taskid: 9ffe77c1-53b8-423d-83c4-886e5cb86221
    type: regular
    task:
      id: 9ffe77c1-53b8-423d-83c4-886e5cb86221
      version: -1
      name: Add raw Data example
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      append: {}
      key:
        simple: rawEvent
      value:
        simple: '2018-04-23 14:28:49,Potential risk found,Computer name: iiiii,Detection type: Suspicious Behavior Detection,First Seen: Symantec has known about this file for more than 1 year.,Application name: Microsoft\\\\xAE Windows\\\\xAE Operating System,Application type: Trojan Worm,Application version: 6.1.7600.16385,Hash type: SHA-1,Application hash: e5d6725d-742b-4365-8402-62466d275c05,Company name: KKK.,LLLL,MMMM,File size (bytes): 1842,Sensitivity: 0,Detection score: 3,COH Engine Version: 11.3.2.9,Detection Submissions No,Permitted application reason: Not on the permitted application list,Disposition: Bad,Download site: https://www.example.com/army/basket,Web domain: pcqxcoxljjtcrui.ac,Downloaded by: c:/users/administrator/desktop/tools/tools/xxxtools.exe,Prevalence: Unknown,Confidence: There is not enough information about this file to recommend it.,URL Tracking Status: on,Risk Level: Reputation was not used in this detection.,Detection Source: ,Source: SONAR Scan,Risk name: SONAR.Heuristic.121,Occurrences: 7,c:\\\\users\\\\example\\\\appdata\\\\local\\\\temp\\\\example\\\\socar.exe,Still contains 2 infected items,Actual action: Quarantined,Requested action: Quarantined,Secondary action: Quarantined,Event time: 2018-04-23 14:28:49,Inserted: 2018-04-23 14:28:49,End: 2018-04-23 14:28:49,Domain: Domain B,Group: My Company\\\\ZZZZ,Server: Example Server D,User: user_a,Source computer: eeeee,Source IP: 10.0.2.4\n\", signature=\"Trojan Worm\"'
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
  "16":
    id: "16"
    taskid: aae19ee0-0c38-479b-8469-eb077ecd7cbf
    type: regular
    task:
      id: aae19ee0-0c38-479b-8469-eb077ecd7cbf
      version: -1
      name: Parse Raw example
      script: SplunkPy|||splunk-parse-raw
      type: regular
      iscommand: true
      brand: SplunkPy
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      extend-context:
        simple: parsedRaw=
      raw:
        simple: ${rawEvent}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2295
        }
      }
  "17":
    id: "17"
    taskid: 35fe8b6f-a77c-4a79-8518-668e9a33904a
    type: condition
    task:
      id: 35fe8b6f-a77c-4a79-8518-668e9a33904a
      version: -1
      name: Is Raw parsed ?
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "18"
      "yes":
      - "10"
    scriptarguments:
      left:
        simple: ${parsedRaw.search_name}
      right:
        simple: Endpoint - CB Response Hit for Bit9AdvancedThreats Threat Intel Feed
          - Rule
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2470
        }
      }
  "18":
    id: "18"
    taskid: 4869dfde-e598-4895-82fa-c9015aeab227
    type: regular
    task:
      id: 4869dfde-e598-4895-82fa-c9015aeab227
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2645
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2690,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
