id: IPInfoTest
version: 18
name: IPInfoTest
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3fcfb95e-64bd-48bc-8b05-51d7d2337ad8
    type: start
    task:
      id: 3fcfb95e-64bd-48bc-8b05-51d7d2337ad8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 1da32561-ba3f-47c4-837d-38fdc4f0605d
    type: regular
    task:
      id: 1da32561-ba3f-47c4-837d-38fdc4f0605d
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all: ""
      key: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: bb28330c-772e-4858-8343-02de54eafdf5
    type: regular
    task:
      id: bb28330c-772e-4858-8343-02de54eafdf5
      version: -1
      name: ip
      description: Check IP reputation (when information is available, returns a JSON
        with details).  Uses all configured Threat Intelligence feeds
      script: ipinfo|||ip
      type: regular
      iscommand: true
      brand: ipinfo
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      ip: 1.1.1.1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 63238b08-836b-4d47-86e5-4b5de8261003
    type: regular
    task:
      id: 63238b08-836b-4d47-86e5-4b5de8261003
      version: -1
      name: VerifyContext IP
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: ""
      fields: Address, Geo.Description, Geo.Country, Geo.Location
      path: IP
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
