id: McAfee-MAR_Test
version: -1
name: McAfee-MAR_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 38d3a420-d501-4afe-8da4-e47626d3bd3c
    type: start
    task:
      id: 38d3a420-d501-4afe-8da4-e47626d3bd3c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 3203c732-9d89-486e-80b7-c98646411577
    type: regular
    task:
      id: 3203c732-9d89-486e-80b7-c98646411577
      version: -1
      name: mar-collectors-list
      description: Returns a list of all collectors and their outputs
      script: McAfee Active Response|||mar-collectors-list
      type: regular
      iscommand: true
      brand: McAfee Active Response
    nexttasks:
      '#none#':
      - "2"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: abacf63a-3464-4e7b-8159-773af8a4d99f
    type: regular
    task:
      id: abacf63a-3464-4e7b-8159-773af8a4d99f
      version: -1
      name: mar-search
      description: Search endpoint data
      script: McAfee Active Response|||mar-search
      type: regular
      iscommand: true
      brand: McAfee Active Response
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      collector: HostInfo
      filter-by: ""
      filter-operator: ""
      filter-value: ""
      outputs: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: 2c8251e8-bdf3-4342-8a34-2a3203aec867
    type: regular
    task:
      id: 2c8251e8-bdf3-4342-8a34-2a3203aec867
      version: -1
      name: VerifyContext mar-search
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      expectedValue: ""
      fields: os,created_at,hostname,ip_address
      path: MAR.HostInfo
    view: |-
      {
        "position": {
          "x": 50,
          "y": 550
        }
      }
  "4":
    id: "4"
    taskid: d86fa58a-2a71-408f-8d12-1ff6c9541e7e
    type: regular
    task:
      id: d86fa58a-2a71-408f-8d12-1ff6c9541e7e
      version: -1
      name: mar-search with filter
      description: '!mar-search collector=Processes filter-by=name filter-operator=Equals
        filter-value=SYSTEM outputs=user_id,name,uptime'
      script: McAfee Active Response|||mar-search
      type: regular
      iscommand: true
      brand: McAfee Active Response
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      collector: Processes
      filter-by: name
      filter-operator: Equals
      filter-value: SYSTEM
      outputs: user_id,name,uptime
    view: |-
      {
        "position": {
          "x": 50,
          "y": 727
        }
      }
  "5":
    id: "5"
    taskid: e1c37161-0e74-4211-8cda-4939ca486df3
    type: regular
    task:
      id: e1c37161-0e74-4211-8cda-4939ca486df3
      version: -1
      name: VerifyContext mar-search with filter
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: ""
      fields: user_id,name,uptime
      path: MAR.Processes
    view: |-
      {
        "position": {
          "x": 50,
          "y": 901
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 946,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
