id: Anomali_ThreatStream_Test
version: -1
fromversion: 3.5.0
name: Anomali ThreatStream Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cc16a1a8-e966-460b-8056-aac54e3515f2
    type: start
    task:
      id: cc16a1a8-e966-460b-8056-aac54e3515f2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: ba9f9bad-2bce-410d-815e-fceed9b85b4d
    type: regular
    task:
      id: ba9f9bad-2bce-410d-815e-fceed9b85b4d
      version: -1
      name: threatstream-intelligence (type=ip, value=218.227.212.90)
      description: To retrieve threat intelligence from the ThreatStream cloud
      script: Anomali ThreatStream|||threatstream-intelligence
      type: regular
      iscommand: true
      brand: Anomali ThreatStream
    nexttasks:
      '#none#':
      - "2"
      - "4"
      - "5"
    scriptarguments:
      asn: {}
      confidence: {}
      country: {}
      created_ts: {}
      expiration_ts: {}
      feed_id: {}
      id: {}
      import_session_ id: {}
      ip: {}
      is_public: {}
      itype: {}
      latitude: {}
      limit: {}
      longitude: {}
      meta.detail: {}
      meta.detail2: {}
      meta.maltype: {}
      meta.severity: {}
      modified_ts: {}
      org: {}
      owner_ organization_id: {}
      rdns: {}
      source_reported_ confidence: {}
      status: {}
      tags.name: {}
      threat_type: {}
      trusted_circle_ids: {}
      type:
        simple: ip
      update_id: {}
      using:
        simple: Anomali_ThreatStream_instance_1
      value:
        simple: 218.227.212.90
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "2":
    id: "2"
    taskid: f750cef2-9d1e-48db-82e2-a5e21a92a0b7
    type: regular
    task:
      id: f750cef2-9d1e-48db-82e2-a5e21a92a0b7
      version: -1
      name: ip (176.228.66.70)
      description: Checks the reputation of the given IP
      script: Anomali ThreatStream|||ip
      type: regular
      iscommand: true
      brand: Anomali ThreatStream
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      ip:
        simple: 176.228.66.70
      threshold: {}
      using:
        simple: Anomali_ThreatStream_instance_1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "3":
    id: "3"
    taskid: 1e846eb4-2634-4b78-8beb-659486208c2e
    type: regular
    task:
      id: 1e846eb4-2634-4b78-8beb-659486208c2e
      version: -1
      name: domain (kpanels.in)
      description: Checks the reputation of the given IP or domain name
      script: Anomali ThreatStream|||domain
      type: regular
      iscommand: true
      brand: Anomali ThreatStream
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      domain:
        simple: kpanels.in
      threshold: {}
      using:
        simple: Anomali_ThreatStream_instance_1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "4":
    id: "4"
    taskid: 5f3b4257-7df5-48f4-8ae8-df336d0f5f45
    type: regular
    task:
      id: 5f3b4257-7df5-48f4-8ae8-df336d0f5f45
      version: -1
      name: file (3e5d63b93a68d715f7559f42285223f4)
      description: Checks the reputation of the given checksum
      script: Anomali ThreatStream|||file
      type: regular
      iscommand: true
      brand: Anomali ThreatStream
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      file:
        simple: 3e5d63b93a68d715f7559f42285223f4
      threshold: {}
      using:
        simple: Anomali_ThreatStream_instance_1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    id: "5"
    taskid: 9949f81e-3a07-4272-8c2a-39d3a0a92b0a
    type: regular
    task:
      id: 9949f81e-3a07-4272-8c2a-39d3a0a92b0a
      version: -1
      name: threatstream-email-reputation (mailonline_16@filposcv.com)
      description: Checks the reputation of the given email
      script: Anomali ThreatStream|||threatstream-email-reputation
      type: regular
      iscommand: true
      brand: Anomali ThreatStream
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      email:
        simple: mailonline_16@filposcv.com
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
  "6":
    id: "6"
    taskid: 0350626f-e2bc-4011-8627-672c67fe1855
    type: regular
    task:
      id: 0350626f-e2bc-4011-8627-672c67fe1855
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "7":
    id: "7"
    taskid: e157f516-36e1-4a79-8506-d9052a6b4989
    type: regular
    task:
      id: e157f516-36e1-4a79-8506-d9052a6b4989
      version: -1
      name: VerifyContext (File)
      description: |+
        Verify path in context
        - Verify path existence
        - If matching object is array - verify fields exists in each object in array
        - If matching object is not array - verify fields exists in matching object
        - if 'expectedValue' supplied - ensure that given value equal to context path

      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: MD5, Malicious, Score
      path:
        simple: File
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "8":
    id: "8"
    taskid: 1d6adc0e-ce79-4ee7-8b57-c0211d7add19
    type: regular
    task:
      id: 1d6adc0e-ce79-4ee7-8b57-c0211d7add19
      version: -1
      name: VerifyContext (IP)
      description: |+
        Verify path in context
        - Verify path existence
        - If matching object is array - verify fields exists in each object in array
        - If matching object is not array - verify fields exists in matching object
        - if 'expectedValue' supplied - ensure that given value equal to context path

      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ASN, Address, Geo, Malicious, Score
      path:
        simple: IP
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "9":
    id: "9"
    taskid: 54fcfa9e-2a6c-4f02-806e-2c2d19d8d6f0
    type: regular
    task:
      id: 54fcfa9e-2a6c-4f02-806e-2c2d19d8d6f0
      version: -1
      name: VerifyContext (Domain)
      description: |+
        Verify path in context
        - Verify path existence
        - If matching object is array - verify fields exists in each object in array
        - If matching object is not array - verify fields exists in matching object
        - if 'expectedValue' supplied - ensure that given value equal to context path

      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: DNS, Name, Score
      path:
        simple: Domain
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "11":
    id: "11"
    taskid: 7bf1a60f-4517-46db-8183-0cbd7049e434
    type: regular
    task:
      id: 7bf1a60f-4517-46db-8183-0cbd7049e434
      version: -1
      name: VerifyContext (ThreatStream.EmailReputation)
      description: |+
        Verify path in context
        - Verify path existence
        - If matching object is array - verify fields exists in each object in array
        - If matching object is not array - verify fields exists in matching object
        - if 'expectedValue' supplied - ensure that given value equal to context path

      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Itype, Created, Modified, Confidence, Details1, Details2, Status,
          ThreatScore, Source, Id, Email, Severity
      path:
        simple: ThreatStream.EmailReputation
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"