id: Test - DBot Indicator Enrichment - Generic
version: -1
name: Test - DBot Indicator Enrichment - Generic
description: Test "DBot Indicator Enrichment" playbook
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 8ba9b6f2-da24-4ab2-8448-0dd66e916131
    type: start
    task:
      id: 8ba9b6f2-da24-4ab2-8448-0dd66e916131
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 7b5186d2-823f-4d19-8f54-397edf40b686
    type: playbook
    task:
      id: 7b5186d2-823f-4d19-8f54-397edf40b686
      version: -1
      name: DBot Indicator Enrichment - Generic
      description: ""
      playbookName: DBot Indicator Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    id: "2"
    taskid: a55e812a-4cd0-4307-8e88-9d31345ac564
    type: regular
    task:
      id: a55e812a-4cd0-4307-8e88-9d31345ac564
      version: -1
      name: Set IP reputation
      description: Set IP for test
      scriptName: IndicatorSet
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      indicator:
        simple: 1.2.3.4
      reputation:
        simple: Suspicious
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 3b7d6611-cb8c-4827-8273-9bfb59894ce1
    type: regular
    task:
      id: 3b7d6611-cb8c-4827-8273-9bfb59894ce1
      version: -1
      name: Set Ip into context
      description: set IP into context
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      append: {}
      key:
        simple: IP.Address
      value:
        simple: 1.2.3.4
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    id: "4"
    taskid: 1ab3374f-1797-4de6-8e1b-5faae2a7128d
    type: regular
    task:
      id: 1ab3374f-1797-4de6-8e1b-5faae2a7128d
      version: -1
      name: Assert result
      description: Check results
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: DBotScore
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
