commonfields:
  id: TestCreateDuplicates
  version: -1
name: TestCreateDuplicates
script: |-
  import dateutil.parser
  from datetime import timedelta
  incident = demisto.incidents()[0]

  def parse_label(label):
      return {label['type']: label['value']}

  new_incident_time = dateutil.parser.parse(incident['occurred']) - timedelta(hours=int(demisto.args()['hoursDiff']))
  res = demisto.executeCommand("createNewIncident", {'name': 'ThisIsATestForDuplicate',
  'occurred': new_incident_time.isoformat(), 'type': incident['type'],
  'labels': map(parse_label, incident['labels'])
  })
  demisto.results(res)
type: python
tags: []
comment: Create a duplicate incident to the current.
enabled: true
args:
- name: hoursDiff
  description: Hours different between the original incident and created incident.
  defaultValue: "2"
scripttarget: 0
runonce: false
