commonfields:
  id: TestCreateWordFile
  version: -1
name: TestCreateWordFile
script: |
  from StringIO import StringIO
  from docx import Document

  res = []
  errEntry = {
      "Type": entryTypes["error"],
      "ContentsFormat": formats["text"],
      "Contents": ""
  }

  args = demisto.args()
  try:
      document = Document()
      document.add_paragraph(args['text'])
      demisto.log('1')
      target_stream = StringIO()
      demisto.log('2')
      document.save(target_stream)
      demisto.log('3')
      res = fileResult(args['name'], target_stream.getvalue())
      demisto.log('4')
  except BaseException as e:
      errEntry["Contents"] = "Error occurred while creating the word file.\nException info: " + str(e)
      res = errEntry

  demisto.results(res)
type: python
tags: []
comment: A test script to create a word file with a text as content and file name
  and put it in the context.
enabled: true
args:
- name: name
  required: true
  description: The name of the file to create
- name: text
  required: true
  description: The content of the file to create
scripttarget: 0
dockerimage: demisto/word-parser
