id: CrowdStrike Enrichment Playbook
version: 4
name: CrowdStrike Enrichment Playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2380acff-abe1-46f1-8910-1aedfd2dd492
    type: start
    task:
      id: 2380acff-abe1-46f1-8910-1aedfd2dd492
      version: 1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 3105f277-5117-4c1e-8ccd-ccdd178ca962
    type: regular
    task:
      id: 3105f277-5117-4c1e-8ccd-ccdd178ca962
      version: 1
      name: Check MD5s
      script: crowdstrike-intel|||file
      type: regular
      iscommand: true
      brand: crowdstrike-intel
    scriptarguments:
      file: ${File.MD5}
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "3":
    id: "3"
    taskid: a47488ec-b99f-4b6c-8b1c-8237588a86b7
    type: regular
    task:
      id: a47488ec-b99f-4b6c-8b1c-8237588a86b7
      version: 1
      name: Check SHA1s
      script: crowdstrike-intel|||file
      type: regular
      iscommand: true
      brand: crowdstrike-intel
    scriptarguments:
      file: ${File.SHA1}
    view: |-
      {
        "position": {
          "x": 893,
          "y": 220
        }
      }
  "4":
    id: "4"
    taskid: afbc5729-8165-4c29-8f54-7a5af5366906
    type: regular
    task:
      id: afbc5729-8165-4c29-8f54-7a5af5366906
      version: 1
      name: Check SHA256s
      script: crowdstrike-intel|||file
      type: regular
      iscommand: true
      brand: crowdstrike-intel
    scriptarguments:
      file: ${File.SHA256}
    view: |-
      {
        "position": {
          "x": -23,
          "y": 220
        }
      }
  "5":
    id: "5"
    taskid: 8aff31d4-dfea-40b2-8f14-e60dea0a9fc9
    type: regular
    task:
      id: 8aff31d4-dfea-40b2-8f14-e60dea0a9fc9
      version: 1
      name: Check IPs
      script: crowdstrike-intel|||ip
      type: regular
      iscommand: true
      brand: crowdstrike-intel
    scriptarguments:
      file: ${File.SHA256}
      ip: ${IP.Address}
    view: |-
      {
        "position": {
          "x": -505,
          "y": 220
        }
      }
  "6":
    id: "6"
    taskid: 462ebe6e-30b3-4856-8bec-0275247e7a5b
    type: regular
    task:
      id: 462ebe6e-30b3-4856-8bec-0275247e7a5b
      version: 1
      name: Check URLs
      script: crowdstrike-intel|||url
      type: regular
      iscommand: true
      brand: crowdstrike-intel
    scriptarguments:
      file: ${File.SHA256}
      ip: ${IP.Address}
      url: ${URL}
    view: |-
      {
        "position": {
          "x": -988,
          "y": 220
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 2261,
        "x": -988,
        "y": 50
      }
    }
  }
