id: WildFire - Detonate file
version: -1
name: WildFire - Detonate file
description: Detonate files through WildFire
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 089f0d6b-2af7-4990-8013-ba815b38bca8
    type: start
    task:
      id: 089f0d6b-2af7-4990-8013-ba815b38bca8
      version: -1
      description: ""
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "4":
    id: "4"
    taskid: ab4f7c4b-4afe-4d19-8156-7da0508cefd4
    type: regular
    task:
      id: ab4f7c4b-4afe-4d19-8156-7da0508cefd4
      version: -1
      name: DetonateFile (WildFire)
      description: Detonate the file in WildFire.
      script: WildFire|||detonate-file
      type: regular
      iscommand: true
      brand: WildFire
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      delay: ""
      entryID: ${File(['exe', 'pe32', 'pe64', 'pdf'].filter(function(t) {return val.Info.toLowerCase().indexOf(t)
        >= 0 || val.Type.toLowerCase().indexOf(t) >= 0;}).length > 0).EntryID}
      format: ""
      hash: ""
      interval: ""
      md5: ""
      timeout: ""
      upload: ${File(['exe', 'pe32', 'pe64', 'pdf'].filter(function(t) {return val.Info.toLowerCase().indexOf(t)
        >= 0 || val.Type.toLowerCase().indexOf(t) >= 0;}).length > 0).EntryID}
      verbose: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    id: "5"
    taskid: f47ddd4c-20b8-4803-8521-ba5134aa0375
    type: condition
    task:
      id: f47ddd4c-20b8-4803-8521-ba5134aa0375
      version: -1
      name: Is WildFire enabled?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "4"
    scriptarguments:
      value: ${modules(val.brand == 'WildFire' && val.state == 'active')}
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "6":
    id: "6"
    taskid: 48bff149-dda3-493c-89a7-ab76925eb0a6
    type: title
    task:
      id: 48bff149-dda3-493c-89a7-ab76925eb0a6
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: EntryID
  value: ${File.EntryID}
  description: EntryID of file to be uploaded
outputs: []
releaseNotes: "Detonating files using the new command for it in WildFire"