id: Hunt for bad IOCs
version: -1
name: Hunt for bad IOCs
fromVersion: 2.5.0
system: true
description: Assume that malicious IOCs are in the right place in the context and
  start hunting using available tools
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9d563269-d6b7-4d77-83c8-8916860ed44b
    type: start
    task:
      id: 9d563269-d6b7-4d77-83c8-8916860ed44b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "2"
      - "3"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 4575847d-6979-4a86-8f77-ad7afcda5b01
    type: playbook
    task:
      id: 4575847d-6979-4a86-8f77-ad7afcda5b01
      version: -1
      name: ""
      playbookName: Carbon black Protection Rapid IOC Hunting
      type: playbook
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: ea507294-262f-4b30-879a-7a0d33944a0f
    type: playbook
    task:
      id: ea507294-262f-4b30-879a-7a0d33944a0f
      version: -1
      name: ""
      playbookName: Carbon Black Rapid IOC Hunting
      type: playbook
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 69cac33b-55de-4223-84f4-dea5ccca44e9
    type: playbook
    task:
      id: 69cac33b-55de-4223-84f4-dea5ccca44e9
      version: -1
      name: ""
      playbookName: CrowdStrike Rapid IOC Hunting
      type: playbook
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 240,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
