id: account_enrichment_-_generic
version: -1
name: Account Enrichment - Generic
fromversion: "3.5.0"
description: Enrich Accounts using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 03bb7183-afc8-4bcd-8f32-5c35d41fdcad
    type: start
    task:
      id: 03bb7183-afc8-4bcd-8f32-5c35d41fdcad
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: c9efda34-5c97-4be8-8dab-f0e318355a29
    type: condition
    task:
      id: c9efda34-5c97-4be8-8dab-f0e318355a29
      version: -1
      name: Is there a username to query?
      description: Checks if there's a username to query
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value: inputs.Username
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 193
        }
      }
  "2":
    id: "2"
    taskid: ecd2967b-740c-4806-8a1e-77ff1b093991
    type: title
    task:
      id: ecd2967b-740c-4806-8a1e-77ff1b093991
      version: -1
      name: Active Directory
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "3":
    id: "3"
    taskid: b3c42fed-7e9b-428e-8fd6-142c05a2cbd1
    type: title
    task:
      id: b3c42fed-7e9b-428e-8fd6-142c05a2cbd1
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "4":
    id: "4"
    taskid: 19f64d77-18f2-45a6-8ec5-9d2203d9637a
    type: condition
    task:
      id: 19f64d77-18f2-45a6-8ec5-9d2203d9637a
      version: -1
      name: Is Active Directory enabled?
      description: Checks if there's an active "Active Directory" instance
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: activedir
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 515
        }
      }
  "5":
    id: "5"
    taskid: a1e1dfa5-6bb7-47d7-89ae-2d4c47266c04
    type: regular
    task:
      id: a1e1dfa5-6bb7-47d7-89ae-2d4c47266c04
      version: -1
      name: Get Account info from Active Directory
      description: Query "Active Directory" for the username's info
      scriptName: ADGetUser
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      email: {}
      headers: {}
      limit: {}
      name: {}
      nestedSearch: {}
      userAccountControlOut: {}
      username:
        simple: ${Account.Username}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 690
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Username
  value:
    simple: ${Account.Username}
  required: false
  description: The Username to enrich
outputs:
- contextPath: Account.Type
  description: Type of the Account entity
  type: string
- contextPath: Account.ID
  description: The unique Account DN (Distinguished Name)
  type: string
- contextPath: Account.Username
  description: The Account username
  type: string
- contextPath: Account.Email
  description: The email address associated with the Account
  type: string
- contextPath: Account.Groups
  description: The groups the Account is part of
  type: unknown
- contextPath: Account.DisplayName
  description: The Account display name
  type: string
- contextPath: Account.Manager
  description: The Account's manager
  type: string
