id: playbook0
version: 3
name: Default
description: Default playbook to help classify incoming incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 96dbf98e-bc4e-4d21-808f-54cf03241207
    type: start
    task:
      id: 96dbf98e-bc4e-4d21-808f-54cf03241207
      version: 1
      name: start_task
      type: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    view: |-
      {
        "position": {
          "x": -255,
          "y": 44
        }
      }
  "2":
    id: "2"
    taskid: 6a0aef28-d546-47af-8947-99f46d77d48a
    type: condition
    task:
      id: 6a0aef28-d546-47af-8947-99f46d77d48a
      version: 1
      name: Is this an email
      scriptName: Exists
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "3"
    scriptarguments:
      key: Label/Email/from
      value: ${incident.labels.Email/from}
    view: |-
      {
        "position": {
          "x": -257,
          "y": 391
        }
      }
  "3":
    id: "3"
    taskid: 5f274bd6-82a8-4f81-87e9-ca8561e78661
    type: condition
    task:
      id: 5f274bd6-82a8-4f81-87e9-ca8561e78661
      version: 1
      name: Is this email coming from Splunk
      scriptName: Set
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    scriptarguments:
      key: incident.labels.Email/from
      value: set-to-splunk-sender
    view: |-
      {
        "position": {
          "x": 50,
          "y": 583
        }
      }
  "4":
    id: "4"
    taskid: 3e289371-6cd3-4665-8109-6c79c71fbfc2
    type: regular
    task:
      id: 3e289371-6cd3-4665-8109-6c79c71fbfc2
      version: 6
      name: SplunkEmailParser
      scriptName: SplunkEmailParser
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      body: ${Label/Email/html}
      subject: ${Label/Email/subject}
    view: |-
      {
        "position": {
          "x": 573,
          "y": 749
        }
      }
  "5":
    id: "5"
    taskid: 4225b27f-723a-4a25-8756-1e1cfd7e234f
    type: condition
    task:
      id: 4225b27f-723a-4a25-8756-1e1cfd7e234f
      version: 1
      name: Is this a Nexpose email
      scriptName: Set
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    scriptarguments:
      key: incident.labels.Email/from
      value: set-to-nexpose-sender
    view: |-
      {
        "position": {
          "x": 50,
          "y": 917
        }
      }
  "6":
    id: "6"
    taskid: cda168ea-c74d-40b4-89cb-67014f85409d
    type: regular
    task:
      id: cda168ea-c74d-40b4-89cb-67014f85409d
      version: 6
      name: NexposeEmailParser
      scriptName: NexposeEmailParser
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    view: |-
      {
        "position": {
          "x": 552,
          "y": 1081
        }
      }
  "7":
    id: "7"
    taskid: cfb8b77c-fa54-4792-834e-6f3b9d4e278a
    type: condition
    task:
      id: cfb8b77c-fa54-4792-834e-6f3b9d4e278a
      version: 1
      name: Is this a SentinelOne email
      scriptName: Set
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    scriptarguments:
      key: incident.labels.Email/from
      value: set-to-sentinelone-sender
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1255
        }
      }
  "8":
    id: "8"
    taskid: d7ea35bb-e794-4c1a-80d9-24137e2bd9db
    type: regular
    task:
      id: d7ea35bb-e794-4c1a-80d9-24137e2bd9db
      version: 6
      name: Set incident type and playbook to SentinelOne
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      addLabels: ""
      customFieldName: ""
      customFieldValue: ""
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: ""
      stage: ""
      type: set-to-sentinelone-type
      updatePlaybookForType: "yes"
    view: |-
      {
        "position": {
          "x": 542.5,
          "y": 1428
        }
      }
  "9":
    id: "9"
    taskid: cf75ade9-a303-4814-8d99-6ec9d09fbc02
    type: regular
    task:
      id: cf75ade9-a303-4814-8d99-6ec9d09fbc02
      version: 12
      name: Set type and playbook to Phishing (default type for emails)
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      addLabels: ""
      customFieldName: ""
      customFieldValue: ""
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: ""
      stage: ""
      type: Phishing
      updatePlaybookForType: "yes"
    view: |-
      {
        "position": {
          "x": 53,
          "y": 1620
        }
      }
  "10":
    id: "10"
    taskid: f9de0883-2020-490e-85ed-fdfb66a2db87
    type: condition
    task:
      id: f9de0883-2020-490e-85ed-fdfb66a2db87
      version: 12
      name: Is this a malware incident
      description: Did it involve a malicious binary running in your environment?
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "11"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1919
        }
      }
  "11":
    id: "11"
    taskid: c5d0e4fe-72db-40e2-8016-b86b944f2c9f
    type: regular
    task:
      id: c5d0e4fe-72db-40e2-8016-b86b944f2c9f
      version: 12
      name: SetIncidentType
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      type: Malware
    view: |-
      {
        "position": {
          "x": 413,
          "y": 2088
        }
      }
  "12":
    id: "12"
    taskid: 7b1823dd-b38e-4cd6-874d-87ede0be1f9e
    type: condition
    task:
      id: 7b1823dd-b38e-4cd6-874d-87ede0be1f9e
      version: 12
      name: Is this a phishing incident?
      description: Was this incident created because a suspected email was received?
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "13"
    view: |-
      {
        "position": {
          "x": 413,
          "y": 2353
        }
      }
  "13":
    id: "13"
    taskid: 66553f46-579a-42af-8c02-341af3445ba3
    type: regular
    task:
      id: 66553f46-579a-42af-8c02-341af3445ba3
      version: 12
      name: SetIncidentType
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      type: Phishing
    view: |-
      {
        "position": {
          "x": 598,
          "y": 2576
        }
      }
  "14":
    id: "14"
    taskid: 93f3f626-0b08-4257-8559-c2d3838cea13
    type: condition
    task:
      id: 93f3f626-0b08-4257-8559-c2d3838cea13
      version: 12
      name: Is the incident a C2 communication incident?
      description: Was the incident opened because communication to a known bad actor
        was detected?
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "15"
    view: |-
      {
        "position": {
          "x": 307,
          "y": 2797
        }
      }
  "15":
    id: "15"
    taskid: 070a2204-c59e-4c9c-88cf-95d5cd4a14ad
    type: regular
    task:
      id: 070a2204-c59e-4c9c-88cf-95d5cd4a14ad
      version: 12
      name: SetIncidentType
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      type: C2Communication
    view: |-
      {
        "position": {
          "x": 552,
          "y": 2965
        }
      }
  "16":
    id: "16"
    taskid: bd100974-58ce-4b53-8e32-c3930e215184
    type: condition
    task:
      id: bd100974-58ce-4b53-8e32-c3930e215184
      version: 12
      name: Is the incident a ransomware incident?
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "17"
    view: |-
      {
        "position": {
          "x": 305,
          "y": 3188
        }
      }
  "17":
    id: "17"
    taskid: 8a09e454-e0cc-4c4c-8b1b-77ccc402fabf
    type: regular
    task:
      id: 8a09e454-e0cc-4c4c-8b1b-77ccc402fabf
      version: 12
      name: SetIncidentType
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      type: Ransomware
    view: |-
      {
        "position": {
          "x": 626,
          "y": 3363
        }
      }
  "18":
    id: "18"
    taskid: 6cab1990-09da-4e94-8d26-7a67571a6303
    type: condition
    task:
      id: 6cab1990-09da-4e94-8d26-7a67571a6303
      version: 12
      name: Is the incident an unknown binary incident?
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "19"
    view: |-
      {
        "position": {
          "x": 307,
          "y": 3565
        }
      }
  "19":
    id: "19"
    taskid: bb222001-660e-418c-8849-25341bb74ddc
    type: regular
    task:
      id: bb222001-660e-418c-8849-25341bb74ddc
      version: 12
      name: SetIncidentType
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      type: UnknownBinary
    view: |-
      {
        "position": {
          "x": 664,
          "y": 3730
        }
      }
  "20":
    id: "20"
    taskid: b4f728f9-7690-49ec-8214-216cf28d83e1
    type: condition
    task:
      id: b4f728f9-7690-49ec-8214-216cf28d83e1
      version: 12
      name: Does the incident involve a lost or stolen device?
      issystemtask: true
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "21"
    view: |-
      {
        "position": {
          "x": 307,
          "y": 4027
        }
      }
  "21":
    id: "21"
    taskid: 3e019db0-5b05-45e4-86ca-c5944a9fdd48
    type: regular
    task:
      id: 3e019db0-5b05-45e4-86ca-c5944a9fdd48
      version: 12
      name: SetIncidentType
      scriptName: IncidentSet
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      type: DeviceLost
    view: |-
      {
        "position": {
          "x": 307,
          "y": 4313
        }
      }
  "22":
    id: "22"
    taskid: cedcbabe-7b14-4b7c-843d-60b04f66e9b2
    type: title
    task:
      id: cedcbabe-7b14-4b7c-843d-60b04f66e9b2
      version: 1
      name: Mail Classifier
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    view: |-
      {
        "position": {
          "x": -255,
          "y": 197
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 4364,
        "width": 1301,
        "x": -257,
        "y": 44
      }
    }
  }
