id: 2c56c928-58f2-4d5d-84f2-048146e8fbc9
version: 21
name: Packetsled
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b3bc6824-db01-4a5b-886e-04fc2d8263cf
    type: start
    task:
      id: b3bc6824-db01-4a5b-886e-04fc2d8263cf
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    view: |-
      {
        "position": {
          "x": 50,
          "y": -100
        }
      }
  "1":
    id: "1"
    taskid: ba93881a-fecf-44a4-8f06-ef1b2cefc29d
    type: regular
    task:
      id: ba93881a-fecf-44a4-8f06-ef1b2cefc29d
      version: -1
      name: packetsled-get-incidents
      description: Query for incidents by time range and severity
      script: Packetsled|||packetsled-get-incidents
      type: regular
      iscommand: true
      brand: Packetsled
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      envid: ""
      probe: ""
      severity: ""
      start_time: ""
      stop_time: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
  "2":
    id: "2"
    taskid: 77b29294-1227-4d74-8107-7e7a769b6552
    type: regular
    task:
      id: 77b29294-1227-4d74-8107-7e7a769b6552
      version: -1
      name: packetsled-get-files
      description: Query packetsled extracted files
      script: Packetsled|||packetsled-get-files
      type: regular
      iscommand: true
      brand: Packetsled
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      envid: ${packetsled.psincidents.envid}
      family: ""
      geo: ""
      host: ${packetsled.psincidents.host}
      incident: ${packetsled.psincidents}
      limit: ""
      log: psfile_analytics
      port: ""
      probe: ${packetsled.psincidents.probe}
      protocol: ""
      start_time: ${packetsled.psincidents.start_time}
      stop_time: ${packetsled.psincidents.stop_time}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
  "3":
    id: "3"
    taskid: 075fbbbf-38a0-4a7a-82db-b10e62e2ed64
    type: regular
    task:
      id: 075fbbbf-38a0-4a7a-82db-b10e62e2ed64
      version: -1
      name: packetsled-get-pcaps
      description: Query packetsled for full packet
      script: Packetsled|||packetsled-get-pcaps
      type: regular
      iscommand: true
      brand: Packetsled
    scriptarguments:
      envid: ${packetsled.psincidents.envid}
      host: ${packetsled.psincidents.host}
      limitbytes: ""
      limitpkts: ""
      port: ""
      probe: ${packetsled.psincidents.probe}
      protocol: ""
      start_time: ${packetsled.psincidents.start_time}
      stop_time: ${packetsled.psincidents.stop_time}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 750
        }
      }
  "4":
    id: "4"
    taskid: 712a6b8d-29d5-495a-8ac0-f2963771e337
    type: regular
    task:
      id: 712a6b8d-29d5-495a-8ac0-f2963771e337
      version: -1
      name: packetsled-get-flows
      description: Query packetsled sensor metadata
      script: Packetsled|||packetsled-get-flows
      type: regular
      iscommand: true
      brand: Packetsled
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      envid: ${packetsled.psincidents.envid}
      family: ""
      geo: ""
      host: ${packetsled.psincidents.host}
      limit: ""
      log: ""
      port: ""
      probe: ${packetsled.psincidents.probe}
      protocol: ""
      start_time: ${packetsled.psincidents.start_time}
      stop_time: ${packetsled.psincidents.stop_time}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
  "6":
    id: "6"
    taskid: 10889c2c-285d-4f2f-8281-f6c05f5e3fea
    type: regular
    task:
      id: 10889c2c-285d-4f2f-8281-f6c05f5e3fea
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all: "yes"
      key: packetsled
    view: |-
      {
        "position": {
          "x": 50,
          "y": 43
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 945,
        "width": 380,
        "x": 50,
        "y": -100
      }
    }
  }
inputs: []
