id: Hunt for bad IOCs
version: -1
name: Hunt for bad IOCs
fromversion: 3.5.0
system: true
description: Assume that malicious IOCs are in the right place in the context and
  start hunting using available tools
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c485e19b-c83a-48e4-892c-8bd91e17ced2
    type: start
    task:
      id: c485e19b-c83a-48e4-892c-8bd91e17ced2
      version: -1
      description: ""
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 697,
          "y": 50
        }
      }
  "5":
    id: "5"
    taskid: f4b71101-7ae3-4ce8-87b7-10eeb13c1a79
    type: playbook
    task:
      id: f4b71101-7ae3-4ce8-87b7-10eeb13c1a79
      version: -1
      name: CrowdStrike Rapid IOC Hunting
      playbookId: playbook16
      playbookName: CrowdStrike Rapid IOC Hunting
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      MD5Hash:
        complex:
          root: inputs
          accessor: MD5Hash
      SHA1Hash:
        complex:
          root: inputs
          accessor: SHA1Hash
      SHA256Hash:
        complex:
          root: inputs
          accessor: SHA256Hash
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 60,
          "y": 604
        }
      }
  "7":
    id: "7"
    taskid: 9f3311f1-fd41-4b15-8537-53495b0f6cef
    type: playbook
    task:
      id: 9f3311f1-fd41-4b15-8537-53495b0f6cef
      version: -1
      name: Carbon Black Rapid IOC Hunting
      playbookId: Carbon Black Rapid IOC Hunting
      playbookName: Carbon Black Rapid IOC Hunting
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      Hash:
        complex:
          root: inputs
          accessor: MD5Hash
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1229,
          "y": 604
        }
      }
  "8":
    id: "8"
    taskid: 89429b18-8ecd-4b23-86c0-30a33afd22b9
    type: playbook
    task:
      id: 89429b18-8ecd-4b23-86c0-30a33afd22b9
      version: -1
      name: Carbon black Protection Rapid IOC Hunting
      playbookId: playbook17
      playbookName: Carbon black Protection Rapid IOC Hunting
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      Hash:
        complex:
          root: inputs
          accessor: MD5Hash
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1643,
          "y": 604
        }
      }
  "9":
    id: "9"
    taskid: 9510dbd8-98c3-4611-802f-333acf31875b
    type: title
    task:
      id: 9510dbd8-98c3-4611-802f-333acf31875b
      version: -1
      name: MD5 Only
      type: title
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1148,
          "y": 184
        }
      }
  "10":
    id: "10"
    taskid: ce67117f-133a-4da3-84be-14e4a831756a
    type: title
    task:
      id: ce67117f-133a-4da3-84be-14e4a831756a
      version: -1
      name: MD5 / SHA1 / SHA256
      type: title
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 184
        }
      }
  "11":
    id: "11"
    taskid: 5c43d38d-83e0-46d2-8e1b-cb059f73612e
    type: condition
    task:
      id: 5c43d38d-83e0-46d2-8e1b-cb059f73612e
      version: -1
      name: Is MD5 hash?
      description: Is MD5 hash?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "7"
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: MD5Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1148,
          "y": 309
        }
      }
  "12":
    id: "12"
    taskid: f2a05482-2b17-4a09-8813-be48459935c3
    type: title
    task:
      id: f2a05482-2b17-4a09-8813-be48459935c3
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 697,
          "y": 884
        }
      }
  "13":
    id: "13"
    taskid: 5930cd65-e812-4ac7-8976-660487fdea01
    type: playbook
    task:
      id: 5930cd65-e812-4ac7-8976-660487fdea01
      version: -1
      name: TIE - IOC Hunt
      playbookId: TIE - IOC Hunt
      playbookName: TIE - IOC Hunt
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 498,
          "y": 604
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "11_12_#default#": 0.2,
      "11_7_yes": 0.5,
      "11_8_yes": 0.77
    },
    "paper": {
      "dimensions": {
        "height": 899,
        "width": 1963,
        "x": 60,
        "y": 50
      }
    }
  }
inputs:
- key: MD5Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: MD5 Hash
- key: SHA1Hash
  value:
    complex:
      root: File
      accessor: SHA1
  required: false
  description: SHA1 Hash
- key: SHA256Hash
  value:
    complex:
      root: File
      accessor: SHA256
  required: false
  description: SHA256 Hash
outputs:
- contextPath: FalconHostDevices
  description: Device IDs found by device IOC search
  type: string
- contextPath: File.References.AgentGuid
  description: The GUID of the system that referenced the file
  type: string
- contextPath: Endpoint.Hostname
  description: Hostname
  type: string
- contextPath: found_file_locations
  description: Found file locations
  type: string
- contextPath: found_hashes
  description: Found hashes
  type: string
releaseNotes: "-"