id: playbook6
version: -1
system: true
fromversion: 2.5.0
name: Protectwise Demo Playbook
description: Displays information for all events since 2016-06-17 and all observations
  since 2016-08-15, and downloads all related PCAPs. Waits 5 minutes between each
  10 observation PCAPs downloaded to stay within the ProtectWise default request rate
  limit .
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 05568fd1-7237-4cd0-8c09-afd6ea379404
    type: start
    task:
      id: 05568fd1-7237-4cd0-8c09-afd6ea379404
      version: -1
      name: start_task
      type: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 14dd4695-41d2-454a-8d7c-f34141c06515
    type: regular
    task:
      id: 14dd4695-41d2-454a-8d7c-f34141c06515
      version: -1
      name: PWSensors
      scriptName: PWSensors
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      sensorId: "1985"
    results:
    - pwsensors
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 21ad611d-0cb2-47cc-8cb4-0cba4c3efe16
    type: regular
    task:
      id: 21ad611d-0cb2-47cc-8cb4-0cba4c3efe16
      version: -1
      name: PWEvents
      scriptName: PWEvents
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      end: ""
      eventType: ""
      expandDetails: ""
      ip: ""
      killChainStage: ""
      maxLimit: ""
      minLimit: ""
      nextPage: ""
      observationStage: ""
      reverseOrder: ""
      start: 2016-06-17
      threatCategory: ""
      threatLevel: ""
    results:
    - pwevents
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    id: "4"
    taskid: bfd8cc23-fd89-48f3-880e-f1413937b612
    type: regular
    task:
      id: bfd8cc23-fd89-48f3-880e-f1413937b612
      version: -1
      name: PWEventPcapInfo
      scriptName: PWEventPcapInfo
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      eventId: ${pwevents}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    id: "5"
    taskid: 94419891-a100-4ee6-8ac6-674f6dee2619
    type: regular
    task:
      id: 94419891-a100-4ee6-8ac6-674f6dee2619
      version: -1
      name: PWEventPcapDownload
      description: Waits around 5 minutes every 10 files
      scriptName: PWEventPcapDownload
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      burstsize: "10"
      eventId: ${pwevents}
      filename: ""
      waitms: "310000"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "6":
    id: "6"
    taskid: c223a464-ea5b-4404-812e-d8d23509aa47
    type: regular
    task:
      id: c223a464-ea5b-4404-812e-d8d23509aa47
      version: -1
      name: PWObservations
      scriptName: PWObservations
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      end: ""
      expandDetails: ""
      hasKillChain: ""
      ip: ""
      killChainStage: ""
      maxLimit: ""
      minLimit: ""
      nextPage: ""
      reverseOrder: ""
      sensorId: ${pwsensors}
      signatureId: ""
      start: 2016-08-15
      threatCategory: ""
      threatLevel: ""
      type: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    id: "7"
    taskid: dc1a1307-cf45-4ae2-83c7-35176079d6e6
    type: regular
    task:
      id: dc1a1307-cf45-4ae2-83c7-35176079d6e6
      version: -1
      name: PWObservationPcapInfo
      scriptName: PWObservationPcapInfo
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      id: ${pwobservations}
      sensorId: ${pwsensors}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "8":
    id: "8"
    taskid: 05cb4857-2411-4af9-8069-16b5b1bbd93a
    type: regular
    task:
      id: 05cb4857-2411-4af9-8069-16b5b1bbd93a
      version: -1
      name: PWObservationPcapDownload
      description: Waits around 5 minutes every 10 files
      scriptName: PWObservationPcapDownload
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      burstsize: "10"
      filename: ""
      id: ${pwobservations}
      sensorId: ${pwsensors}
      waitms: "310000"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "9":
    id: "9"
    taskid: d91a8bac-6a6f-4194-848c-bac3447787f2
    type: regular
    task:
      id: d91a8bac-6a6f-4194-848c-bac3447787f2
      version: -1
      name: PrintContext
      scriptName: PrintContext
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "10":
    id: "10"
    taskid: 231e2da6-02d2-4d40-8a3c-44a4d6733a40
    type: regular
    task:
      id: 231e2da6-02d2-4d40-8a3c-44a4d6733a40
      version: -1
      name: CloseInvestigation
      scriptName: CloseInvestigation
      iscommand: false
      brand: ""
    scriptarguments:
      reason: Finished
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
