id: search_endpoints_by_hash_-_carbon_black_protection
fromversion: 3.5.0
system: true
version: -1
name: Search Endpoints By Hash - Carbon Black Protection
description: Hunt for endpoint activity involving hash IOCs, using Carbon Black Protection.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9b42ebf8-2133-4457-83ed-1d281ed7887f
    type: start
    task:
      id: 9b42ebf8-2133-4457-83ed-1d281ed7887f
      version: -1
      name: start_task
      description: ""
      type: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
  "8":
    id: "8"
    taskid: 0891cd8c-8331-42ee-80d8-ec78652b7ad2
    type: regular
    task:
      id: 0891cd8c-8331-42ee-80d8-ec78652b7ad2
      version: -1
      name: Search hashes in the file catalog
      description: Searching The file catalog for the hashes
      scriptName: CBPCatalogFindHash
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      extend-context:
        simple: ComputerId=computerId
      md5:
        complex:
          root: inputs.Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -197,
          "y": 573
        }
      }
  "9":
    id: "9"
    taskid: 255f2625-68d4-4475-81a2-663da89a39d6
    type: regular
    task:
      id: 255f2625-68d4-4475-81a2-663da89a39d6
      version: -1
      name: Check if the hashes are included in any rules
      description: If the hashes have been approved or blocked in the past, they will
        be in existing rules. It is useful to see whether the hash was in some blacklist
        or whitelist or a person marked them as such, possibly with a comment explaining
        their reasons.
      scriptName: CBPFindRule
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      extend-context:
        simple: ComputerId=computerId
      hash:
        complex:
          root: inputs.Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -197,
          "y": 745
        }
      }
  "10":
    id: "10"
    taskid: e499031a-b17c-4c20-8e8d-2747e29d329d
    type: condition
    task:
      id: e499031a-b17c-4c20-8e8d-2747e29d329d
      version: -1
      name: Is Carbon Black Protection enabled?
      description: Is Carbon Black Protection enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "12"
    scriptarguments:
      value:
        simple: ${modules(val.brand == 'carbonblackprotection' && val.state == 'active')}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: carbonblackprotection
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
  "11":
    id: "11"
    taskid: e5069a6c-2c37-4f0d-8a7b-571fdd1aa9ac
    type: title
    task:
      id: e5069a6c-2c37-4f0d-8a7b-571fdd1aa9ac
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 253,
          "y": 1316
        }
      }
  "12":
    id: "12"
    taskid: 57f5bcda-24a1-4387-8566-94fa8eed1155
    type: condition
    task:
      id: 57f5bcda-24a1-4387-8566-94fa8eed1155
      version: -1
      name: Do we have files to hunt?
      description: Do we have files to hunt?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "8"
    scriptarguments:
      value:
        simple: ${File.MD5}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs.Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": -50,
          "y": 380
        }
      }
  "13":
    id: "13"
    taskid: 0174e70d-e14f-47cc-8c65-0b36c142ae52
    type: regular
    task:
      id: 0174e70d-e14f-47cc-8c65-0b36c142ae52
      version: -1
      name: Get hostname and workgroup
      description: Get hostname and workgroup
      script: carbonblackprotection|||cbp-computer-get
      type: regular
      iscommand: true
      brand: carbonblackprotection
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      extend-context: {}
      headers: {}
      id:
        complex:
          root: ComputerId
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -197,
          "y": 928
        }
      }
  "14":
    id: "14"
    taskid: accc2606-97d8-45e7-8382-8fa3a8799240
    type: regular
    task:
      id: accc2606-97d8-45e7-8382-8fa3a8799240
      version: -1
      name: Get hostname
      description: Get hostname
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      append: {}
      key:
        simple: Endpoint.Hostname
      value:
        complex:
          root: Endpoint
          accessor: Hostname
          transformers:
          - operator: string.replaceMatch
            args:
              regex:
                value:
                  simple: .*\\(.*)
              replaceWith:
                value:
                  simple: $1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -197,
          "y": 1107
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "10_11_#default#": 0.36,
      "12_11_#default#": 0.32
    },
    "paper": {
      "dimensions": {
        "height": 1331,
        "width": 852,
        "x": -197,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: The MD5 Hash to hunt for
outputs:
- contextPath: Endpoint.Hostname
  description: The device hostname
  type: string
- contextPath: Endpoint
  description: The endpoint
  type: unknown
