id: 2c56c928-58f2-4d5d-84f2-048146e8fbc9
version: 37
name: Packetsled
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b3bc6824-db01-4a5b-886e-04fc2d8263cf
    type: start
    task:
      id: b3bc6824-db01-4a5b-886e-04fc2d8263cf
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    view: |-
      {
        "position": {
          "x": 50,
          "y": -148
        }
      }
  "8":
    id: "8"
    taskid: 143874b2-445d-4503-8378-604d8d067c6a
    type: regular
    task:
      id: 143874b2-445d-4503-8378-604d8d067c6a
      version: -1
      name: packetsled-get-files
      description: Query packetsled extracted files
      script: Packetsled|||packetsled-get-files
      type: regular
      iscommand: true
      brand: Packetsled
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      envid: ""
      family: ""
      geo: ""
      host: ""
      incident: ${packetsled.psincidents}
      limit: ""
      log: ""
      port: ""
      probe: ""
      protocol: ""
      start_time: ""
      stop_time: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 403
        }
      }
  "9":
    id: "9"
    taskid: 0daf0c6e-be7a-4410-83de-14480e60675e
    type: regular
    task:
      id: 0daf0c6e-be7a-4410-83de-14480e60675e
      version: -1
      name: packetsled-get-pcaps
      description: Query packetsled for full packet
      script: Packetsled|||packetsled-get-pcaps
      type: regular
      iscommand: true
      brand: Packetsled
    scriptarguments:
      envid: ""
      host: ""
      incident: ${packetsled.psincidents}
      limitbytes: ""
      limitpkts: ""
      port: ""
      probe: ""
      protocol: ""
      start_time: ""
      stop_time: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 583
        }
      }
  "10":
    id: "10"
    taskid: 651c5caa-7be7-4a2d-89eb-7aa8e3ab9236
    type: regular
    task:
      id: 651c5caa-7be7-4a2d-89eb-7aa8e3ab9236
      version: -1
      name: packetsled-get-incidents
      description: Query for incidents by time range and severity
      script: Packetsled|||packetsled-get-incidents
      type: regular
      iscommand: true
      brand: Packetsled
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      envid: ""
      probe: ""
      severity: ""
      start_time: ""
      stop_time: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 33
        }
      }
  "12":
    id: "12"
    taskid: 63eb8d6b-f462-4db5-8e8f-876dcfa90030
    type: regular
    task:
      id: 63eb8d6b-f462-4db5-8e8f-876dcfa90030
      version: -1
      name: packetsled-get-flows
      description: Query packetsled sensor metadata
      script: Packetsled|||packetsled-get-flows
      type: regular
      iscommand: true
      brand: Packetsled
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      envid: ""
      family: ""
      geo: ""
      host: ""
      incident: ${packetsled.psincidents}
      limit: ""
      log: ""
      port: ""
      probe: ""
      protocol: ""
      start_time: ""
      stop_time: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 214
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 826,
        "width": 380,
        "x": 50,
        "y": -148
      }
    }
  }
inputs: []
