id: playbook0
version: -1
name: Default
description: Default playbook to help classify incoming incidents
system: true
fromversion: 2.5.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 96dbf98e-bc4e-4d21-808f-54cf03241207
    type: start
    task:
      id: 96dbf98e-bc4e-4d21-808f-54cf03241207
      version: -1
      name: start_task
      type: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 6a0aef28-d546-47af-8947-99f46d77d48a
    type: condition
    task:
      id: 6a0aef28-d546-47af-8947-99f46d77d48a
      version: -1
      name: Is this an email
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "34"
      "yes":
      - "22"
    scriptarguments:
      key: Label/Email/from
      value: ${incident.labels.Email/from}
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 195
        }
      }
  "4":
    id: "4"
    taskid: 610f12ea-ce4f-444c-8dfe-3a4ffb6df6f9
    type: regular
    task:
      id: 610f12ea-ce4f-444c-8dfe-3a4ffb6df6f9
      version: -1
      name: SplunkEmailParser
      scriptName: SplunkEmailParser
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    scriptarguments:
      body: ${incident.labels.Email/html}
      subject: ${incident.labels.Email/subject}
    view: |-
      {
        "position": {
          "x": 910,
          "y": 865
        }
      }
  "6":
    id: "6"
    taskid: cda168ea-c74d-40b4-89cb-67014f85409d
    type: regular
    task:
      id: cda168ea-c74d-40b4-89cb-67014f85409d
      version: -1
      name: NexposeEmailParser
      scriptName: NexposeEmailParser
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "8":
    id: "8"
    taskid: d7ea35bb-e794-4c1a-80d9-24137e2bd9db
    type: regular
    task:
      id: d7ea35bb-e794-4c1a-80d9-24137e2bd9db
      version: -1
      name: Set incident type and playbook to SentinelOne
      scriptName: IncidentSet
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    scriptarguments:
      addLabels: ""
      customFieldName: ""
      customFieldValue: ""
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: ""
      stage: ""
      type: set-to-sentinelone-type
      updatePlaybookForType: "yes"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 865
        }
      }
  "9":
    id: "9"
    taskid: cf75ade9-a303-4814-8d99-6ec9d09fbc02
    type: regular
    task:
      id: cf75ade9-a303-4814-8d99-6ec9d09fbc02
      version: -1
      name: Set type and playbook to Phishing (default type for emails)
      scriptName: IncidentSet
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      addLabels: ""
      customFieldName: ""
      customFieldValue: ""
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: ""
      stage: ""
      type: Phishing
      updatePlaybookForType: "yes"
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 865
        }
      }
  "22":
    id: "22"
    taskid: cedcbabe-7b14-4b7c-843d-60b04f66e9b2
    type: title
    task:
      id: cedcbabe-7b14-4b7c-843d-60b04f66e9b2
      version: -1
      name: Mail Classifier
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "33"
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "23":
    id: "23"
    taskid: 40ab3f30-8252-4f50-8aec-dbcd2f85a1ec
    type: title
    task:
      id: 40ab3f30-8252-4f50-8aec-dbcd2f85a1ec
      version: -1
      name: Classify by Brand
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    view: |-
      {
        "position": {
          "x": 2127.5,
          "y": 545
        }
      }
  "26":
    id: "26"
    taskid: f2869c16-1168-482c-87b1-3740a0d6c0a9
    type: regular
    task:
      id: f2869c16-1168-482c-87b1-3740a0d6c0a9
      version: -1
      name: QRadar Classifier
      scriptName: QRadarClassifier
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    scriptarguments:
      contextOutput: ${inputs.ClassifierContext}
      customCategories: ${inputs.CustomCategories}
    view: |-
      {
        "position": {
          "x": 2670,
          "y": 865
        }
      }
  "27":
    id: "27"
    taskid: 8bf6dc34-f9e0-4502-829a-995cd5c7332f
    type: condition
    task:
      id: 8bf6dc34-f9e0-4502-829a-995cd5c7332f
      version: -1
      name: Get Brand
      description: Prints text to war room
      scriptName: Print
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "35"
      QRadar:
      - "26"
      Trend Micro:
      - "29"
      Vectra:
      - "28"
    scriptarguments:
      value: ${incident.labels.Brand}
    view: |-
      {
        "position": {
          "x": 2127.5,
          "y": 690
        }
      }
  "28":
    id: "28"
    taskid: a4bf35f1-1ba6-41cf-8ecf-963e4342abff
    type: regular
    task:
      id: a4bf35f1-1ba6-41cf-8ecf-963e4342abff
      version: -1
      name: 'Vectra Classifier '
      scriptName: VectraClassifier
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    view: |-
      {
        "position": {
          "x": 2240,
          "y": 865
        }
      }
  "29":
    id: "29"
    taskid: 37ef2cf4-f0f1-4f02-8083-c8e9355c3eb7
    type: regular
    task:
      id: 37ef2cf4-f0f1-4f02-8083-c8e9355c3eb7
      version: -1
      name: Trendmicro Classifier
      scriptName: TrendMicroClassifier
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    view: |-
      {
        "position": {
          "x": 1790,
          "y": 865
        }
      }
  "30":
    id: "30"
    taskid: e3e6429a-96e9-4e6a-8fe2-2882c8033ba4
    type: regular
    task:
      id: e3e6429a-96e9-4e6a-8fe2-2882c8033ba4
      version: -1
      name: Manually decide playbook
      description: Could not decide incident type automatically, please set playbook
        Manually
      type: regular
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 1677.5,
          "y": 1215
        }
      }
  "33":
    id: "33"
    taskid: 2f7ec274-84aa-4e36-80a7-bb7aa32e5560
    type: condition
    task:
      id: 2f7ec274-84aa-4e36-80a7-bb7aa32e5560
      version: -1
      name: Get Email Sender
      description: Prints text to war room
      scriptName: MapValues
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      nexpose:
      - "6"
      sentinel:
      - "8"
      splunk:
      - "4"
    scriptarguments:
      input: ${incident.labels.Email/from}
      translated: splunk,sentinel,nexpose
      values: ${inputs.SplunkSender},${inputs.SentinelSender},${inputs.NexposeSender}
    view: |-
      {
        "position": {
          "x": 695,
          "y": 690
        }
      }
  "34":
    id: "34"
    taskid: 5ae67300-d763-4671-8f0c-78a34bb2bb41
    type: condition
    task:
      id: 5ae67300-d763-4671-8f0c-78a34bb2bb41
      version: -1
      name: Does incident include "Brand" label?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "35"
      "yes":
      - "23"
    scriptarguments:
      value: ${incident.labels.Brand}
    view: |-
      {
        "position": {
          "x": 1902.5,
          "y": 370
        }
      }
  "35":
    id: "35"
    taskid: 5db2091c-bd4b-4827-8318-e26fa57e938c
    type: playbook
    task:
      id: 5db2091c-bd4b-4827-8318-e26fa57e938c
      version: -1
      name: ""
      playbookName: Enrichment Playbook
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "30"
    view: |-
      {
        "position": {
          "x": 1677.5,
          "y": 1040
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "2_34_#default#": 0.62,
      "33_9_#default#": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 3000,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: SplunkSender
  value: splunk@placeholder.com
  description: If your splunk sends incidents via email, what is the sender email
    address?
- key: NexposeSender
  value: nexpose@placeholder.com
  description: If Nexpose sends incidents via email, what is the sender email address?
- key: SentinelSender
  value: sentinel@placeholder.com
  description: If Sentinel sends incidents via email, what is the sender email address?
- key: ClassifierContext
  value: Classifier/Description
  description: This context key will contain the description of the incident properties
    that we tried to classify
- key: CustomCategories
  value: ""
  description: 'Option to add custom categories to the classifier, JSON with SIEM
    categories and their Demisto type counterparts. i.e {"SIEMCategory1": "DemistoType1",
    "SIEMCategory2": "DemistoType2"}'
