id: TIE - IOC Hunt
version: -1
name: IOC Hunt - TIE
description: |-
  Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

  Input:
  * Hash (default, takes all deferent hashes from context)

  Output:
  * All agents that files with "Hash" has been executed on (TIE)
  * Enrich Agents info from ePO
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 9329911b-7aca-4410-8284-205fd24ea39e
    type: start
    task:
      id: 9329911b-7aca-4410-8284-205fd24ea39e
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 0695daf1-5803-4724-8e17-8e2bbc2adf29
    type: condition
    task:
      id: 0695daf1-5803-4724-8e17-8e2bbc2adf29
      version: -1
      name: Is TIE enabled?
      description: Is the integration configured & active?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: McAfee Threat Intelligence Exchange
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
  "2":
    id: "2"
    taskid: 09abeae0-3dc7-41c9-8166-b8e521132f55
    type: condition
    task:
      id: 09abeae0-3dc7-41c9-8166-b8e521132f55
      version: -1
      name: Is ePO enabled?
      description: Is ePo configured and active?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "6"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: epo
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1094
        }
      }
  "3":
    id: "3"
    taskid: 8dc9e4ab-26a5-463d-8be1-71213904e386
    type: regular
    task:
      id: 8dc9e4ab-26a5-463d-8be1-71213904e386
      version: -1
      name: List all agents that the Hash has been executed on
      description: get all Agent Guids for these hashes
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      iscommand: true
      brand: McAfee Threat Intelligence Exchange
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      file:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 518
        }
      }
  "4":
    id: "4"
    taskid: ac91afe9-aabf-48fb-89d3-bac2afaa5b4e
    type: title
    task:
      id: ac91afe9-aabf-48fb-89d3-bac2afaa5b4e
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 135,
          "y": 1492
        }
      }
  "5":
    id: "5"
    taskid: cf4100ee-5833-4bd5-8c90-a346b84d074c
    type: condition
    task:
      id: cf4100ee-5833-4bd5-8c90-a346b84d074c
      version: -1
      name: Did we find any relevant agents?
      description: Did any Guids return?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "8"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: File
          accessor: References.AgentGuid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 703
        }
      }
  "6":
    id: "6"
    taskid: e033cd87-9df6-45af-8147-1b55ada8f19f
    type: regular
    task:
      id: e033cd87-9df6-45af-8147-1b55ada8f19f
      version: -1
      name: Get Agent info from ePO
      description: Get hostnames for the Guids
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        complex:
          root: File
          accessor: References.AgentGuid
      taskID: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1325
        }
      }
  "7":
    id: "7"
    taskid: 353a94d6-2b5e-405d-8620-e08f4704a1cc
    type: title
    task:
      id: 353a94d6-2b5e-405d-8620-e08f4704a1cc
      version: -1
      name: Hunt HASH in TIE
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "8":
    id: "8"
    taskid: 394ab728-5dfe-4cb8-88e1-1cfc81374e18
    type: title
    task:
      id: 394ab728-5dfe-4cb8-88e1-1cfc81374e18
      version: -1
      name: Enrich in ePO
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 956
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "1_4_#default#": 0.1,
      "2_4_#default#": 0.17,
      "5_4_#default#": 0.11
    },
    "paper": {
      "dimensions": {
        "height": 1507,
        "width": 675,
        "x": 135,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
      b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
  required: false
  description: |-
    The Hash to hunt (Could be MD5,SHA1,SHA256).
    Default is set to all hashes
outputs:
- contextPath: File.References.AgentGuid
  description: The GUID of the system that referenced the file
  type: string
- contextPath: Endpoint.Hostname
  description: Hostname
  type: string
releaseNotes: "-"