id: playbook15
version: -1
name: Tanium Demo Playbook
description: This playbook shows how to use automation scripts to interact with Tanium.
fromVersion: 2.5.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 18219156-ab84-4e03-8a5d-eaf3f2b5d402
    type: start
    task:
      id: 18219156-ab84-4e03-8a5d-eaf3f2b5d402
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 54
        }
      }
  "2":
    id: "2"
    taskid: 5c3e4175-c3b9-4d99-83a2-03ac1d9dfff5
    type: regular
    task:
      id: 5c3e4175-c3b9-4d99-83a2-03ac1d9dfff5
      version: -1
      name: tn-ask-question
      description: Ask the server to parse the question text and choose the first
        parsed result as the question to run
      script: Tanium|||tn-ask-question
      type: regular
      iscommand: true
      brand: Tanium
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      question: ${Tanium.SavedQuestions.query_text}
    view: |-
      {
        "position": {
          "x": 450,
          "y": 669
        }
      }
  "3":
    id: "3"
    taskid: dbe92300-227f-4979-8a06-d5dc91deeb78
    type: regular
    task:
      id: dbe92300-227f-4979-8a06-d5dc91deeb78
      version: -1
      name: tn-ask-question
      description: Ask the server to parse the question text and choose the first
        parsed result as the question to run
      script: Tanium|||tn-ask-question
      type: regular
      iscommand: true
      brand: Tanium
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      question: Get all machines with processes starting with "EC"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 830
        }
      }
  "4":
    id: "4"
    taskid: 7161586d-f99d-4996-8824-de3e7f852baf
    type: regular
    task:
      id: 7161586d-f99d-4996-8824-de3e7f852baf
      version: -1
      name: tn-get-saved-question
      description: Get a saved question by name or id
      script: Tanium|||tn-get-saved-question
      type: regular
      iscommand: true
      brand: Tanium
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      id: ""
      name: Tanium Client Versions
    view: |-
      {
        "position": {
          "x": 450,
          "y": 338
        }
      }
  "6":
    id: "6"
    taskid: e66ed6a5-1d04-459c-82dc-d356008b0f0d
    type: regular
    task:
      id: e66ed6a5-1d04-459c-82dc-d356008b0f0d
      version: -1
      name: tn-get-saved-question
      description: Get a saved question by name or id
      script: Tanium|||tn-get-saved-question
      type: regular
      iscommand: true
      brand: Tanium
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      id: ""
      name: Running Applications
    view: |-
      {
        "position": {
          "x": 450,
          "y": 508
        }
      }
  "7":
    id: "7"
    taskid: 474a6415-eb35-4137-8977-c60db94ac520
    type: title
    task:
      id: 474a6415-eb35-4137-8977-c60db94ac520
      version: -1
      name: Querying Tanium
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 198
        }
      }
  "8":
    id: "8"
    taskid: c6202d75-3923-44df-86e6-a685195739c8
    type: title
    task:
      id: c6202d75-3923-44df-86e6-a685195739c8
      version: -1
      name: Deploying Actions
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 998
        }
      }
  "9":
    id: "9"
    taskid: 12031fc9-491e-43cb-807c-d869400e2f59
    type: regular
    task:
      id: 12031fc9-491e-43cb-807c-d869400e2f59
      version: -1
      name: tn-deploy-package
      description: Deploy a package and get the results back
      script: Tanium|||tn-deploy-package
      type: regular
      iscommand: true
      brand: Tanium
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      action_filters: ""
      action_options: ""
      get_results: ""
      package: USB Write Protect - Set to On
      package_args: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1152
        }
      }
  "10":
    id: "10"
    taskid: b34ca7a6-2cd0-4a2d-8f15-2c972b6c752f
    type: title
    task:
      id: b34ca7a6-2cd0-4a2d-8f15-2c972b6c752f
      version: -1
      name: Actions pending approval - Viewing and approving
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1337
        }
      }
  "11":
    id: "11"
    taskid: 602135ba-8444-45c6-8e24-a7e610c19206
    type: regular
    task:
      id: 602135ba-8444-45c6-8e24-a7e610c19206
      version: -1
      name: tn-approve-saved-action
      description: Approve saved actions
      script: Tanium|||tn-approve-saved-action
      type: regular
      iscommand: true
      brand: Tanium
    scriptarguments:
      action_id: ${Tanium.SavedActions.Id}
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1517
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1558,
        "width": 380,
        "x": 450,
        "y": 54
      }
    }
  }
inputs: []
