id: endpoint_enrichment_-_generic
version: -1
name: Endpoint Enrichment - Generic
fromversion: "3.5.0"
description: Enrich an Endpoint Hostname using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b2acb73e-f19b-4720-8e0e-03f4767aeae9
    type: start
    task:
      id: b2acb73e-f19b-4720-8e0e-03f4767aeae9
      version: -1
      description: ""
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: b88e8246-b819-4b0b-8ec0-efc1f2262656
    type: title
    task:
      id: b88e8246-b819-4b0b-8ec0-efc1f2262656
      version: -1
      description: ""
      name: Endpoint Products
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 370
        }
      }
  "2":
    id: "2"
    taskid: 4c4ac7b4-7259-442c-886d-462accd31438
    type: condition
    task:
      id: 4c4ac7b4-7259-442c-886d-462accd31438
      version: -1
      description: ""
      name: Is ePO enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: epo
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 660
        }
      }
  "3":
    id: "3"
    taskid: 67f9e78d-54ed-4cda-86ef-cc4993634602
    type: condition
    task:
      id: 67f9e78d-54ed-4cda-86ef-cc4993634602
      version: -1
      description: ""
      name: Is there an Endpoint Hostname to run on?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "24"
      - "1"
    scriptarguments:
      value:
        simple: ${inputs.Hostname}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              simple: inputs.Hostname
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "4":
    id: "4"
    taskid: 47694916-e14f-4d67-8ad5-09180a8b7af8
    type: title
    task:
      id: 47694916-e14f-4d67-8ad5-09180a8b7af8
      version: -1
      description: ""
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 1295
        }
      }
  "5":
    id: "5"
    taskid: 39035710-09b8-4b7c-867b-e9e70494dec4
    type: regular
    task:
      id: 39035710-09b8-4b7c-867b-e9e70494dec4
      version: -1
      name: Get host information from ePO
      description: 'ePO: Get host information'
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        simple: ${inputs.Hostname}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 906
        }
      }
  "6":
    id: "6"
    taskid: ffd40404-8b46-4d0d-809a-7814893b79aa
    type: condition
    task:
      id: ffd40404-8b46-4d0d-809a-7814893b79aa
      version: -1
      name: Is SentinelOne enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "7"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: sentinelOne
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 660
        }
      }
  "7":
    id: "7"
    taskid: cf334489-ab5a-40cc-86a4-55e1800e99fb
    type: regular
    task:
      id: cf334489-ab5a-40cc-86a4-55e1800e99fb
      version: -1
      name: Get host information from SentinelOne
      description: 'SentinelOne: Get host information'
      script: sentinelOne|||so-agents-query
      type: regular
      iscommand: true
      brand: sentinelOne
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 962.5,
          "y": 906
        }
      }
  "8":
    id: "8"
    taskid: 55bdf46d-73ee-4a16-8e02-75183006074e
    type: condition
    task:
      id: 55bdf46d-73ee-4a16-8e02-75183006074e
      version: -1
      name: Is Carbon Black Enterprise Response enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "9"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: carbonblack
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 660
        }
      }
  "9":
    id: "9"
    taskid: 414dafaf-bcb9-400c-87af-e1f8362bc8b1
    type: regular
    task:
      id: 414dafaf-bcb9-400c-87af-e1f8362bc8b1
      version: -1
      name: Get host information from Carbon Black Enterprise Response
      description: 'Carbon Black Enterprise Response: Get host information '
      script: carbonblack|||cb-sensor-info
      type: regular
      iscommand: true
      brand: carbonblack
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      groupid: {}
      hostname:
        simple: ${inputs.Hostname}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      ip: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      sensor: {}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 906
        }
      }
  "10":
    id: "10"
    taskid: 981c68a7-0ddf-4618-88db-ffebb297b5d9
    type: condition
    task:
      id: 981c68a7-0ddf-4618-88db-ffebb297b5d9
      version: -1
      name: Is CrowdStrike Falcon Host enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "25"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: FalconHost
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2300,
          "y": 660
        }
      }
  "14":
    id: "14"
    taskid: 536d3e49-6ee4-4f43-887c-4811bb372bf7
    type: condition
    task:
      id: 536d3e49-6ee4-4f43-887c-4811bb372bf7
      version: -1
      name: Is Cylance Protect enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "26"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: Cylance Protect
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 660
        }
      }
  "16":
    id: "16"
    taskid: 0de1f82b-b009-4851-8b21-879f20185b86
    type: title
    task:
      id: 0de1f82b-b009-4851-8b21-879f20185b86
      version: -1
      description: ""
      name: ePO
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 515
        }
      }
  "17":
    id: "17"
    taskid: e1f06a6e-589c-4ba5-855c-fb4ff8227502
    type: title
    task:
      id: e1f06a6e-589c-4ba5-855c-fb4ff8227502
      version: -1
      description: ""
      name: Sentinel One
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 515
        }
      }
  "18":
    id: "18"
    taskid: 425ed28d-6f1d-49dd-8fdf-80af51ea6dae
    type: title
    task:
      id: 425ed28d-6f1d-49dd-8fdf-80af51ea6dae
      version: -1
      description: ""
      name: Carbon Black Enterprise Response
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 515
        }
      }
  "19":
    id: "19"
    taskid: 6b426785-8b42-431d-825e-0a528371f322
    type: title
    task:
      id: 6b426785-8b42-431d-825e-0a528371f322
      version: -1
      description: ""
      name: Cylance Protect
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 515
        }
      }
  "20":
    id: "20"
    taskid: 0536265f-61ec-4c76-8ebb-2cdb0cc1f35e
    type: title
    task:
      id: 0536265f-61ec-4c76-8ebb-2cdb0cc1f35e
      version: -1
      description: ""
      name: CrowdStrike Falcon Host
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2300,
          "y": 515
        }
      }
  "22":
    id: "22"
    taskid: 30ea0e89-9f55-43c2-80d9-72ef4a793082
    type: condition
    task:
      id: 30ea0e89-9f55-43c2-80d9-72ef4a793082
      version: -1
      name: Is Active Directory enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "23"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: activedir
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -226,
          "y": 660
        }
      }
  "23":
    id: "23"
    taskid: 2e3c4846-df71-4cbf-8e76-1ad007709902
    type: regular
    task:
      id: 2e3c4846-df71-4cbf-8e76-1ad007709902
      version: -1
      name: Get host information from Active Directory
      description: 'Active Directory: Get host information'
      scriptName: ADGetComputer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      headers: {}
      name:
        simple: ${inputs.Hostname}
      nestedSearch: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -15,
          "y": 906
        }
      }
  "24":
    id: "24"
    taskid: 9e893bcb-5daf-456a-80ae-786591c1f382
    type: title
    task:
      id: 9e893bcb-5daf-456a-80ae-786591c1f382
      version: -1
      description: ""
      name: Active Directory
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -226,
          "y": 503
        }
      }
  "25":
    id: "25"
    taskid: 48121c45-6c2e-497f-8f14-065f9058b42d
    type: playbook
    task:
      id: 48121c45-6c2e-497f-8f14-065f9058b42d
      version: -1
      description: ""
      name: CrowdStrike Endpoint Enrichment
      playbookName: CrowdStrike Endpoint Enrichment
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 2300,
          "y": 1052
        }
      }
  "26":
    id: "26"
    taskid: b0c0a905-5078-4c2e-8423-d846849425d1
    type: regular
    task:
      id: b0c0a905-5078-4c2e-8423-d846849425d1
      version: -1
      name: Get host information from Cylance Protect
      description: 'Cylance Protect: Get host information.'
      script: Cylance Protect|||cylance-protect-get-devices
      type: regular
      iscommand: true
      brand: Cylance Protect
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      filters:
        complex:
          root: inputs
          accessor: Hostname
          transformers:
          - operator: string.concat
            args:
              prefix: '[{"Field":"device_name","Operator":"IsEqualTo","Value":"'
              suffix: '"}]'
      headers: {}
      page_number: {}
      page_size: {}
      sorts: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1851,
          "y": 914
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1310,
        "width": 2906,
        "x": -226,
        "y": 50
      }
    }
  }
inputs:
- key: Hostname
  value:
    simple: ${Endpoint.Hostname}
  required: false
  description: The hostname to enrich
outputs:
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
