id: Carbon Black Rapid IOC Hunting
fromversion: 3.5.0
system: true
version: -1
name: Carbon Black Rapid IOC Hunting
description: Hunt for malicious indicators using Carbon Black
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: edc8b672-13e8-48fa-87c9-594118876ac4
    type: start
    task:
      id: edc8b672-13e8-48fa-87c9-594118876ac4
      version: -1
      name: ""
      description: Playbook start point
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 8522b27b-705f-4411-8612-aaf14ab1ef38
    type: regular
    task:
      id: 8522b27b-705f-4411-8612-aaf14ab1ef38
      version: -1
      name: CBFindHash
      description: Search Carbon Black for connection to specified md5 hash(es).
      scriptName: CBFindHash
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      md5:
        complex:
          root: inputs
          accessor: Hash
    results:
    - found_file_locations
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    id: "2"
    taskid: 6cc1eea9-726e-41f4-806a-0ed419347119
    type: condition
    task:
      id: 6cc1eea9-726e-41f4-806a-0ed419347119
      version: -1
      name: Is Carbon Black enabled?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${modules(val.brand == 'carbonblack' && val.state == 'active')}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: carbonblack
                accessor: brand
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 108ba97d-b9da-4162-808d-025b5f6b7986
    type: title
    task:
      id: 108ba97d-b9da-4162-808d-025b5f6b7986
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    id: "4"
    taskid: b9d04fe4-581a-43bf-8eee-0b7cb145c6ed
    type: condition
    task:
      id: b9d04fe4-581a-43bf-8eee-0b7cb145c6ed
      version: -1
      name: Do we have files to hunt?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    scriptarguments:
      value:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "2_3_#default#": 0.27
    },
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: MD5 Hash
outputs:
- contextPath: found_file_locations
  description: Found file locations
  type: string
- contextPath: found_hashes
  description: Found hashes
  type: string
releaseNotes: "-"