id: CrowdStrike Falcon Sandbox - Detonate file
version: -1
name: CrowdStrike Falcon Sandbox - Detonate file
description: Detonate file through CrowdStrike Falcon Sandbox
fromversion: "3.5.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 99639e9f-c42f-4241-849e-205318e76136
    type: start
    task:
      id: 99639e9f-c42f-4241-849e-205318e76136
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "4":
    id: "4"
    taskid: 74b3c9f2-12c2-4d14-8088-fcf09067c209
    type: regular
    task:
      id: 74b3c9f2-12c2-4d14-8088-fcf09067c209
      version: -1
      name: DetonateFile (CS Falcon Sandbox)
      description: Detonate the file in CS Falcon Sandbox.
      script: VxStream|||vx-detonate-file
      type: regular
      iscommand: true
      brand: VxStream
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      delay: {}
      entryId:
        simple: ${inputs.EntryID}
      environmentID: {}
      timeout: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    id: "5"
    taskid: 1b506876-b5d6-4890-84c1-98684630107c
    type: condition
    task:
      id: 1b506876-b5d6-4890-84c1-98684630107c
      version: -1
      name: Is CS Falcon Sandbox enabled?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "7"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: VxStream
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "6":
    id: "6"
    taskid: 54bc8e82-f709-4686-8a24-43b6cbe9986b
    type: title
    task:
      id: 54bc8e82-f709-4686-8a24-43b6cbe9986b
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "7":
    id: "7"
    taskid: 6b7fbff0-e88f-4977-8b2e-c29dc8c6033d
    type: condition
    task:
      id: 6b7fbff0-e88f-4977-8b2e-c29dc8c6033d
      version: -1
      name: Is there file to detonate?
      description: Checks if there is a file to detonate through CS Faclon Sandbox.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${inputs.EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -120,
          "y": 357
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 550,
        "x": -120,
        "y": 50
      }
    }
  }
inputs:
- key: EntryID
  value:
    simple: ${File.EntryID}
  required: false
  description: Entry ID of file to be detonated
outputs:
- contextPath: File.SHA256
  description: SHA256 of the file
  type: string
- contextPath: File.SHA1
  description: SHA1 of the file
  type: string
- contextPath: File.MD5
  description: MD5 of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
