id: 77dacbae-1595-41ef-81bf-a8405a8ecb7a
version: -1
name: Endpoint Enrichment - Generic
fromVersion: "3.5.0"
description: Enrich an Endpoint Hostname using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2aadae56-45ae-4e11-832a-f627bfd77f07
    type: start
    task:
      id: 2aadae56-45ae-4e11-832a-f627bfd77f07
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1962.5,
          "y": 48
        }
      }
  "1":
    id: "1"
    taskid: 57b61cf4-9764-4072-8397-2ef81ce7ad75
    type: title
    task:
      id: 57b61cf4-9764-4072-8397-2ef81ce7ad75
      version: -1
      name: Endpoint Products
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 515
        }
      }
  "2":
    id: "2"
    taskid: 0223a9a6-eaca-4b2d-8f99-1b89c2427074
    type: condition
    task:
      id: 0223a9a6-eaca-4b2d-8f99-1b89c2427074
      version: -1
      name: Is ePO enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: epo
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2085,
          "y": 1155
        }
      }
  "3":
    id: "3"
    taskid: d656ca90-8307-45d7-8854-a0052c2843be
    type: condition
    task:
      id: d656ca90-8307-45d7-8854-a0052c2843be
      version: -1
      name: Is there an Endpoint Hostname to run on?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "21"
    scriptarguments:
      value:
        simple: ${inputs.Hostname}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value: inputs.Hostname
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1962.5,
          "y": 195
        }
      }
  "4":
    id: "4"
    taskid: 291509d3-03b4-4b9a-8e8f-174f33903161
    type: title
    task:
      id: 291509d3-03b4-4b9a-8e8f-174f33903161
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1512.5,
          "y": 1505
        }
      }
  "5":
    id: "5"
    taskid: a7e8f084-8022-4135-8509-14aeaedced7e
    type: regular
    task:
      id: a7e8f084-8022-4135-8509-14aeaedced7e
      version: -1
      name: Get host info from ePO
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        simple: ${inputs.Hostname}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1972.5,
          "y": 1330
        }
      }
  "6":
    id: "6"
    taskid: 49215025-f200-45c8-8c30-f45832f29560
    type: condition
    task:
      id: 49215025-f200-45c8-8c30-f45832f29560
      version: -1
      name: Is SentinelOne enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "7"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: sentinelOne
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1155
        }
      }
  "7":
    id: "7"
    taskid: 74111b99-2ca2-4ecf-8616-14f90f466289
    type: regular
    task:
      id: 74111b99-2ca2-4ecf-8616-14f90f466289
      version: -1
      name: Get host info from SentinelOne
      script: sentinelOne|||so-agents-query
      type: regular
      iscommand: true
      brand: sentinelOne
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1330
        }
      }
  "8":
    id: "8"
    taskid: dffadc70-1144-4b0f-8f43-281ad8d2ffa7
    type: condition
    task:
      id: dffadc70-1144-4b0f-8f43-281ad8d2ffa7
      version: -1
      name: Is Carbon Black Enterprise Response enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "9"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: active
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 1155
        }
      }
  "9":
    id: "9"
    taskid: dd5f38b9-9d4c-4274-8806-443ba0925aa8
    type: regular
    task:
      id: dd5f38b9-9d4c-4274-8806-443ba0925aa8
      version: -1
      name: Get host info from Carbon Black Enterprise Response
      script: carbonblack|||cb-sensor-info
      type: regular
      iscommand: true
      brand: carbonblack
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      groupid: {}
      hostname:
        simple: ${inputs.Hostname}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      ip: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      sensor: {}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1330
        }
      }
  "10":
    id: "10"
    taskid: 2a6519e7-447e-4cf1-878b-c45681908d95
    type: condition
    task:
      id: 2a6519e7-447e-4cf1-878b-c45681908d95
      version: -1
      name: Is CrowdStrike Falcon Host enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "11"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: FalconHost
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1625,
          "y": 805
        }
      }
  "11":
    id: "11"
    taskid: 9942861d-4f94-4c0a-85fd-823f27f6ddf4
    type: regular
    task:
      id: 9942861d-4f94-4c0a-85fd-823f27f6ddf4
      version: -1
      name: Get device ID
      script: FalconHost|||cs-device-search
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      extend-context: {}
      filter:
        simple: hostname:"${inputs.Hostname}"
      group_id: {}
      group_id__in: {}
      groupid: {}
      hostname:
        simple: ${inputs.Hostname}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      ip: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      offset: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      sensor: {}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1512.5,
          "y": 980
        }
      }
  "12":
    id: "12"
    taskid: 3f67b4b3-5452-4af5-81be-d8e21993cda1
    type: condition
    task:
      id: 3f67b4b3-5452-4af5-81be-d8e21993cda1
      version: -1
      name: Was a device ID found?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "13"
    scriptarguments:
      value:
        simple: ${FalconHostDevices}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value: FalconHostDevices
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1512.5,
          "y": 1155
        }
      }
  "13":
    id: "13"
    taskid: 8bd9842c-d9ca-48e4-8642-ca9dc9f6c7ce
    type: regular
    task:
      id: 8bd9842c-d9ca-48e4-8642-ca9dc9f6c7ce
      version: -1
      name: Get host info from CrowdStrike Falcon Host
      script: FalconHost|||cs-device-details
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1403,
          "y": 1330
        }
      }
  "14":
    id: "14"
    taskid: 7dd84e4a-1859-4227-894f-2aec51e94d1d
    type: condition
    task:
      id: 7dd84e4a-1859-4227-894f-2aec51e94d1d
      version: -1
      name: Is Cylance Protect enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "15"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: Cylance Protect
          - - operator: string.isEqual
              left:
                value: modules.state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 1155
        }
      }
  "15":
    id: "15"
    taskid: 11e910f4-5067-4bf9-8af8-9c59a1a8947f
    type: regular
    task:
      id: 11e910f4-5067-4bf9-8af8-9c59a1a8947f
      version: -1
      name: Get host info from Cylance Protect
      script: Cylance Protect|||cylance-protect-get-devices
      type: regular
      iscommand: true
      brand: Cylance Protect
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      filters:
        simple: '[{"Field":"device_name","Operator":"IsEqualTo","Value":"${inputs.Hostname}"}]'
      headers: {}
      page_number: {}
      page_size: {}
      searchText:
        simple: ${inputs.Hostname}
      sorts: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 1330
        }
      }
  "16":
    id: "16"
    taskid: 86053c92-99d8-4b79-8b6d-0185e050f730
    type: title
    task:
      id: 86053c92-99d8-4b79-8b6d-0185e050f730
      version: -1
      name: ePO
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2085,
          "y": 995
        }
      }
  "17":
    id: "17"
    taskid: e1c09b5f-a35f-49a6-8199-d3df1031612f
    type: title
    task:
      id: e1c09b5f-a35f-49a6-8199-d3df1031612f
      version: -1
      name: Sentinel One
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 995
        }
      }
  "18":
    id: "18"
    taskid: eda63af2-7cf1-4069-812a-67f60a9c2dfa
    type: title
    task:
      id: eda63af2-7cf1-4069-812a-67f60a9c2dfa
      version: -1
      name: Carbon Black Enterprise Response
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 995
        }
      }
  "19":
    id: "19"
    taskid: 17990776-9803-4d5c-85fe-e7327e27ef51
    type: title
    task:
      id: 17990776-9803-4d5c-85fe-e7327e27ef51
      version: -1
      name: Cylance Protect
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 995
        }
      }
  "20":
    id: "20"
    taskid: 10af1189-7397-4173-813e-9cc0efa2abdb
    type: title
    task:
      id: 10af1189-7397-4173-813e-9cc0efa2abdb
      version: -1
      name: CrowdStrike Falcon Host
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1625,
          "y": 660
        }
      }
  "21":
    id: "21"
    taskid: ed808cd8-4465-41b6-82d2-540c81f03f0e
    type: title
    task:
      id: ed808cd8-4465-41b6-82d2-540c81f03f0e
      version: -1
      name: Enrich Endpoint by Hostname
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 370
        }
      }
  "22":
    id: "22"
    taskid: 7a7dcd9a-ee50-4154-8421-62333f636178
    type: condition
    task:
      id: 7a7dcd9a-ee50-4154-8421-62333f636178
      version: -1
      name: Is Active Directory enabled?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "23"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: activedir
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2535,
          "y": 1155
        }
      }
  "23":
    id: "23"
    taskid: 372efbf5-d3e1-4a40-85ab-6c00cb154cdf
    type: regular
    task:
      id: 372efbf5-d3e1-4a40-85ab-6c00cb154cdf
      version: -1
      name: Get host info from Active Directory
      scriptName: ADGetComputer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      headers: {}
      name:
        simple: ${inputs.Hostname}
      nestedSearch: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2422.5,
          "y": 1330
        }
      }
  "24":
    id: "24"
    taskid: 7d07aa94-b375-4088-836b-b1b2e453c12d
    type: title
    task:
      id: 7d07aa94-b375-4088-836b-b1b2e453c12d
      version: -1
      name: Active Directory
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2535,
          "y": 995
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1522,
        "width": 2865,
        "x": 50,
        "y": 48
      }
    }
  }
inputs:
- key: Hostname
  value:
    simple: ${Endpoint.Hostname}
  required: false
  description: The hostname to enrich
outputs:
- contextPath: Endpoint.Hostname
  description: Endpoint hostname
  type: string
- contextPath: Endpoint.Mac
  description: Endpoint mac addresses
  type: unknown
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: Endpoint ip addresses
  type: unknown
- contextPath: Endpoint.Domain
  description: Endpoint domain
  type: string
