id: TIE - IOC Hunt
version: -1
name: TIE - IOC Hunt
description: |-
  Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

  Input:
  * Hash (default, takes all deferent hashes from context)

  Output:
  * All agents that files with "Hash" has been executed on (TIE)
  * Enrich Agents info from ePO
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: b79d975a-a6dc-4a66-8515-c8f4177b0a40
    type: start
    task:
      id: b79d975a-a6dc-4a66-8515-c8f4177b0a40
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 7d6bbf27-cbb1-4766-81f9-ce96403a6190
    type: condition
    task:
      id: 7d6bbf27-cbb1-4766-81f9-ce96403a6190
      version: -1
      name: Is TIE enabled?
      description: Is the integration active?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    scriptarguments:
      left: {}
      right: {}
      value: {}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: McAfee Threat Intelligence Exchange
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
  "2":
    id: "2"
    taskid: 08329ca6-0fc5-433c-8ec0-86047d6bb1c1
    type: condition
    task:
      id: 08329ca6-0fc5-433c-8ec0-86047d6bb1c1
      version: -1
      name: Is ePO enabled?
      description: Is the integration active?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "6"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.brand
                iscontext: true
              right:
                value:
                  simple: epo
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: epo
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1080
        }
      }
  "3":
    id: "3"
    taskid: 0b0bbca0-86c6-411e-8aed-90bc5641660d
    type: regular
    task:
      id: 0b0bbca0-86c6-411e-8aed-90bc5641660d
      version: -1
      name: List all agents that the Hash has been executed on
      description: Get Agent GUIDS for the given hashes
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      iscommand: true
      brand: McAfee Threat Intelligence Exchange
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      file:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 519
        }
      }
  "4":
    id: "4"
    taskid: c283821d-46ac-4b77-8728-9bc136f0c729
    type: title
    task:
      id: c283821d-46ac-4b77-8728-9bc136f0c729
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 135,
          "y": 1492
        }
      }
  "5":
    id: "5"
    taskid: 2d39c3e4-e65f-4f14-82c1-057a08162227
    type: condition
    task:
      id: 2d39c3e4-e65f-4f14-82c1-057a08162227
      version: -1
      name: Did we find any relevant agents?
      description: Did we get any Agent GUIDS?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "8"
    scriptarguments:
      value:
        complex:
          root: File
          accessor: References.AgentGuid
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: File
                accessor: References.AgentGuid
            iscontext: true
    view: |-
      {
        "position": {
          "x": 430,
          "y": 703
        }
      }
  "6":
    id: "6"
    taskid: a4f50e6a-370e-48ba-83bb-a7b863c15036
    type: regular
    task:
      id: a4f50e6a-370e-48ba-83bb-a7b863c15036
      version: -1
      name: Get Agent info from ePO
      description: Get hostnames for the Agent GUIDS
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        complex:
          root: File
          accessor: References.AgentGuid
      taskID: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1326
        }
      }
  "7":
    id: "7"
    taskid: a08baee9-a402-4bc8-8cae-77c4c144d889
    type: title
    task:
      id: a08baee9-a402-4bc8-8cae-77c4c144d889
      version: -1
      name: Hunt HASH in TIE
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "8":
    id: "8"
    taskid: 1df1aefe-fce4-4fb8-80e0-3fbef311f772
    type: title
    task:
      id: 1df1aefe-fce4-4fb8-80e0-3fbef311f772
      version: -1
      name: Enrich in ePO
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 956
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "1_4_#default#": 0.1,
      "2_4_#default#": 0.17,
      "5_4_#default#": 0.11
    },
    "paper": {
      "dimensions": {
        "height": 1507,
        "width": 675,
        "x": 135,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
      b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
  required: false
  description: |-
    The Hash to hunt (Could be MD5,SHA1,SHA256).
    Default is set to all hashes
outputs:
- contextPath: File.References.AgentGuid
  description: The GUID of the system that referenced the file
  type: string
- contextPath: Endpoint.Hostname
  description: Hostname
  type: string
releaseNotes: "-"