id: Demisto_Self-Defense_-_Account_policy_monitoring_playbook
version: -1
name: Demisto Self-Defense - Account policy monitoring playbook
description: Get list of Demisto users through the REST API, and alert if any non-SAML user accounts are found.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 8d5e0af6-7ac8-49ce-8de7-60aed382e97b
    type: start
    task:
      id: 8d5e0af6-7ac8-49ce-8de7-60aed382e97b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 6b8b4358-fdfe-4b6d-8aa6-e6a94bfd62f3
    type: regular
    task:
      id: 6b8b4358-fdfe-4b6d-8aa6-e6a94bfd62f3
      version: -1
      name: List Demisto users
      description: send HTTP GET requests
      script: Demisto REST API|||demisto-api-get
      type: regular
      iscommand: true
      brand: Demisto REST API
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context:
        simple: DemistoUsers=response
      uri:
        simple: users
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 258
        }
      }
  "2":
    id: "2"
    taskid: e2febf92-f432-462c-883b-78aca9385909
    type: condition
    task:
      id: e2febf92-f432-462c-883b-78aca9385909
      version: -1
      name: Any non-SSO users?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isNotEmpty
          left:
            value:
              complex:
                root: DemistoUsers
                filters:
                - - operator: string.isNotEqual
                    left:
                      value:
                        simple: DemistoUsers.userType
                      iscontext: true
                    right:
                      value:
                        simple: SAML
            iscontext: true
    view: |-
      {
        "position": {
          "x": 448,
          "y": 443
        }
      }
  "3":
    id: "3"
    taskid: b0b658b0-9296-4eb8-8c59-b176bbe97a48
    type: title
    task:
      id: b0b658b0-9296-4eb8-8c59-b176bbe97a48
      version: -1
      name: Alert and Escalate
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 660
        }
      }
  "4":
    id: "4"
    taskid: 099ab147-084a-41c8-8eea-aaa3313cb343
    type: regular
    task:
      id: 099ab147-084a-41c8-8eea-aaa3313cb343
      version: -1
      name: Escalate to Critical
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      addLabels: {}
      amarkdownsection: {}
      anothernumberpleasejusttomakesure: {}
      arcsightcaseid: {}
      attach: {}
      attachamenthash: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      blah: {}
      booltest: {}
      compliance: {}
      customFields: {}
      customfield: {}
      daysbetweenreportcreation: {}
      details: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      hjhj: {}
      htmltypefield: {}
      id: {}
      important: {}
      importantfield: {}
      itaytestfield: {}
      labels: {}
      longtextone: {}
      longtexttoo: {}
      mailbody: {}
      multilinetext: {}
      name: {}
      numberplease: {}
      occurred: {}
      one: {}
      owner: {}
      phase: {}
      relatedincidentssummary: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity:
        simple: critical
      single: {}
      single2: {}
      sla: {}
      source: {}
      sourceip: {}
      sourceip1: {}
      subcat: {}
      subcategory: {}
      systems: {}
      team: {}
      test: {}
      test2: {}
      testfield: {}
      testhtml: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      tldr: {}
      tttttt: {}
      type: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 84,
          "y": 817
        }
      }
  "5":
    id: "5"
    taskid: 330b7f73-0b8a-4596-86e5-c30df8174098
    type: regular
    task:
      id: 330b7f73-0b8a-4596-86e5-c30df8174098
      version: -1
      name: Send alert to Slack channel
      script: slack|||slack-send
      type: regular
      iscommand: true
      brand: slack
    scriptarguments:
      IgnoreAddURL: {}
      channel:
        simple: csirt
      entry: {}
      group: {}
      message:
        simple: Non-SSO Demisto User detected!
      threadID: {}
      to: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 386,
          "y": 1018
        }
      }
  "6":
    id: "6"
    taskid: afebdda7-3635-4392-8634-2584a243cda5
    type: regular
    task:
      id: afebdda7-3635-4392-8634-2584a243cda5
      version: -1
      name: Send SMS alert
      script: Twilio|||TwilioSendSMS
      type: regular
      iscommand: true
      brand: Twilio
    scriptarguments:
      body:
        simple: Non-SSO Demisto User detected!
      from: {}
      to:
        simple: +1(XXX)666-1337
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 675,
          "y": 841
        }
      }
  "7":
    id: "7"
    taskid: 9c7d51bf-48c0-41a7-8280-2d91990ffd8c
    type: regular
    task:
      id: 9c7d51bf-48c0-41a7-8280-2d91990ffd8c
      version: -1
      name: Close
      scriptName: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 922,
          "y": 590
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "2_3_yes": 0.62
    },
    "paper": {
      "dimensions": {
        "height": 1063,
        "width": 1218,
        "x": 84,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "Get list of Demisto users through the REST API, and alert if any non-SAML user accounts are found."