id: 11d14ecb-be98-4cb1-8e69-7bb8d3e05f98
version: -1
name: IOC Hunt - TIE
description: |-
  Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

  Input:
  * Hash (default, takes all deferent hashes from context)

  Output:
  * All agents that files with "Hash" has been executed on (TIE)
  * Enrich Agents info from ePO
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 81f502a8-6bf0-480e-858e-8183d676a0cb
    type: start
    task:
      id: 81f502a8-6bf0-480e-858e-8183d676a0cb
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 85df1f35-fe50-4718-8a89-9980c243173d
    type: condition
    task:
      id: 85df1f35-fe50-4718-8a89-9980c243173d
      version: -1
      name: Is TIE enabled?
      description: Is the integration configured & active?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: McAfee Threat Intelligence Exchange
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
  "2":
    id: "2"
    taskid: ac9c1d4a-1f0b-4580-880f-e635dae5de8c
    type: condition
    task:
      id: ac9c1d4a-1f0b-4580-880f-e635dae5de8c
      version: -1
      name: Is ePO enabled?
      description: Is ePo configured and active?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "6"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: epo
          - - operator: string.isEqual
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1094
        }
      }
  "3":
    id: "3"
    taskid: 3d8b54c7-4821-47ed-8b0b-c49c0c1316e5
    type: regular
    task:
      id: 3d8b54c7-4821-47ed-8b0b-c49c0c1316e5
      version: -1
      name: List all agents that the Hash has been executed on
      description: get all Agent Guids for these hashes
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      iscommand: true
      brand: McAfee Threat Intelligence Exchange
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      file:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 518
        }
      }
  "4":
    id: "4"
    taskid: 037c09ff-b1db-4064-8547-5eb7ec154569
    type: title
    task:
      id: 037c09ff-b1db-4064-8547-5eb7ec154569
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 135,
          "y": 1492
        }
      }
  "5":
    id: "5"
    taskid: 9f3efd5f-2f98-4b12-8382-573aa82f20d6
    type: condition
    task:
      id: 9f3efd5f-2f98-4b12-8382-573aa82f20d6
      version: -1
      name: Did we find any relevant agents?
      description: Did any Guids return?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "8"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: File
          accessor: References.AgentGuid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 703
        }
      }
  "6":
    id: "6"
    taskid: 9433ab36-7e10-41ca-85e2-d7e88e52fac4
    type: regular
    task:
      id: 9433ab36-7e10-41ca-85e2-d7e88e52fac4
      version: -1
      name: Get Agent info from ePO
      description: Get hostnames for the Guids
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        complex:
          root: File
          accessor: References.AgentGuid
      taskID: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1325
        }
      }
  "7":
    id: "7"
    taskid: 6ce19051-8a2d-4bdd-81fb-e943643096a5
    type: title
    task:
      id: 6ce19051-8a2d-4bdd-81fb-e943643096a5
      version: -1
      name: Hunt HASH in TIE
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "8":
    id: "8"
    taskid: 2ff39268-9b09-4d89-8ecb-c696eb335295
    type: title
    task:
      id: 2ff39268-9b09-4d89-8ecb-c696eb335295
      version: -1
      name: Enrich in ePO
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 956
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "1_4_#default#": 0.1,
      "2_4_#default#": 0.17,
      "5_4_#default#": 0.11
    },
    "paper": {
      "dimensions": {
        "height": 1507,
        "width": 675,
        "x": 135,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
      b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
  required: false
  description: |-
    The Hash to hunt (Could be MD5,SHA1,SHA256).
    Default is set to all hashes
outputs:
- contextPath: File.References.AgentGuid
  description: The GUID of the system that referenced the file
  type: string
- contextPath: Endpoint.Hostname
  description: Hostname
  type: string
