id: playbook16
fromversion: 3.5.0
system: true
version: -1
name: CrowdStrike Rapid IOC Hunting
description: Hunt for endpoint activity involving hash and domain IOCs, using Crowdstrike Falcon Host.\nAlso use AnalystEmail label to determine where to send an email alert if something is found.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 64d3d099-e3f0-45ae-8898-c4530cf996b9
    type: start
    task:
      id: 64d3d099-e3f0-45ae-8898-c4530cf996b9
      version: -1
      description: ""
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: f7deb892-5c75-4528-86e3-fc138410907d
    type: condition
    task:
      id: f7deb892-5c75-4528-86e3-fc138410907d
      version: -1
      name: Are there MD5s to hunt?
      description: Check if a context key is set. Can also optionally provide a value
        argument to compare against context data for this key.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "6"
    scriptarguments:
      value:
        complex:
          root: File
          accessor: MD5
    continueonerror: true
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: MD5Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 499,
          "y": 515
        }
      }
  "3":
    id: "3"
    taskid: 5d7e0687-794a-40d1-8e0f-3140e8240419
    type: condition
    task:
      id: 5d7e0687-794a-40d1-8e0f-3140e8240419
      version: -1
      name: Are there SHA1s to hunt?
      description: Check if a context key is set. Can also optionally provide a value
        argument to compare against context data for this key.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "7"
    scriptarguments:
      value:
        complex:
          root: File
          accessor: SHA1
    continueonerror: true
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: SHA1Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 951,
          "y": 515
        }
      }
  "4":
    id: "4"
    taskid: c0fa045a-6ceb-43ae-8068-4da027d9a8cd
    type: condition
    task:
      id: c0fa045a-6ceb-43ae-8068-4da027d9a8cd
      version: -1
      name: Are there SHA256s to hunt?
      description: Check if a context key is set. Can also optionally provide a value
        argument to compare against context data for this key.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    scriptarguments:
      value:
        complex:
          root: File
          accessor: SHA256
    continueonerror: true
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: SHA256Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1402,
          "y": 515
        }
      }
  "6":
    id: "6"
    taskid: 1597138e-0ca4-47a0-8423-a56e51d912be
    type: regular
    task:
      id: 1597138e-0ca4-47a0-8423-a56e51d912be
      version: -1
      name: Hunt for devices running MD5
      description: |
        Returns a list of device IDs on which an indicator ran
      script: FalconHost|||cs-device-ran-on
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      type:
        simple: md5
      value:
        complex:
          root: inputs
          accessor: MD5Hash
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 690
        }
      }
  "7":
    id: "7"
    taskid: 6145759d-ec43-40fb-80c4-68743e707260
    type: regular
    task:
      id: 6145759d-ec43-40fb-80c4-68743e707260
      version: -1
      name: Hunt for devices accessing SHA1
      description: Returns a list of device IDs on which an indicator ran
      script: FalconHost|||cs-device-ran-on
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      type:
        simple: sha1
      value:
        complex:
          root: inputs
          accessor: SHA1Hash
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 690
        }
      }
  "8":
    id: "8"
    taskid: 0d38906e-dac1-4cc9-8ff7-5cd3b9309985
    type: regular
    task:
      id: 0d38906e-dac1-4cc9-8ff7-5cd3b9309985
      version: -1
      name: Hunt for devices accessing SHA256
      description: Returns a list of device IDs on which an indicator ran
      script: FalconHost|||cs-device-ran-on
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      type:
        simple: sha256
      value:
        complex:
          root: inputs
          accessor: SHA256Hash
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1512.5,
          "y": 690
        }
      }
  "9":
    id: "9"
    taskid: 34584bf7-5dbd-430d-8819-eb6f8a5536b1
    type: title
    task:
      id: 34584bf7-5dbd-430d-8819-eb6f8a5536b1
      version: -1
      description: ""
      name: Get device details and email
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 725,
          "y": 865
        }
      }
  "11":
    id: "11"
    taskid: f0de869e-18e4-4881-8cdc-fbfc9bd4b5af
    type: regular
    task:
      id: f0de869e-18e4-4881-8cdc-fbfc9bd4b5af
      version: -1
      name: Get device details
      description: Get device details
      script: FalconHost|||cs-device-search
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      filter: {}
      limit: {}
      offset: {}
      query:
        complex:
          root: FalconHostDevices
      value:
        simple: ${FalconHostDevices}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1512.5,
          "y": 1183
        }
      }
  "14":
    id: "14"
    taskid: 4bfa613f-2a85-4836-8256-61b0c2da4314
    type: condition
    task:
      id: 4bfa613f-2a85-4836-8256-61b0c2da4314
      version: -1
      name: Found any devices?
      description: Found any devices?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "11"
    scriptarguments:
      value:
        complex:
          root: FalconHostDevices
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: FalconHostDevices
            iscontext: true
    view: |-
      {
        "position": {
          "x": 725,
          "y": 1009
        }
      }
  "15":
    id: "15"
    taskid: 0be18d12-04e5-4109-89ff-b8f917d9bc38
    type: title
    task:
      id: 0be18d12-04e5-4109-89ff-b8f917d9bc38
      version: -1
      description: ""
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1167,
          "y": 1395
        }
      }
  "16":
    id: "16"
    taskid: e0aa833a-773a-45d6-8a5a-94c44c855b6d
    type: condition
    task:
      id: e0aa833a-773a-45d6-8a5a-94c44c855b6d
      version: -1
      name: Is FalconHost enabled?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "17"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.brand
                iscontext: true
              right:
                value:
                  simple: FalconHost
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: FalconHost
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 195
        }
      }
  "17":
    id: "17"
    taskid: 78d65ffe-90ed-4323-83dd-76ac86842582
    type: title
    task:
      id: 78d65ffe-90ed-4323-83dd-76ac86842582
      version: -1
      description: ""
      name: Hunt for indicators
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "3"
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 725,
          "y": 370
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "14_11_yes": 0.55,
      "4_8_yes": 0.56
    },
    "paper": {
      "dimensions": {
        "height": 1410,
        "width": 1393.5,
        "x": 499,
        "y": 50
      }
    }
  }
inputs:
- key: MD5Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: MD5 Hash
- key: SHA1Hash
  value:
    complex:
      root: File
      accessor: SHA1
  required: false
  description: SHA1 Hash
- key: SHA256Hash
  value:
    complex:
      root: File
      accessor: SHA256
  required: false
  description: SHA256 Hash
outputs:
- contextPath: FalconHostDevices
  description: Device IDs found by device IOC search
  type: string
