id: endpoint_enrichment_-_generic
version: -1
name: Endpoint Enrichment - Generic
fromversion: "3.5.0"
description: Enrich an Endpoint Hostname using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2aadae56-45ae-4e11-832a-f627bfd77f07
    type: start
    task:
      id: 2aadae56-45ae-4e11-832a-f627bfd77f07
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 57b61cf4-9764-4072-8397-2ef81ce7ad75
    type: title
    task:
      id: 57b61cf4-9764-4072-8397-2ef81ce7ad75
      version: -1
      name: Endpoint Products
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 370
        }
      }
  "2":
    id: "2"
    taskid: 622bd394-e7de-456e-87e8-5fef68be528e
    type: condition
    task:
      id: 622bd394-e7de-456e-87e8-5fef68be528e
      version: -1
      name: Is ePO enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: epo
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 660
        }
      }
  "3":
    id: "3"
    taskid: d1063167-eb02-4a96-88f3-6cf2a1a281b4
    type: condition
    task:
      id: d1063167-eb02-4a96-88f3-6cf2a1a281b4
      version: -1
      name: Is there an Endpoint Hostname to run on?
      description: Validate playbook input has hostname
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "24"
      - "1"
    scriptarguments:
      value:
        simple: ${inputs.Hostname}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value: inputs.Hostname
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "4":
    id: "4"
    taskid: 291509d3-03b4-4b9a-8e8f-174f33903161
    type: title
    task:
      id: 291509d3-03b4-4b9a-8e8f-174f33903161
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1062.5,
          "y": 1295
        }
      }
  "5":
    id: "5"
    taskid: 96700830-dd4f-4df5-87f7-6a40827b1909
    type: regular
    task:
      id: 96700830-dd4f-4df5-87f7-6a40827b1909
      version: -1
      name: Get host information from ePO
      description: 'ePO: Get host information'
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        simple: ${inputs.Hostname}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 906
        }
      }
  "6":
    id: "6"
    taskid: 44ac8ddd-a3c9-4286-8fc2-db7ebd57f949
    type: condition
    task:
      id: 44ac8ddd-a3c9-4286-8fc2-db7ebd57f949
      version: -1
      name: Is SentinelOne enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "7"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: sentinelOne
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 660
        }
      }
  "7":
    id: "7"
    taskid: a5bcb6cc-a0bd-4487-8e86-9886b498fa6b
    type: regular
    task:
      id: a5bcb6cc-a0bd-4487-8e86-9886b498fa6b
      version: -1
      name: Get host information from SentinelOne
      description: 'SentinelOne: Get host information'
      script: sentinelOne|||so-agents-query
      type: regular
      iscommand: true
      brand: sentinelOne
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 962.5,
          "y": 906
        }
      }
  "8":
    id: "8"
    taskid: 783a05fe-2276-400c-8f83-fa1d3d0efaea
    type: condition
    task:
      id: 783a05fe-2276-400c-8f83-fa1d3d0efaea
      version: -1
      name: Is Carbon Black Enterprise Response enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "9"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: carbonblack
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 660
        }
      }
  "9":
    id: "9"
    taskid: e09bb022-dda3-4d18-8e70-6bbd57542afe
    type: regular
    task:
      id: e09bb022-dda3-4d18-8e70-6bbd57542afe
      version: -1
      name: Get host information from Carbon Black Enterprise Response
      description: 'Carbon Black Enterprise Response: Get host information '
      script: carbonblack|||cb-sensor-info
      type: regular
      iscommand: true
      brand: carbonblack
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      agent_id: {}
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      groupid: {}
      hostname:
        simple: ${inputs.Hostname}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      ip: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      searchText:
        simple: ${inputs.Hostname}
      sensor: {}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 906
        }
      }
  "10":
    id: "10"
    taskid: c5eda198-6d1c-4b43-860a-dbcd60349cf1
    type: condition
    task:
      id: c5eda198-6d1c-4b43-860a-dbcd60349cf1
      version: -1
      name: Is CrowdStrike Falcon Host enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "25"
    scriptarguments:
      extend-context: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: FalconHost
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2300,
          "y": 660
        }
      }
  "14":
    id: "14"
    taskid: a5243da2-8932-440d-811b-8e36db1894d7
    type: condition
    task:
      id: a5243da2-8932-440d-811b-8e36db1894d7
      version: -1
      name: Is Cylance Protect enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "15"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: Cylance Protect
          - - operator: string.isEqual
              left:
                value: modules.state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 660
        }
      }
  "15":
    id: "15"
    taskid: 754a0f01-15ac-43a0-86dc-4b5d39a9287c
    type: regular
    task:
      id: 754a0f01-15ac-43a0-86dc-4b5d39a9287c
      version: -1
      name: Get host information from Cylance Protect
      description: ' Cylance Protect: Get host information'
      script: Cylance Protect|||cylance-protect-get-devices
      type: regular
      iscommand: true
      brand: Cylance Protect
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      filters:
        complex:
          root: inputs
          accessor: Hostname
          transformers:
          - operator: string.Concat
            args:
              prefix: '[{"Field":"device_name","Operator":"IsEqualTo","Value":"'
              suffix: '"}]'
      headers: {}
      page_number: {}
      page_size: {}
      searchText:
        simple: ${inputs.Hostname}
      sorts: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 906
        }
      }
  "16":
    id: "16"
    taskid: 86053c92-99d8-4b79-8b6d-0185e050f730
    type: title
    task:
      id: 86053c92-99d8-4b79-8b6d-0185e050f730
      version: -1
      name: ePO
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 515
        }
      }
  "17":
    id: "17"
    taskid: e1c09b5f-a35f-49a6-8199-d3df1031612f
    type: title
    task:
      id: e1c09b5f-a35f-49a6-8199-d3df1031612f
      version: -1
      name: Sentinel One
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 950,
          "y": 515
        }
      }
  "18":
    id: "18"
    taskid: eda63af2-7cf1-4069-812a-67f60a9c2dfa
    type: title
    task:
      id: eda63af2-7cf1-4069-812a-67f60a9c2dfa
      version: -1
      name: Carbon Black Enterprise Response
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 515
        }
      }
  "19":
    id: "19"
    taskid: 17990776-9803-4d5c-85fe-e7327e27ef51
    type: title
    task:
      id: 17990776-9803-4d5c-85fe-e7327e27ef51
      version: -1
      name: Cylance Protect
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1850,
          "y": 515
        }
      }
  "20":
    id: "20"
    taskid: 10af1189-7397-4173-813e-9cc0efa2abdb
    type: title
    task:
      id: 10af1189-7397-4173-813e-9cc0efa2abdb
      version: -1
      name: CrowdStrike Falcon Host
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2300,
          "y": 515
        }
      }
  "22":
    id: "22"
    taskid: bcd00e63-0038-480f-8ad7-ce66cd7d3eab
    type: condition
    task:
      id: bcd00e63-0038-480f-8ad7-ce66cd7d3eab
      version: -1
      name: Is Active Directory enabled?
      description: Check if there is any active instance of this brand
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "23"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value: brand
                iscontext: true
              right:
                value: activedir
          - - operator: string.isEqual
              left:
                value: state
                iscontext: true
              right:
                value: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -226,
          "y": 660
        }
      }
  "23":
    id: "23"
    taskid: 7f773da6-ac7b-46f8-88b4-96efe343edd9
    type: regular
    task:
      id: 7f773da6-ac7b-46f8-88b4-96efe343edd9
      version: -1
      name: Get host information from Active Directory
      description: 'Active Directory: Get host information'
      scriptName: ADGetComputer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      headers: {}
      name:
        simple: ${inputs.Hostname}
      nestedSearch: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -15,
          "y": 906
        }
      }
  "24":
    id: "24"
    taskid: 7d07aa94-b375-4088-836b-b1b2e453c12d
    type: title
    task:
      id: 7d07aa94-b375-4088-836b-b1b2e453c12d
      version: -1
      name: Active Directory
      type: title
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -226,
          "y": 503
        }
      }
  "25":
    id: "25"
    taskid: b235a8df-d976-4049-8520-86eec2027218
    type: playbook
    task:
      id: b235a8df-d976-4049-8520-86eec2027218
      version: -1
      name: CrowdStrike Endpoint Enrichment
      playbookName: CrowdStrike Endpoint Enrichment
      type: playbook
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 2300,
          "y": 1001
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1310,
        "width": 2906,
        "x": -226,
        "y": 50
      }
    }
  }
inputs:
- key: Hostname
  value:
    simple: ${Endpoint.Hostname}
  required: false
  description: The hostname to enrich
outputs:
- contextPath: Endpoint.Hostname
  description: Endpoint hostname
  type: string
- contextPath: Endpoint.Mac
  description: Endpoint mac addresses
  type: unknown
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: Endpoint ip addresses
  type: unknown
- contextPath: Endpoint.Domain
  description: Endpoint domain
  type: string
