id: TIE - IOC Hunt
version: -1
name: TIE - IOC Hunt
description: |-
  Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using McAfee TIE (requires ePO as well).

  Input:
  * Hash (default, takes all deferent hashes from context)

  Output:
  * All agents that files with "Hash" has been executed on (TIE)
  * Enrich Agents info from ePO
starttaskid: "0"
fromversion: 3.5.0
tasks:
  "0":
    id: "0"
    taskid: 80386f11-23d2-4ca7-8e8a-efc6c7d8b797
    type: start
    task:
      id: 80386f11-23d2-4ca7-8e8a-efc6c7d8b797
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 4267c141-4e26-42ac-8e3e-319f21b98c2f
    type: condition
    task:
      id: 4267c141-4e26-42ac-8e3e-319f21b98c2f
      version: -1
      name: Is TIE enabled?
      description: Is the integration active?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    scriptarguments:
      left: {}
      right: {}
      value: {}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: McAfee Threat Intelligence Exchange
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
  "2":
    id: "2"
    taskid: ef3ee4a1-06b8-471a-8ee2-900fcc693279
    type: condition
    task:
      id: ef3ee4a1-06b8-471a-8ee2-900fcc693279
      version: -1
      name: Is ePO enabled?
      description: Is the integration active?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "6"
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          root: modules
          filters:
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.brand
                iscontext: true
              right:
                value:
                  simple: epo
          - - operator: string.isEqual
              left:
                value:
                  simple: modules.state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: epo
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1080
        }
      }
  "3":
    id: "3"
    taskid: 056330fa-3260-41b6-8b05-22fc6ae903a7
    type: regular
    task:
      id: 056330fa-3260-41b6-8b05-22fc6ae903a7
      version: -1
      name: List all agents that the Hash has been executed on
      description: Get Agent GUIDS for the given hashes
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      iscommand: true
      brand: McAfee Threat Intelligence Exchange
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      file:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 519
        }
      }
  "4":
    id: "4"
    taskid: b000dc4b-e71b-43dc-87d3-da7fbeae2d91
    type: title
    task:
      id: b000dc4b-e71b-43dc-87d3-da7fbeae2d91
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 135,
          "y": 1492
        }
      }
  "5":
    id: "5"
    taskid: 5f1dbb77-12f1-468f-88a9-ea61a008cfe3
    type: condition
    task:
      id: 5f1dbb77-12f1-468f-88a9-ea61a008cfe3
      version: -1
      name: Did we find any relevant agents?
      description: Did we get any Agent GUIDS?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "8"
    scriptarguments:
      value:
        complex:
          root: File
          accessor: References.AgentGuid
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: File
                accessor: References.AgentGuid
            iscontext: true
    view: |-
      {
        "position": {
          "x": 430,
          "y": 703
        }
      }
  "6":
    id: "6"
    taskid: 1daed919-4f5e-4502-873f-3f31c6b8998f
    type: regular
    task:
      id: 1daed919-4f5e-4502-873f-3f31c6b8998f
      version: -1
      name: Get Agent info from ePO
      description: Get hostnames for the Agent GUIDS
      scriptName: EPOFindSystem
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      searchText:
        complex:
          root: File
          accessor: References.AgentGuid
      taskID: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1326
        }
      }
  "7":
    id: "7"
    taskid: ef3c7391-412b-4976-8fc4-f66cbe2607c4
    type: title
    task:
      id: ef3c7391-412b-4976-8fc4-f66cbe2607c4
      version: -1
      name: Hunt HASH in TIE
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "8":
    id: "8"
    taskid: 4795a873-58e7-4312-83ae-bd7e29d8e8f1
    type: title
    task:
      id: 4795a873-58e7-4312-83ae-bd7e29d8e8f1
      version: -1
      name: Enrich in ePO
      description: ""
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 430,
          "y": 956
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "1_4_#default#": 0.1,
      "2_4_#default#": 0.17,
      "5_4_#default#": 0.11
    },
    "paper": {
      "dimensions": {
        "height": 1507,
        "width": 675,
        "x": 135,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
      b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
  required: false
  description: |-
    The Hash to hunt (Could be MD5,SHA1,SHA256).
    Default is set to all hashes
outputs:
- contextPath: File.References.AgentGuid
  description: The GUID of the system that referenced the file
  type: string
- contextPath: Endpoint.Hostname
  description: Hostname
  type: string
releaseNotes: "-"