id: playbook11
version: -1
system: true
fromversion: 2.5.0
name: McAfee ePO Repository Compliance Playbook
description: Ensures that ePO servers are updated to the latest McAfee published AV
  signatures (DAT file version).
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ee018e04-2610-4998-87d0-f5217127bbad
    type: start
    task:
      id: ee018e04-2610-4998-87d0-f5217127bbad
      version: 1
      name: start_task
      issystemtask: true
      type: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
      - "2"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 4d3e8911-2cd9-4f8c-89fa-1d1418bc3dfa
    type: regular
    task:
      id: 4d3e8911-2cd9-4f8c-89fa-1d1418bc3dfa
      version: 1
      name: Retrieve DAT version and date from McAfee
      script: epo|||epo-get-latest-dat
      issystemtask: true
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "12"
    view: |-
      {
        "position": {
          "x": 281,
          "y": 246
        }
      }
  "4":
    id: "4"
    taskid: b7e28ac8-487e-4946-8316-7361f08ac1c5
    type: regular
    task:
      id: b7e28ac8-487e-4946-8316-7361f08ac1c5
      version: 1
      name: Initiate update task in each local repository
      script: epo|||epo-update-repository
      issystemtask: true
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      repos: ${olddatrepos}
    view: |-
      {
        "position": {
          "x": 348,
          "y": 604
        }
      }
  "5":
    id: "5"
    taskid: 620023d1-63b0-4834-81a2-74dd20437dda
    type: regular
    task:
      id: 620023d1-63b0-4834-81a2-74dd20437dda
      version: 1
      name: Send report to admin with update results
      scriptName: SendEmail
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      attachIDs: ""
      bcc: ""
      body: ePO Update Successful.
      cc: ""
      htmlBody: ""
      noteEntryID: ""
      subject: 'Demisto: ePO Update Results'
      to: ${incident.labels.adminEmail}
    view: |-
      {
        "position": {
          "x": 109,
          "y": 1361
        }
      }
  "7":
    id: "7"
    taskid: dccfaaf4-cca5-44d3-8818-6a5131b502ed
    type: regular
    task:
      id: dccfaaf4-cca5-44d3-8818-6a5131b502ed
      version: 1
      name: Send email alert with list of faulty repositories to admin
      scriptName: SendEmail
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      attachIDs: ""
      bcc: ""
      body: ePO Update Error. Please review status of Demisto incident ${incident.id}
        - ${incident.name}
      cc: ""
      htmlBody: ""
      noteEntryID: ""
      subject: 'Demisto: Faulty ePO Repositories Alert'
      to: ${incident.labels.adminEmail}
    view: |-
      {
        "position": {
          "x": 603,
          "y": 1321
        }
      }
  "10":
    id: "10"
    taskid: 220a0d1d-b7cc-403f-8750-526d3bf55b51
    type: regular
    task:
      id: 220a0d1d-b7cc-403f-8750-526d3bf55b51
      version: 1
      name: Close the investigation
      scriptName: CloseInvestigation
      issystemtask: true
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: ""
      reason: AuditCompleted
    view: |-
      {
        "position": {
          "x": -190,
          "y": 1710
        }
      }
  "11":
    id: "11"
    taskid: dd5d9578-ca9e-4a3b-8088-940627f3fe9e
    type: regular
    task:
      id: dd5d9578-ca9e-4a3b-8088-940627f3fe9e
      version: 1
      name: epo-get-current-dat
      description: check the existing DAT file version in ePO
      script: epo|||epo-get-current-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "12"
    view: |-
      {
        "position": {
          "x": -173,
          "y": 246
        }
      }
  "12":
    id: "12"
    taskid: 65c71a36-2fdb-413e-8c8d-80c60d16d91f
    type: condition
    task:
      id: 65c71a36-2fdb-413e-8c8d-80c60d16d91f
      version: 1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "10"
    scriptarguments:
      left: ${mcafee.latestDAT}
      right: ${mcafee.epoDAT=val.substr(1,val.indexOf('.'))}
    results:
    - AreValuesEqual
    view: |-
      {
        "position": {
          "x": 50,
          "y": 422
        }
      }
  "13":
    id: "13"
    taskid: d758c9d9-7e76-4b0b-8991-eef780abdf82
    type: regular
    task:
      id: d758c9d9-7e76-4b0b-8991-eef780abdf82
      version: 1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      seconds: "60"
    view: |-
      {
        "position": {
          "x": 348,
          "y": 770
        }
      }
  "14":
    id: "14"
    taskid: ea2cbbde-9240-4626-80b1-be87ef9175e0
    type: regular
    task:
      id: ea2cbbde-9240-4626-80b1-be87ef9175e0
      version: 1
      name: epo-get-current-dat
      description: check the existing DAT file version in ePO
      script: epo|||epo-get-current-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      extend-context: mcafee.newEpoDAT=productDetectionProductVersion
    view: |-
      {
        "position": {
          "x": 348,
          "y": 950
        }
      }
  "15":
    id: "15"
    taskid: 38be8d12-a8eb-47d8-857c-f3a824fbce20
    type: condition
    task:
      id: 38be8d12-a8eb-47d8-857c-f3a824fbce20
      version: 1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "5"
    scriptarguments:
      left: ${mcafee.latestDAT}
      right: ${mcafee.newEpoDAT=val.substr(1,val.indexOf('.'))}
    results:
    - AreValuesEqual
    view: |-
      {
        "position": {
          "x": 348,
          "y": 1130
        }
      }
  "16":
    id: "16"
    taskid: 5e480762-0617-4ad1-80e3-8bead4c6adf5
    type: regular
    task:
      id: 5e480762-0617-4ad1-80e3-8bead4c6adf5
      version: 1
      name: Set incident to High severity
      description: Modify incident info such as name, owner, type, etc.
      scriptName: IncidentSet
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      addLabels: ""
      customFieldName: ""
      customFieldValue: ""
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: High
      stage: ""
      type: ""
      updatePlaybookForType: ""
    view: |-
      {
        "position": {
          "x": 603,
          "y": 1540
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1755,
        "width": 1173,
        "x": -190,
        "y": 50
      }
    }
  }
