id: CrowdStrike Enrichment Playbook
version: -1
name: CrowdStrike Enrichment Playbook
system: true
fromversion: 2.5.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2380acff-abe1-46f1-8910-1aedfd2dd492
    type: start
    task:
      id: 2380acff-abe1-46f1-8910-1aedfd2dd492
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
      - "9"
      - "12"
      - "11"
      - "10"
    view: |-
      {
        "position": {
          "x": 1115,
          "y": 50
        }
      }
  "2":
    id: "2"
    taskid: 3105f277-5117-4c1e-8ccd-ccdd178ca962
    type: regular
    task:
      id: 3105f277-5117-4c1e-8ccd-ccdd178ca962
      version: -1
      name: Check MD5s
      script: FalconIntel|||file
      type: regular
      iscommand: true
      brand: FalconIntel
    scriptarguments:
      file: ${File.MD5}
    view: |-
      {
        "position": {
          "x": -347,
          "y": 504
        }
      }
  "3":
    id: "3"
    taskid: a47488ec-b99f-4b6c-8b1c-8237588a86b7
    type: regular
    task:
      id: a47488ec-b99f-4b6c-8b1c-8237588a86b7
      version: -1
      name: Check SHA1s
      script: FalconIntel|||file
      type: regular
      iscommand: true
      brand: FalconIntel
    scriptarguments:
      file: ${File.SHA1}
    view: |-
      {
        "position": {
          "x": 332,
          "y": 501
        }
      }
  "4":
    id: "4"
    taskid: afbc5729-8165-4c29-8f54-7a5af5366906
    type: regular
    task:
      id: afbc5729-8165-4c29-8f54-7a5af5366906
      version: -1
      name: Check SHA256s
      script: FalconIntel|||file
      type: regular
      iscommand: true
      brand: FalconIntel
    scriptarguments:
      file: ${File.SHA256}
    view: |-
      {
        "position": {
          "x": 885,
          "y": 504
        }
      }
  "5":
    id: "5"
    taskid: 8aff31d4-dfea-40b2-8f14-e60dea0a9fc9
    type: regular
    task:
      id: 8aff31d4-dfea-40b2-8f14-e60dea0a9fc9
      version: -1
      name: Check IPs
      script: FalconIntel|||ip
      type: regular
      iscommand: true
      brand: FalconIntel
    scriptarguments:
      file: ${File.SHA256}
      ip: ${IP.Address}
    view: |-
      {
        "position": {
          "x": 1866,
          "y": 501
        }
      }
  "6":
    id: "6"
    taskid: 462ebe6e-30b3-4856-8bec-0275247e7a5b
    type: regular
    task:
      id: 462ebe6e-30b3-4856-8bec-0275247e7a5b
      version: -1
      name: Check URLs
      script: FalconIntel|||url
      type: regular
      iscommand: true
      brand: FalconIntel
    scriptarguments:
      file: ${File.SHA256}
      ip: ${IP.Address}
      url: ${URL}
    view: |-
      {
        "position": {
          "x": 2452,
          "y": 504
        }
      }
  "7":
    id: "7"
    taskid: bfd8fbc4-2f42-4dc0-8e18-8c04a4d572c2
    type: condition
    task:
      id: bfd8fbc4-2f42-4dc0-8e18-8c04a4d572c2
      version: 1
      name: Is MD5 exists in incident
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "2"
    scriptarguments:
      value: ${File.MD5}
    view: |-
      {
        "position": {
          "x": 48,
          "y": 223
        }
      }
  "9":
    id: "9"
    taskid: b6d7ada6-dfd8-4c6c-83bf-5e9b13e90cc5
    type: condition
    task:
      id: b6d7ada6-dfd8-4c6c-83bf-5e9b13e90cc5
      version: 1
      name: Is SHA1 exists in incident
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "3"
    scriptarguments:
      value: ${File.SHA1}
    view: |-
      {
        "position": {
          "x": 630,
          "y": 223
        }
      }
  "10":
    id: "10"
    taskid: 2d59c415-6f7b-446b-8175-f1c1ef961e33
    type: condition
    task:
      id: 2d59c415-6f7b-446b-8175-f1c1ef961e33
      version: 1
      name: Is URL exists in Incident
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "6"
    scriptarguments:
      value: ${URL}
    view: |-
      {
        "position": {
          "x": 2375,
          "y": 223
        }
      }
  "11":
    id: "11"
    taskid: 9bb5684d-53d6-47b3-83c3-5cbd1dfb734e
    type: condition
    task:
      id: 9bb5684d-53d6-47b3-83c3-5cbd1dfb734e
      version: 1
      name: Is IP exists in incident
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "5"
    scriptarguments:
      value: ${IP.Address}
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 223
        }
      }
  "12":
    id: "12"
    taskid: 08e1c7d5-eeb6-4233-82ca-c19dfab17daf
    type: condition
    task:
      id: 08e1c7d5-eeb6-4233-82ca-c19dfab17daf
      version: 1
      name: Is SHA256 exists in incident
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "4"
    scriptarguments:
      value: ${File.SHA256}
    view: |-
      {
        "position": {
          "x": 1118,
          "y": 223
        }
      }
  "13":
    id: "13"
    taskid: d536069b-6d4e-47e2-8303-3c5503d7aa51
    type: title
    task:
      id: d536069b-6d4e-47e2-8303-3c5503d7aa51
      version: 1
      name: Done
      scriptName: Print
      type: title
      iscommand: false
      brand: ""
    scriptarguments:
      value: Done
    view: |-
      {
        "position": {
          "x": 1118,
          "y": 1008
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "10_13_#default#": 0.11,
      "10_6_yes": 0.53,
      "11_13_#default#": 0.21,
      "11_5_yes": 0.51,
      "12_13_#default#": 0.23,
      "12_4_yes": 0.5,
      "7_13_#default#": 0.1,
      "7_2_yes": 0.31,
      "9_13_#default#": 0.14,
      "9_3_yes": 0.39
    },
    "paper": {
      "dimensions": {
        "height": 1023,
        "width": 3179,
        "x": -347,
        "y": 50
      }
    }
  }
