id: c19e328d-0cf3-4a94-88b3-df670d984602
version: 23
name: SEP Test
description: This playbook tests the SEPM integration commands.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b9912ecc-bae9-40c5-8a5f-7cf8db6329f0
    type: start
    task:
      id: b9912ecc-bae9-40c5-8a5f-7cf8db6329f0
      version: 1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "3":
    id: "3"
    taskid: 902ca921-3e39-4e75-8c5a-c4e3acab59c0
    type: regular
    task:
      id: 902ca921-3e39-4e75-8c5a-c4e3acab59c0
      version: 1
      name: sep-system-info
      description: Get the system information (version, AV definition).
      script: SymantecEndpointProtection|||sep-system-info
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "7"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "7":
    id: "7"
    taskid: 24584df7-c160-496d-8a6c-f266b024a8b7
    type: regular
    task:
      id: 24584df7-c160-496d-8a6c-f266b024a8b7
      version: 1
      name: SEPVerifySystemInfo
      scriptName: SEPVerifySystemInfo
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      entryId: ${lastCompletedTaskEntries}
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "8":
    id: "8"
    taskid: a72628c1-8c8d-4061-8675-bd244c841950
    type: regular
    task:
      id: a72628c1-8c8d-4061-8675-bd244c841950
      version: 1
      name: sep-client-content
      description: Retrieves the client content.
      script: SymantecEndpointProtection|||sep-client-content
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "9"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "9":
    id: "9"
    taskid: 4800d344-b9fa-4555-8a50-e47fbbfcc00d
    type: regular
    task:
      id: 4800d344-b9fa-4555-8a50-e47fbbfcc00d
      version: 1
      name: SEPVerifyClientContent
      scriptName: SEPVerifyClientContent
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      entryId: ${lastCompletedTaskEntries}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "10":
    id: "10"
    taskid: e02eff34-c648-44d5-863f-3684775ac34a
    type: regular
    task:
      id: e02eff34-c648-44d5-863f-3684775ac34a
      version: 1
      name: sep-groups-info
      description: Get information about groups.
      script: SymantecEndpointProtection|||sep-groups-info
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "12"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "11":
    id: "11"
    taskid: 2186a3f5-eb6f-4b0e-872a-383d35b2def7
    type: regular
    task:
      id: 2186a3f5-eb6f-4b0e-872a-383d35b2def7
      version: 1
      name: sep-endpoints-info hostname=WIN-EE8OQ1NRFR0
      description: Get information about endpoints.
      script: SymantecEndpointProtection|||sep-endpoints-info
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      columns: ""
      hostname: WIN-EE8OQ1NRFR0
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "12":
    id: "12"
    taskid: c3d11558-9718-49e2-8aa8-6cedb0ce2dbb
    type: regular
    task:
      id: c3d11558-9718-49e2-8aa8-6cedb0ce2dbb
      version: 1
      name: SEPVerifyGroupsInfo
      scriptName: SEPVerifyGroupsInfo
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      entryId: ${lastCompletedTaskEntries}
      extend-context: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "13":
    id: "13"
    taskid: a6ba6869-5bcb-45ac-8518-5d432da03963
    type: regular
    task:
      id: a6ba6869-5bcb-45ac-8518-5d432da03963
      version: 1
      name: SEPVerifyEndpointsInfo
      scriptName: SEPVerifyEndpointsInfo
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "16":
    id: "16"
    taskid: c63b6bb2-e021-42df-8fb0-776021ff3471
    type: regular
    task:
      id: c63b6bb2-e021-42df-8fb0-776021ff3471
      version: 1
      name: SEPScan (by hostname, don't wait)
      scriptName: SEPScan
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      hostname: ${SEPM.Endpoint.Hostname}
      interval: "1"
      ip: ""
      scanType: ScanNow_Quick
      timeout: "1"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
  "20":
    id: "20"
    taskid: 0e42a0b7-7a97-4fb9-8e8e-ab594152fe46
    type: regular
    task:
      id: 0e42a0b7-7a97-4fb9-8e8e-ab594152fe46
      version: 1
      name: DoNothing
      scriptName: DoNothing
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "41"
      - "36"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
  "21":
    id: "21"
    taskid: 618c65ce-3ea7-4683-8456-766915b61e22
    type: regular
    task:
      id: 618c65ce-3ea7-4683-8456-766915b61e22
      version: 1
      name: DeleteContextKey (SEPM)
      description: Deletes a key from the context.
      scriptName: DeleteContextKey
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "8"
    scriptarguments:
      extend-context: ""
      key: SEPM
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "22":
    id: "22"
    taskid: b6af1074-e1ce-4786-8890-516907c81862
    type: regular
    task:
      id: b6af1074-e1ce-4786-8890-516907c81862
      version: 1
      name: DoNothing
      scriptName: DoNothing
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
      - "10"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "23":
    id: "23"
    taskid: f9b01731-ca41-485d-8072-8cdb025462a1
    type: regular
    task:
      id: f9b01731-ca41-485d-8072-8cdb025462a1
      version: 1
      name: SEPVerifyCommandStatus (stateId = 0, still running)
      scriptName: SEPVerifyCommandStatus
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "30"
    scriptarguments:
      commandId: ${SEPM.LastCommand.[2].CommandId}
      entryId: ""
      stateId: "0"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2295
        }
      }
  "24":
    id: "24"
    taskid: 28d371e7-f4d8-4dc6-8c8c-5d6e39461960
    type: regular
    task:
      id: 28d371e7-f4d8-4dc6-8c8c-5d6e39461960
      version: 1
      name: sep-command-status (Scan command ID)
      description: Retrieves the status of a command.
      script: SymantecEndpointProtection|||sep-command-status
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      commandId: ${SEPM.LastCommand.[2].CommandId}
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2120
        }
      }
  "30":
    id: "30"
    taskid: 5aecec64-8df0-4c3c-8a1b-dfdb02dfbb45
    type: regular
    task:
      id: 5aecec64-8df0-4c3c-8a1b-dfdb02dfbb45
      version: 1
      name: All Done!
      scriptName: DoNothing
      type: regular
      iscommand: false
      brand: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2470
        }
      }
  "36":
    id: "36"
    taskid: bd63e308-de7c-4f4b-806f-e159d2415e10
    type: regular
    task:
      id: bd63e308-de7c-4f4b-806f-e159d2415e10
      version: 1
      name: sep-update-content (by IP, wait until done)
      description: Updates the content of the given client.
      script: SymantecEndpointProtection|||sep-update-content
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "40"
    scriptarguments:
      hostname: ""
      interval: ""
      ip: ${SEPM.Endpoint.IPAddresses.[0]}
      timeout: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "37":
    id: "37"
    taskid: e536e6cd-e837-42d8-8a9d-4210d79eed72
    type: regular
    task:
      id: e536e6cd-e837-42d8-8a9d-4210d79eed72
      version: 1
      name: 'SEPVerifyCommandStatus (command #1, done)'
      scriptName: SEPVerifyCommandStatus
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      commandId: ${SEPM.LastCommand.[1].CommandId}
      entryId: ""
      stateId: "3"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
  "39":
    id: "39"
    taskid: 54dc6712-acb0-4c61-8d7d-dc58d3483097
    type: regular
    task:
      id: 54dc6712-acb0-4c61-8d7d-dc58d3483097
      version: 1
      name: 'SEPVerifyCommandStatus (command #2, done)'
      scriptName: SEPVerifyCommandStatus
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      commandId: ${SEPM.LastCommand.[0].CommandId}
      entryId: ""
      stateId: "3"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
  "40":
    id: "40"
    taskid: aec99eeb-f4fa-4c1e-84c9-6beb2277e7d8
    type: regular
    task:
      id: aec99eeb-f4fa-4c1e-84c9-6beb2277e7d8
      version: 1
      name: DoNothing
      scriptName: DoNothing
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "39"
      - "37"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
  "41":
    id: "41"
    taskid: e016b106-b523-4bab-8647-cc552f3d0bbb
    type: regular
    task:
      id: e016b106-b523-4bab-8647-cc552f3d0bbb
      version: 1
      name: sep-quarantine (by hostname, wait until done)
      description: Quarantines the endpoint according to its policy.
      script: SymantecEndpointProtection|||sep-quarantine
      type: regular
      iscommand: true
      brand: SymantecEndpointProtection
    nexttasks:
      '#none#':
      - "40"
    scriptarguments:
      actionType: Quarantine
      hostname: ${SEPM.Endpoint.Hostname}
      interval: ""
      ip: ""
      timeout: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2515,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
