id: Arcsight - Get events related to the Case
version: -1
name: Arcsight - Get events related to the Case
description: |-
  Get the Case's Arcsight ResourceID from the ArcsightCaseID field, or the "ID" label. If neither is there, ask user for the ID.
  Use the resource ID to get full data for the case, the correlated/aggregate events underneath it, and all base events underneath them.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 607a5cb3-f71b-4fe2-8ca8-c7799c2ed832
    type: start
    task:
      id: 607a5cb3-f71b-4fe2-8ca8-c7799c2ed832
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    view: |-
      {
        "position": {
          "x": 425,
          "y": -659
        }
      }
  "1":
    id: "1"
    taskid: 99d98b0d-51ee-4819-8bb1-9580ca71c8b8
    type: regular
    task:
      id: 99d98b0d-51ee-4819-8bb1-9580ca71c8b8
      version: -1
      name: Arcsight - Get Case info
      description: Get a specific case from ESM
      script: ArcSight ESM|||as-get-case
      type: regular
      iscommand: true
      brand: ArcSight ESM
    scriptarguments:
      resourceId: ${incident.arcsightcaseid}
    view: |-
      {
        "position": {
          "x": 567,
          "y": 380
        }
      }
  "2":
    id: "2"
    taskid: 93787e94-68ef-4646-8a86-82c128f9892a
    type: regular
    task:
      id: 93787e94-68ef-4646-8a86-82c128f9892a
      version: -1
      name: Arcsight - get Event ID below the Case
      description: Returns all case event IDs
      script: ArcSight ESM|||as-get-case-event-ids
      type: regular
      iscommand: true
      brand: ArcSight ESM
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      caseId: ${incident.arcsightcaseid}
    view: |-
      {
        "position": {
          "x": 89,
          "y": 380
        }
      }
  "3":
    id: "3"
    taskid: 03be188a-b48c-467c-8879-cf89a3b5ea65
    type: regular
    task:
      id: 03be188a-b48c-467c-8879-cf89a3b5ea65
      version: -1
      name: Get the Events below the Case
      script: ArcSight ESM|||as-get-security-events
      type: regular
      iscommand: true
      brand: ArcSight ESM
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      endDate: ""
      ids: ${ArcSightESM.CaseEvents}
      startDate: ""
    view: |-
      {
        "position": {
          "x": 89,
          "y": 571
        }
      }
  "4":
    id: "4"
    taskid: 7f654da8-0f7a-4007-8f75-36ebd9296cdd
    type: condition
    task:
      id: 7f654da8-0f7a-4007-8f75-36ebd9296cdd
      version: -1
      name: Is ArcsightCaseID set?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "9"
    scriptarguments:
      value: ${incident.arcsightcaseid}
    view: |-
      {
        "position": {
          "x": 425,
          "y": -509
        }
      }
  "5":
    id: "5"
    taskid: f0248d07-ced8-4878-8dce-af05d1c46b4c
    type: condition
    task:
      id: f0248d07-ced8-4878-8dce-af05d1c46b4c
      version: -1
      name: Is ID label included?
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    scriptarguments:
      value: ${incident.labels.ID}
    view: |-
      {
        "position": {
          "x": 106,
          "y": -321
        }
      }
  "6":
    id: "6"
    taskid: 9b9c88f9-39da-4e55-8fee-648b67a11e12
    type: regular
    task:
      id: 9b9c88f9-39da-4e55-8fee-648b67a11e12
      version: -1
      name: Set ArcsightCaseID <-- ID label
      scriptName: IncidentSet
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      addLabels: ""
      customFieldName: ArcsightCaseID
      customFieldValue: ${incident.labels.ID}
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: ""
      stage: ""
      type: ""
      updatePlaybookForType: ""
    view: |-
      {
        "position": {
          "x": 269,
          "y": -108
        }
      }
  "7":
    id: "7"
    taskid: 2b6d2ec9-c419-46fe-8a9c-badc467ba746
    type: regular
    task:
      id: 2b6d2ec9-c419-46fe-8a9c-badc467ba746
      version: -1
      name: User - please insert Arcsight Case Resource ID
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      append: ""
      key: UserInput.ArcsightCaseID
      value: ""
    view: |-
      {
        "position": {
          "x": -140,
          "y": -108
        }
      }
  "8":
    id: "8"
    taskid: c9b44c59-36cd-4906-8113-ef2c93553faf
    type: regular
    task:
      id: c9b44c59-36cd-4906-8113-ef2c93553faf
      version: -1
      name: Set ArcsightCaseID from user input
      scriptName: IncidentSet
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      addLabels: ""
      customFieldName: ArcsightCaseID
      customFieldValue: ${UserInput.ArcsightCaseID}
      details: ""
      labels: ""
      name: ""
      owner: ""
      playbook: ""
      severity: ""
      stage: ""
      type: ""
      updatePlaybookForType: ""
    view: |-
      {
        "position": {
          "x": -140,
          "y": 57
        }
      }
  "9":
    id: "9"
    taskid: d722aebc-ddc2-4022-8577-e88f8869585d
    type: title
    task:
      id: d722aebc-ddc2-4022-8577-e88f8869585d
      version: -1
      name: Get case and event info
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "1"
    view: |-
      {
        "position": {
          "x": 328,
          "y": 231
        }
      }
  "10":
    id: "10"
    taskid: 31770e39-9146-473d-8111-c0af16c1c582
    type: regular
    task:
      id: 31770e39-9146-473d-8111-c0af16c1c582
      version: -1
      name: Get Base Events below the top-level event
      script: ArcSight ESM|||as-get-security-events
      type: regular
      iscommand: true
      brand: ArcSight ESM
    scriptarguments:
      endDate: ""
      ids: ${ArcSightESM.SecurityEvents.baseEventIds}
      startDate: ""
    view: |-
      {
        "position": {
          "x": 89,
          "y": 766
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1520,
        "width": 1087,
        "x": -140,
        "y": -659
      }
    }
  }
inputs: []
releaseNotes: "First version added"