id: crowdstrike_endpoint_enrichment
version: -1
name: CrowdStrike Endpoint Enrichment
fromversion: "3.5.0"
description: Enrich Endpoint with CrowdStrike
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ad3b3bef-6c79-4dba-8b25-5b0374aa7674
    type: start
    task:
      id: ad3b3bef-6c79-4dba-8b25-5b0374aa7674
      version: -1
      description: ""
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "3":
    id: "3"
    taskid: 468064a1-c0dd-4a19-83f7-c8c43d06d768
    type: title
    task:
      id: 468064a1-c0dd-4a19-83f7-c8c43d06d768
      version: -1
      description: ""
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    id: "4"
    taskid: 5b390dfa-ac7e-49e9-8faa-c8ed6ec4ec98
    type: condition
    task:
      id: 5b390dfa-ac7e-49e9-8faa-c8ed6ec4ec98
      version: -1
      name: Was device found?
      description: Check if there was any machine match to the hostname
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              simple: FalconHostDevices
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "5":
    id: "5"
    taskid: 77e64fb3-5cde-4bea-82bf-f93d239c9185
    type: regular
    task:
      id: 77e64fb3-5cde-4bea-82bf-f93d239c9185
      version: -1
      name: Get host information from CrowdStrike Falcon Host
      description: Get host information from CrowdStrike Falcon Host
      script: FalconHost|||cs-device-details
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      extend-context: {}
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 296,
          "y": 555
        }
      }
  "6":
    id: "6"
    taskid: 10ebd215-fd84-4a73-8f1b-3f9ab5c1d50b
    type: regular
    task:
      id: 10ebd215-fd84-4a73-8f1b-3f9ab5c1d50b
      version: -1
      name: Get Device ID
      description: Get CrowdStrike device id by hostname.
      script: FalconHost|||cs-device-search
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      filter:
        complex:
          root: inputs
          accessor: Hostname
          transformers:
          - operator: string.concat
            args:
              prefix: hostname:"
              suffix: '"'
      limit: {}
      offset: {}
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 626,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Hostname
  value:
    simple: ${Endpoint.Hostname}
  required: false
  description: The hostname to enrich
outputs:
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
