id: Carbon Black Rapid IOC Hunting
fromversion: 3.5.0
system: true
version: -1
name: Carbon Black Rapid IOC Hunting
description: Hunt for malicious indicators using Carbon Black
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: edc8b672-13e8-48fa-87c9-594118876ac4
    type: start
    task:
      id: edc8b672-13e8-48fa-87c9-594118876ac4
      version: -1
      name: ""
      description: Playbook start point
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 255509e0-b2e6-483c-8379-1968871458dc
    type: regular
    task:
      id: 255509e0-b2e6-483c-8379-1968871458dc
      version: -1
      name: CBFindHash
      description: Search Carbon Black for connection to specified MD5 hash(es).
      scriptName: CBFindHash
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      md5:
        complex:
          root: inputs
          accessor: Hash
    results:
    - found_file_locations
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 356,
          "y": 605
        }
      }
  "2":
    id: "2"
    taskid: 504da0d8-d8f5-4273-8954-d5d333dc5ca1
    type: condition
    task:
      id: 504da0d8-d8f5-4273-8954-d5d333dc5ca1
      version: -1
      name: Is Carbon Black enabled?
      description: Is Carbon Black enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${modules(val.brand == 'carbonblack' && val.state == 'active')}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: carbonblack
                accessor: brand
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 108ba97d-b9da-4162-808d-025b5f6b7986
    type: title
    task:
      id: 108ba97d-b9da-4162-808d-025b5f6b7986
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 769
        }
      }
  "4":
    id: "4"
    taskid: 4dc64cf1-acb2-47b5-87c8-88e0e90e6c11
    type: condition
    task:
      id: 4dc64cf1-acb2-47b5-87c8-88e0e90e6c11
      version: -1
      name: Do we have files to hunt?
      description: Do we have files to hunt?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    scriptarguments:
      value:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 356,
          "y": 371
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "2_3_#default#": 0.3,
      "2_4_yes": 0.5,
      "4_1_yes": 0.5,
      "4_3_#default#": 0.4
    },
    "paper": {
      "dimensions": {
        "height": 784,
        "width": 686,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: MD5 Hash
outputs:
- contextPath: found_file_locations
  description: Found file locations
  type: string
- contextPath: found_hashes
  description: Found hashes
  type: string
releaseNotes: "-"