id: playbook17
fromversion: 3.5.0
system: true
version: -1
name: Carbon black Protection Rapid IOC Hunting
description: Hunt for endpoint activity involving hash and domain IOCs, using Carbon
  black Protection (Bit9).
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: beabda04-030d-4f10-84f1-b1db9cf9e2b0
    type: start
    task:
      id: beabda04-030d-4f10-84f1-b1db9cf9e2b0
      version: -1
      name: start_task
      description: ""
      type: start
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "8":
    id: "8"
    taskid: 1cd3a55a-f365-447a-8492-bedec09c2f00
    type: regular
    task:
      id: 1cd3a55a-f365-447a-8492-bedec09c2f00
      version: -1
      name: Search hashes in the file catalog
      description: Searching The Bit9 file catalog for the hashes
      scriptName: CBPCatalogFindHash
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      md5:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 572
        }
      }
  "9":
    id: "9"
    taskid: 37bc6180-791e-482f-83ec-51b6ad2db9b6
    type: regular
    task:
      id: 37bc6180-791e-482f-83ec-51b6ad2db9b6
      version: -1
      name: Check if the hashes are included in any rules
      description: If the hashes have been approved or blocked in the past, they will
        be in existing rules. It is useful to see whether the hash was in some blacklist
        or whitelist or a person marked them as such, possibly with a comment explaining
        their reasons.
      scriptName: CBPFindRule
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      hash:
        complex:
          root: inputs
          accessor: Hash
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 734
        }
      }
  "10":
    id: "10"
    taskid: 4b401c8c-4ef1-44f2-8cac-d4ab87d7a013
    type: condition
    task:
      id: 4b401c8c-4ef1-44f2-8cac-d4ab87d7a013
      version: -1
      name: Is CarbonBlack Protection enabled?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "12"
    scriptarguments:
      value:
        simple: ${modules(val.brand == 'carbonblackprotection' && val.state == 'active')}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: carbonblackprotection
            iscontext: true
      - - operator: general.isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: string.isEqual
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 196
        }
      }
  "11":
    id: "11"
    taskid: 93a2df6f-0ee2-4693-8a43-327297f25cb0
    type: title
    task:
      id: 93a2df6f-0ee2-4693-8a43-327297f25cb0
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 902
        }
      }
  "12":
    id: "12"
    taskid: fe930938-3663-4da7-89f6-017dee5784d1
    type: condition
    task:
      id: fe930938-3663-4da7-89f6-017dee5784d1
      version: -1
      name: Do we have files to hunt?
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "8"
    scriptarguments:
      value:
        simple: ${File.MD5}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: general.isExists
          left:
            value:
              complex:
                root: inputs
                accessor: Hash
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 382
        }
      }
view: |-
  {
    "linkLabelsPosition": {
      "10_11_#default#": 0.36,
      "12_11_#default#": 0.16
    },
    "paper": {
      "dimensions": {
        "height": 917,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Hash
  value:
    complex:
      root: File
      accessor: MD5
  required: false
  description: The MD5 Hash to hunt for
outputs:
- contextPath: found_hashes
  description: The existing hashes that were found
  type: string
releaseNotes: "-"