id: entity_enrichment_generic
version: -1
fromversion: 3.5.0
name: Entity Enrichment - Generic
description: Enrich entities using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5da9b365-f082-4c0b-8d9d-4192f4f60600
    type: start
    task:
      id: 5da9b365-f082-4c0b-8d9d-4192f4f60600
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "1"
      - "9"
      - "10"
      - "12"
      - "11"
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 67
        }
      }
  "1":
    id: "1"
    taskid: 9147f8c1-f1f0-4712-834d-9fd5d28a5308
    type: playbook
    task:
      id: 9147f8c1-f1f0-4712-834d-9fd5d28a5308
      version: -1
      name: IP Enrichment - Generic
      description: Enrich IP using one or more integrations
      playbookName: IP Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      IP:
        simple: ${inputs.IP}
      InternalRange: {}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 225
        }
      }
  "2":
    id: "2"
    taskid: f37c42dc-519b-48c6-8f14-141e896089f1
    type: playbook
    task:
      id: f37c42dc-519b-48c6-8f14-141e896089f1
      version: -1
      name: URL Enrichment - Generic
      description: Enrich URL using one or more integrations
      playbookName: URL Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      url:
        simple: ${inputs.url}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 386
        }
      }
  "9":
    id: "9"
    taskid: 23989fe6-2b96-4a3b-816c-0e7aff48a8a6
    type: playbook
    task:
      id: 23989fe6-2b96-4a3b-816c-0e7aff48a8a6
      version: -1
      name: Email Address Enrichment - Generic
      description: Get email address reputation using one or more integrations
      playbookName: Email Address Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      Domain: {}
      Email:
        simple: ${inputs.Email}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 386
        }
      }
  "10":
    id: "10"
    taskid: 69dd9494-da06-47e5-8aa5-2bf549df2ba9
    type: playbook
    task:
      id: 69dd9494-da06-47e5-8aa5-2bf549df2ba9
      version: -1
      name: Endpoint Enrichment - Generic
      description: Enrich an Endpoint Hostname using one or more integrations
      playbookName: Endpoint Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "11":
    id: "11"
    taskid: 065ae30d-9a18-4af0-8167-f018f80a64f7
    type: playbook
    task:
      id: 065ae30d-9a18-4af0-8167-f018f80a64f7
      version: -1
      name: Domain Enrichment - Generic
      description: Enrich Domain using one or more integrations
      playbookName: Domain Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      Domain:
        simple: ${inputs.Domain}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 709
        }
      }
  "12":
    id: "12"
    taskid: 53c64bc6-e40c-44b3-81e1-7cbcfedb8122
    type: playbook
    task:
      id: 53c64bc6-e40c-44b3-81e1-7cbcfedb8122
      version: -1
      name: Account Enrichment - Generic
      description: Enrich Accounts using one or more integrations
      playbookName: Account Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      Username:
        simple: ${inputs.Username}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "13":
    id: "13"
    taskid: 34e5d858-d114-46a7-8d47-998be6e6f295
    type: playbook
    task:
      id: 34e5d858-d114-46a7-8d47-998be6e6f295
      version: -1
      name: File Enrichment - Generic
      description: Get file reputation using one or more integrations
      playbookName: File Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      MD5:
        simple: ${inputs.MD5}
      SHA1:
        simple: ${inputs.SHA1}
      SHA256:
        simple: ${inputs.SHA256}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
  "14":
    id: "14"
    taskid: 92a496cf-6c70-443f-8eb6-0fc78d81d1d6
    type: playbook
    task:
      id: 92a496cf-6c70-443f-8eb6-0fc78d81d1d6
      version: -1
      name: ""
      playbookName: DBot Indicator Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 926
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 954,
        "width": 810,
        "x": 50,
        "y": 67
      }
    }
  }
inputs:
- key: IP
  value:
    simple: ${IP.Address}
  required: false
  description: The IP addresses to enrich
- key: InternalRange
  value: {}
  required: false
  description: The internal range to check against the IPs
- key: MD5
  value:
    simple: ${File.MD5}
  required: false
  description: File MD5 to enrich
- key: SHA256
  value:
    simple: ${File.SHA256}
  required: false
  description: File SHA256 to enrich
- key: SHA1
  value:
    simple: ${File.SHA1}
  required: false
  description: File SHA1 to enrich
- key: url
  value:
    simple: ${URL.Data}
  required: false
  description: url to enrich
- key: Email
  value:
    simple: ${Account.Email.Address}
  required: false
  description: The email addresses to enrich
- key: Hostname
  value:
    simple: ${Endpoint.Hostname}
  required: false
  description: The hostname to enrich
- key: Username
  value:
    simple: ${Account.Username}
  required: false
  description: The Username to enrich
- key: Domain
  value:
    simple: ${Domain.Name}
  required: false
  description: The domain name to enrich
outputs:
- contextPath: Account.ID
  description: The unique Account DN (Distinguished Name)
  type: string
- contextPath: Domain
  description: The domain objects
  type: string
- contextPath: URL.Malicious
  description: whether url was detected as malicious
  type: unknown
- contextPath: URL.Vendor
  description: name of vendor who labeled as malicious
  type: string
- contextPath: URL.Description
  description: additional info on the url
  type: string
- contextPath: URL.Address
  description: The enriched URL
  type: string
- contextPath: Account.Email.Address
  description: The Email account full address
  type: string
- contextPath: IP
  description: The IP objects
  type: unknown
- contextPath: Account.Email.Domain
  description: The Email account domain
  type: string
- contextPath: Account.Email.NetworkType
  description: The Email account NetworkType (could be Internal/External)
  type: string
- contextPath: Account.Email.Username
  description: The Email account username
  type: string
- contextPath: Account.Email.Distance.Domain
  description: The compared domain
  type: unknown
- contextPath: Account.Email.Distance.Value
  description: 'The distance between the email domain and the compared domain '
  type: string
- contextPath: Account.Type
  description: Type of the Account entity
  type: string
- contextPath: Account.Username
  description: The Account username
  type: string
- contextPath: Account.Email
  description: The email address associated with the Account
- contextPath: Account.Groups
  description: The groups the Account is part of
  type: unknown
- contextPath: Account.DisplayName
  description: The Account display name
  type: string
- contextPath: Account.Manager
  description: The Account's manager
  type: string
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
- contextPath: DBotScore.Indicator
  description: The Indicator
  type: string
- contextPath: DBotScore.Type
  description: The Indicator Type
  type: string
- contextPath: DBotScore.Vendor
  description: The DBot score vendor
  type: string
- contextPath: DBotScore.Score
  description: The DBot score
  type: number
releaseNotes: "-"